= Create a BYOC Cluster on Azure
:description: Use the Redpanda Cloud UI to create a BYOC cluster on Azure.
:page-aliases: deploy:deployment-option/cloud/create-byoc-cluster-azure.adoc

Before you deploy a BYOC cluster on Azure, follow the prerequisites to ensure that your Azure subscription meets requirements.

== Prerequisites

=== Verify rpk version

Confirm you have a minimum version of Redpanda `rpk` v24.1. See xref:reference:rpk/rpk-version.adoc[`rpk version`] or xref:manage:rpk/intro-to-rpk.adoc[].

=== Check your Azure subscription

In the https://login.microsoftonline.com/[Azure Portal^], confirm that the dedicated subscription you intend to use with Redpanda includes the following: 

* Role: The Azure user must have the _Owner_ role in the subscription.

* Resources: The subscription must be registered for the following resource providers. See the https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/resource-providers-and-types[Microsoft documentation^]. 

** Microsoft.Compute
** Microsoft.ManagedIdentity
** Microsoft.Storage
** Microsoft.KeyVault
** Microsoft.Network
+
TIP: To check if an Azure resource provider is registered, run the following command using the Azure CLI or in the Azure Cloud Shell. For example, to check for Microsoft.Compute:
+
``` 
az provider show -n Microsoft.Compute
```

* Feature: The subscription must be registered for Microsoft.Compute/EncryptionAtHost. See the https://learn.microsoft.com/en-us/azure/virtual-machines/linux/disks-enable-host-based-encryption-cli#prerequisites[Microsoft documentation^].

* Quota: The subscription must have the following quota in the region where you will use Redpanda. See the https://learn.microsoft.com/en-us/azure/quotas/view-quotas[Microsoft documentation^].

** Standard LASv3-series vCPUs: 24
** Standard DADSv5-series vCPUs: 8

* Monitoring: Ensure that Azure Network Watcher is enabled in the NetworkWatcherRG resource group and the region where you will use Redpanda. See the https://learn.microsoft.com/en-us/azure/network-watcher/network-watcher-overview[Microsoft documentation^]. To enable it:
+
```
# Create the NetworkWatcherRG resource group
az group create --name 'NetworkWatcherRG' --location '<region_name>'

# Enable Network Watcher in <region_name>
az network watcher configure --resource-group 'NetworkWatcherRG' --locations '<region_name>' --enabled
```

=== Check Azure SKU restrictions

Check to ensure that the Azure subscription does not have any SKU restrictions for the VM sizes in the region where you intend to use Redpanda. Using the Azure CLI or in the Azure Cloud Shell, run:

----
az vm list-skus -l eastus2 --zone --size Standard_L8as_v3 --output table
az vm list-skus -l eastus2 --zone --size Standard_D2s_v3 --output table
az vm list-skus -l eastus2 --zone --size Standard_D2ads_v5 --output table
----

If you see restrictions, https://learn.microsoft.com/en-us/troubleshoot/azure/general/region-access-request-process[open a Microsoft support request^] to remove the restrictions. For example, checking the Standard_L8as_v3 VM SKU restriction in the eastus2 region for all zones could show:

[%nowrap,bash]
----
ResourceType     Locations    Name              Zones    Restrictions
---------------  -----------  ---------------   -------  ------------
virtualMachines  eastus2      Standard_L8as_v3   1,2,3    NotAvailableForSubscription, type: Zone, locations: eastus2, zones: 2,3
----

== Create a BYOC cluster

To create a Redpanda cluster in your Azure Virtual Network, follow the <<prerequisites,prerequisites>> then follow the instructions in the Redpanda Cloud UI. The UI contains the parameters necessary to successfully run `rpk cloud byoc apply`.  

See also: xref:get-started:cloud-overview.adoc#redpanda-cloud-architecture[Redpanda Cloud architecture].

. Log in to https://cloud.redpanda.com[Redpanda Cloud^].
. On the Clusters page, click *Create cluster*, then click *Create BYOC cluster*.
. Enter a cluster name, then select the resource group, provider (Azure), xref:reference:tiers/byoc-tiers.adoc[region, tier], availability, and Redpanda version. 
+
[NOTE]
==== 
* If you plan to create a private network in your own virtual network, select the region where your Azure Virtual Network is located.
* Multi-AZ is the default configuration. Three AZs provide two backups in case one availability zone goes down.
====
+ 
Optionally, click *Advanced settings* to specify up to five key-value custom tags. After the cluster is created, the tags are applied to all Azure resources associated with this cluster. For details, see the https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/tag-resources[Microsoft documentation^].

. Click *Next*.
. On the Network page, enter the connection type: either *Public* or *Private*. For BYOC clusters, *Private* using Azure Private Link is best-practice. 
** Your network name is used to identify this network.
** For a xref:networking:cidr-ranges.adoc[CIDR range], choose one that does not overlap with your existing VPCs or your Redpanda network.
. Click *Next*.
. On the Deploy page, follow the steps to log in to Redpanda Cloud and deploy the agent.
+
As part of agent deployment, Redpanda assigns the permissions required to run the agent. For details about these permissions, see xref:security:authorization/cloud-iam-policies-azure.adoc[Azure IAM policies].

== Next steps

xref:networking:azure-private-link.adoc[]
