= Create Remote Read Replicas
:description: Learn how to create a remote read replica topic with BYOC, which is a read-only topic that mirrors a topic on a different cluster.
:page-aliases: deploy:deployment-option/cloud/remote-read-replicas.adoc, manage:remote-read-replicas.adoc

A remote read replica topic is a read-only topic that mirrors a topic on a different cluster. You can create a separate remote cluster just for consumers of this topic and populate its topics from object storage. A read-only topic on a remote cluster can serve any consumer, without increasing the load on the source cluster. Because these read-only topics access data directly from object storage, there's no impact to the performance of the cluster. Remote read replica topics do not store any data. When a cluster running a remote read replica is terminated, the topic data only exists on the origin cluster.

Redpanda Cloud supports remote read replica topics in BYOC clusters on AWS or GCP. These clusters can be ephemeral; that is, created temporarily to handle specific or transient workloads, but they don't have to be. The ability to make them ephemeral provides flexibility and cost efficiency: you can scale resources up or down as needed and pay only for what you use. 

== Prerequisites

* A BYOC source cluster in Ready state.
* A BYOC reader cluster in Ready state. This separate reader cluster must exist in the same Redpanda organization as the source cluster.
** AWS: The reader cluster must be in the same region as the source cluster. The reader cluster must be in the same account as the source cluster.
** GCP: The reader cluster can be in the same or a different region as the source cluster. The reader cluster must be in the same project as the source cluster.
** Azure: Remote read replicas are not supported.

=== BYOVPC: Grant storage permissions

[NOTE]
====
This prerequisite only applies to BYOVPC deployments. Skip this step if you're enabling remote read replicas on standard BYOC clusters.

====

[tabs]
======
GCP::
+
--
To grant additional permissions to the cloud storage manager of the reader cluster, run:

```bash
gcloud storage buckets add-iam-policy-binding \
    gs://<source-cluster-tiered-storage-bucket-name> \
    --member="serviceAccount:<reader cluster redpanda_cluster_service_account email>" \
    --role="roles/storage.objectViewer"
```

--
AWS::
+
--

To grant additional permissions to the cloud storage manager of the reader cluster, set the `source_cluster_bucket_names`
and `reader_cluster_id` variables in https://github.com/redpanda-data/cloud-examples/blob/main/customer-managed/aws/terraform/variables.tf[cloud-examples^].
This should be done in the Terraform of the reader cluster.

--
======

== Configure remote read replica

Add or remove reader clusters to a source cluster in Redpanda Cloud with the xref:redpanda-cloud:manage:api/controlplane/index.adoc[Cloud Control Plane API]. For information on accessing the Cloud API, see the link:/api/doc/cloud-controlplane/authentication[authentication guide].

. To update your source cluster to add one or more reader cluster IDs, make a link:/api/doc/cloud-controlplane/operation/operation-clusterservice_updatecluster[`PATCH /v1/clusters/{cluster.id}`] request. The full list of clusters is expected on every call. If an ID is removed from the list, it is removed as a reader cluster.
+
```bash
export SOURCE_CLUSTER_ID=.......
export READER_CLUSTER_ID=.......

curl -X PATCH $API_HOST/v1/clusters/$SOURCE_CLUSTER_ID \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $API_TOKEN" \
-d @- << EOF 
{
  "read_replica_cluster_ids": ["$READER_CLUSTER_ID"] 
}
EOF
```

. Optional: To see the list of reader clusters on a given source cluster, make a link:/api/doc/cloud-controlplane/operation/operation-clusterservice_getcluster[`GET /v1/clusters/\{id}`] request:
+
```bash
export SOURCE_CLUSTER_ID=.......

curl -X GET $API_HOST/v1/clusters/$SOURCE_CLUSTER_ID \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $API_TOKEN"
```

[NOTE]
====
A source cluster cannot be deleted if it has remote read replica topics. When you delete a reader cluster, that cluster's ID is removed from any existing source cluster `read_replica_cluster_ids` lists.

====

== Create remote read replica

To create a remote read replica topic, run:

```bash
rpk topic create my-topic -c redpanda.remote.readreplica=<source-cluster-tiered-storage-bucket-name> --tls-enabled
```

For standard BYOC clusters, the source cluster tiered storage bucket name follows the pattern: `redpanda-cloud-storage-$\{SOURCE_CLUSTER_ID}`

== Optional: Tune for live topics

For remote read replicas reading from a live topic (that is, a topic that's being actively written to by a source cluster), it may be advantageous to control how often segments are flushed to object storage. By default, this is set to 60 minutes. To tune `cloud_storage_segment_max_upload_interval_sec` on the source cluster, contact https://support.redpanda.com/hc/en-us/requests/new[Redpanda support^]. (For cold topics, where segments are closed and older than 60 minutes, this configuration is unnecessary: the data is already uploaded to object storage.)
