= Schema Definition
:description: Have you ever wondered how to work with your fellows in one database without interfering with each other? Is it possible to organize the database obje
:page-topic-type: reference

== What is a schema?

Have you ever wondered how to work with your fellows in one database without interfering with each other? Is it possible to organize the database objects into logical groups which do not collide with the other objects’ names?

A schema addresses these needs:

A schema is a collection of tables. A schema also contains views, indexes, sequences, data types, operators, and functions. Redpanda SQL supports multiple schemas. For example, you can have a database named `oxla` and have multiple schemas based on your needs, such as `auth`, `model`, and `business`.

== Default schema in Redpanda SQL

By default, the `public` schema is used in Redpanda SQL. When unqualified `table_name` is used, that `table_name` is equivalent to `public.table_name`. It also applies to `CREATE`, `DROP`, and `SELECT TABLE` statements.

[NOTE]
====
Furthermore, you can create multiple schemas per your needs.
====

== Schema usage scenarios

=== Create a schema

The basic syntax of creating a schema is as follows:

[source,sql]
----
CREATE SCHEMA [IF NOT EXISTS] schema_name;
----

* `schema_name` is the schema name you are going to create.
* `IF NOT EXISTS` is an optional parameter to avoid errors if the schema already exists.

=== Create a table in schema

The syntax to create a table in a specified schema is as follows:

[source,sql]
----
CREATE TABLE schema_name.table_name(
...
);
----

* `schema_name` is the schema that you have created.
* `table_name` is the table name you are going to create.

=== Select a table in schema

After creating the table and inserting some data, display all rows with the following syntax:

[source,sql]
----
SELECT * FROM schema_name.table_name;
----

* `schema_name` is the name of the schema.
* `table_name` is the name of the table you want to display.

=== Drop the schema

Option 1: To drop an empty schema where no objects remain in it, use the following command:

[source,sql]
----
DROP SCHEMA [IF EXISTS] schema_name;
----

* `schema_name` is the schema name you are going to create.
* `IF EXISTS` is an optional parameter to avoid errors if the schema does not exist.

Option 2: Tables reside in a schema, so it is impossible to drop a schema without also dropping the tables. The following command drops the schema along with the tables.

[source,sql]
----
DROP SCHEMA schema_name CASCADE;
----

== Examples

=== Create schema

. First, connect to Redpanda SQL and create a schema:
+
[source,sql]
----
CREATE SCHEMA app_data;
----

. Next, create a table in the `app_data` schema with the following details:
+
[source,sql]
----
CREATE TABLE app_data.functions(
  id int,
  function_name text,
  active bool
);

INSERT INTO app_data.functions(id, function_name, active)
VALUES
('1111', 'Numeric', 'TRUE'),
('2222', 'Text', 'TRUE'),
('3333', 'Timestamp', 'TRUE'),
('4444', 'JSON', 'TRUE'),
('5555', 'Boolean', 'TRUE');
----

. You can verify and show the table with the following command:
+
[source,sql]
----
SELECT * FROM app_data.functions;
----

. You will get the following result:
+
[source,sql]
----
+------+---------------+---------+
| id   | function_name | active  |
+------+---------------+---------+
| 1111 | Numeric       | t       |
| 2222 | Text          | t       |
| 3333 | Timestamp     | t       |
| 4444 | JSON          | t       |
| 5555 | Boolean       | t       |
+------+---------------+---------+
----

=== Create schema using IF NOT EXISTS

To avoid errors when the schema already exists, use the `IF NOT EXISTS` option. Here is how it works:

==== Example without IF NOT EXISTS

. First, create the schema without using the `IF NOT EXISTS` option.
+
[source,sql]
----
CREATE SCHEMA analytics;
----
+
Output:
+
[source,sql]
----
CREATE SCHEMA
----

. If you attempt to create the schema again without using `IF NOT EXISTS`, it will result in an error.
+
[source,sql]
----
CREATE SCHEMA analytics;
----
+
Output:
+
[source,sql]
----
ERROR:  Schema: analytics already exists
----

==== Example with IF NOT EXISTS

Now, create the schema using the `IF NOT EXISTS` option to avoid the error.

[source,sql]
----
CREATE SCHEMA IF NOT EXISTS analytics;
----

Using `IF NOT EXISTS` allows the query to create a schema even if it already exists.

[source,sql]
----
CREATE
----

=== Drop schema

Use the following command to delete the schema and also the tables in it.

[source,sql]
----
DROP SCHEMA app_data CASCADE;
----

Another case is if there is no table or object created inside the schema, you can use the following command to drop the schema.

[source,sql]
----
DROP SCHEMA app_data;
----

=== Drop schema using IF EXISTS

==== Example without IF EXISTS

. First, drop the schema without using the `IF EXISTS` option.
+
[source,sql]
----
DROP SCHEMA analytics;
----
+
Output:
+
[source,sql]
----
DROP
----

. If you attempt to drop the schema again without using `IF EXISTS`, it will result in an error.
+
[source,sql]
----
DROP SCHEMA analytics;
----
+
Output:
+
[source,sql]
----
ERROR:  schema "analytics" does not exist
----

==== Example with IF EXISTS

Now, drop the schema using the `IF EXISTS` option.

[source,sql]
----
DROP SCHEMA IF EXISTS analytics;
----

Using `IF` EXISTS allows the query to succeed even if the schema does not exist.

[source,sql]
----
DROP
----
