= Text
:description: The text data type is a UTF8-encoded text with Unicode support, which stores a sequence of characters (text).
:page-topic-type: reference

The text data type is a UTF8-encoded text with Unicode support, which stores a sequence of characters (text).

== Examples

Let’s create an employee table with a text data type in each column:

[source,sql]
----
CREATE TABLE employee (
    employeeName text,
    employeeDept text,
    employeeRole text
);
INSERT INTO employee (employeeName, employeeDept, employeeRole)
VALUES ('John','Finance','Staff'),
       ('Maya','Product','Staff'),
       ('Jane','Finance','Staff'),
       ('Phil','HR','Manager');
----

[TIP]
====
Insert the text value between the single quotes `' '`.
====
The following output shows the created table:

[source,sql]
----
+---------------+---------------+---------------+
| employeename  | employeedept  | employeerole  |
+---------------+---------------+---------------+
| John          | Finance       | Staff         |
| Maya          | Product       | Staff         |
| Jane          | Finance       | Staff         |
| Phil          | HR            | Manager       |
+---------------+---------------+---------------+
----

== Text with SUBSTR function

The `substr()` function extracts a specific number of characters from a text.

=== Syntax

[source,sql]
----
substr( text, start_position, length )
----

The syntax includes the following parameters:

* `text`is the specified text.
* `start_position` is the starting position, specifying the part from which the substring is returned. Use an integer value.
* `length` determines the number of characters to extract. Use one or more characters.

[NOTE]
====
The first position in the `text` is 1.
====

=== Example

Insert a value into the text column.

[source,sql]
----
SELECT substr('Watermelon',6,5) AS "Fruit";
----

The following output shows the result:

[source,sql]
----
+-------------+
| Fruit       |
+-------------+
| melon       |
+-------------+
----

== Text with LENGTH function

The `length()` function returns the number of characters in a text.

[NOTE]
====
The number of characters might be different from the byte length.
====

=== Syntax

The length function will take a text as a parameter.

[source,sql]
----
LENGTH (text);
----

=== Example

Insert a value into the text column.

[source,sql]
----
SELECT LENGTH ('UNITED STATES');
----

The following output shows the result.

[source,sql]
----
+---------+
| f       |
+---------+
| 13      |
+---------+
----

[NOTE]
====
The `length()` function will also count spaces.
====
