= col_description()
:description: The link:https://www.postgresql.org/docs/current/functions-info.html#FUNCTIONS-INFO-COMMENT[col_description()] is a comment information function that 
:page-topic-type: reference

The link:https://www.postgresql.org/docs/current/functions-info.html#FUNCTIONS-INFO-COMMENT[col_description()] is a comment information function that retrieves the comment associated with a specified table column.

== Syntax

The syntax for the `col_description()` function is as follows:

....
col_description (table_oid, column_number) → NULL
....

== Parameters

The following parameters are required to execute this function:

* link:https://www.postgresql.org/docs/current/datatype-oid.html[table_oid]: specifies the object identifier (OID) of the table containing the column for which you want to retrieve the comment
* link:https://www.postgresql.org/docs/current/datatype-numeric.html#DATATYPE-INT[column_number]: indicates the ordinal position of the column within the table (starting from 1 for the first column)

[NOTE]
====
It is important to note that the column number must be provided as an object identifier (OID), which can be achieved by casting the table name to `regclass`
====

== Restrictions

* This function always returns `NULL` if there are no parameters specified
