= has_schema_privilege()
:description: The link:https://www.postgresql.org/docs/current/functions-info.html#FUNCTIONS-INFO-ACCESS[has_schema_privilege()^]has_schema_privilege is an access pr
:page-topic-type: reference

The link:https://www.postgresql.org/docs/current/functions-info.html#FUNCTIONS-INFO-ACCESS[has_schema_privilege()^]`has_schema_privilege` is an access privilege inquiry function that checks whether the current user has specific privileges on a schema.

== Syntax

There are two available syntax versions of the `has_schema_privilege` function:

.Version 1
[source,sql]
----
SELECT has_schema_privilege('user', 'schema', 'privilege');
----

.Version 2
[source,sql]
----
SELECT has_schema_privilege('schema', 'privilege');
----
No matter what syntax version is choosen, the `has_schema_privilege()` function always returns `TRUE (t)`.

== Parameters

These parameters are required to execute this function:

* `schema`: name of the schema for which to check privileges (can be any string value or string columns from other tables)
* `user`: name of the user who has the privileges (can be any string value)
* `privilege`: specifies the specific privilege to check for in the schema (the function supports `create` and `usage`)

[NOTE]
====
The comparison for the `privilege` is case-insensitive, so it does not matter whether lowercase or uppercase notation is used for the privilege name
====

== Examples

=== Check for `CREATE` privilege

This example uses the `has_schema_privilege()` function to determine if the current user has the `create` privilege on a schema named "`*public*`":

[source,sql]
----
SELECT has_schema_privilege('public', 'create');
----

This query returns `TRUE`, which means that the current user has a `create` privilege on the "`public`" schema.

[source,sql]
----
 has_schema_privilege
----------------------
 t
----

=== Check for `USAGE` privilege

Use the `has_schema_privilege()` function to check for the `usage` privilege on a schema. For example, to check if the current user can create objects in the "`*public*`" schema, run:

[source,sql]
----
SELECT has_schema_privilege('cahyo', 'public', 'USAGE');
----

This query returns `TRUE`, which means the current user has `usage` privilege on the "`*public*`" schema.

[source,sql]
----
 has_schema_privilege
----------------------
 t
----
