= nullif()
:description: The NULLIF() function replaces a given value with null if it matches a specific criterion.
:page-topic-type: reference

The `NULLIF()` function replaces a given value with null if it matches a specific criterion.

== Syntax

This example illustrates the syntax of the `NULLIF` function:

[source,sql]
----
NULLIF(argument_1,argument_2);
----

The `NULLIF` function takes two arguments:

* The first argument is the value to evaluate
* The second argument is the value to treat as null if the first argument matches it

[TIP]
====
*The Output*:
 If the first argument matches the second argument, the `NULLIF()` function returns *NULL*. Otherwise, it returns the first argument as-is.
====

== Examples

=== Handle equal values

In this case, use the `NULLIF` function to compare the values 4 and 4.

[source,sql]
----
SELECT NULLIF (4, 4);
----

The result will be `NULL` since the two values being compared are equal (4 = 4).

[source,text]
....
 if
----
....

=== Handle different values

This example uses the `NULLIF` function to manage different values.

[source,sql]
----
SELECT NULLIF (9, 0);
----

The result will be `9` because the second value in the `NULLIF` function is 0 (The two values are not equal).

[source,text]
----
 if

  9
----

=== String comparison

In this case, the `NULLIF` function compares the strings '`L`' and '`O`'.

[source,sql]
----
SELECT NULLIF ('L', 'O');
----

The result will be `L` because the two strings being compared ('`L`' and '`O`') are not equal. Therefore, the function returns the first string.

[source,text]
----
 if

 L
----

=== Handle default values

Suppose there is an `employees` table with columns for `name` and `salary`. This query retrieves employee names and their adjusted salaries, where a salary of 0 is replaced with NULL:

[source,sql]
----
CREATE TABLE employees (
    name TEXT,
    salary INT
);

INSERT INTO employees (name, salary)
VALUES
    ('John', 50000),
    ('Jane', 0),
    ('Roy', 0),
    ('NEil', 0),
    ('Michael', 75000);
----

Display the records of the table:

[source,sql]
----
SELECT * FROM employees;
----

[source,text]
----
  name   | salary
---------+--------
 John    |  50000
 Jane    |      0
 Roy     |      0
 NEil    |      0
 Michael |  75000
----

This query retrieves employee names and their adjusted salaries, where a salary of 0 is replaced with NULL:

[source,sql]
----
SELECT name, NULLIF(salary, 0) AS adjusted_salary
FROM employees;
----

The `NULLIF` function checks if the `salary` value is 0. If it is, the function returns NULL - otherwise, it returns the original `salary` value.

[source,text]
----
  name   | adjusted_salary
---------+-----------------
 John    |           50000
 Jane    |
 Roy     |
 NEil    |
 Michael |           75000
----

=== Avoid division by zero

Suppose there is a `fractions` table with columns, a `numerator` and a `denominator`.

[source,sql]
----
CREATE TABLE fractions (
    numerator INT,
    denominator INT
);

INSERT INTO fractions (numerator, denominator)
VALUES
    (10, 2),
    (20, 0),
    (15, 3),
    (75, 0),
    (15, 3);
----

Display the table using the `SELECT` statement:

[source,sql]
----
SELECT * FROM fractions;
----

[source,text]
----
 numerator | denominator
-----------+-------------
        10 |           2
        20 |           0
        15 |           3
        75 |           0
        15 |           3
----

Here, the `NULLIF` function is applied to the `denominator` column. If the `denominator` is 0, the function returns NULL, avoiding division by zero.

[source,sql]
----
SELECT numerator, denominator, numerator / NULLIF(denominator, 0) AS "result" FROM fractions;
----

The result is shown in the result column.

[source,text]
----
 numerator | denominator | result
-----------+-------------+--------
        10 |           2 |      5
        20 |           0 |
        15 |           3 |      5
        75 |           0 |
        15 |           3 |      5
----
