= pg_get_expr()
:description: The link:https://www.postgresql.org/docs/current/functions-info.html#FUNCTIONS-INFO-CATALOG[pg_get_expr()^] is a system catalog information function th
:page-topic-type: reference

The link:https://www.postgresql.org/docs/current/functions-info.html#FUNCTIONS-INFO-CATALOG[pg_get_expr()^] is a system catalog information function that retrieves the internal form of an individual expression, such as the default value for a column.

== Syntax

There are two available syntax versions of the `pg_get_expr()` function:

.Version 1
[source,sql]
----
SELECT pg_get_expr('expr_text', relation_oid);
----

.Version 2
[source,sql]
----
SELECT pg_get_expr('expr_text', relation_oid, pretty_bool);
----
Both versions of the `pg_get_expr()` function return an empty string `""`.

== Parameters

The following parameters are required to execute this function:

* `expr_text`: expression for which you want to obtain the internal representation (can be any string value)
* `relation_oid`: OID (Object Identifier) of the table the expression belongs to (integer type)
* `pretty_bool`: boolean value determining whether to format the expression in a more human-readable format (`TRUE`) or not (`FALSE`)

== Example

First, create a sample table named *employees*

[source,sql]
----
CREATE TABLE employees (
    id INT,
    name TEXT,
    salary TEXT
);
----

Then get the OID of the table

[source,sql]
----
SELECT oid FROM pg_class WHERE relname = 'employees';
----

[source,sql]
----
 oid
------
 1018
----

As the last step, retrieve the internal form for the `salary` column using the `pg_get_expr()` function

[source,sql]
----
-- Version 1
SELECT pg_get_expr('salary', 1018);

-- Version 2
SELECT pg_get_expr('salary', 1018, TRUE);
----

Executing any of the queries above returns the following output:

[source,sql]
----
 pg_get_expr
-------------
----
