= pg_get_indexdef()
:description: The link:https://www.postgresql.org/docs/current/functions-info.html#FUNCTIONS-INFO-CATALOG[pg_get_indexdef()] is a system catalog information functio

The link:https://www.postgresql.org/docs/current/functions-info.html++#++FUNCTIONS-INFO-CATALOG[pg++_++get++_++indexdef()] is a system catalog information function that reconstructs the PostgreSQL command used to retrieve the definition of a specified index.

== Syntax

Here are the two available syntax versions of the `pg++_++get++_++indexdef()` function:

.Version 1
[source,sql]
----
pg_get_indexdef(index_oid, column_oid)
----

.Version 2
[source,sql]
----
pg_get_indexdef(index_oid, column_oid, pretty_bool)
----

== Parameters

The following parameters are required to execute this function:

* `index++_++oid`: specifies the object identifier (OID) of the index
* `column++_++oid`: indicates the column number within the index (starting from 1)
* `pretty++_++bool`: controls whether to format the output in a human-readable way

== Example

In this example we’ll start from creating a sample table and an index for it

[source,sql]
----
CREATE TABLE sample_table(col int);
CREATE INDEX sample_index ON sample_table(col);
----

Once that is done, we can get the OID of the index in a following way

[source,sql]
----
SELECT oid FROM pg_class WHERE relname = 'sample_index';
----

[source,sql]
----
 oid
------
 16387
----

As the last step we’re going to retrieve the index definition

[source,sql]
----
SELECT pg_get_indexdef(16387);
----

Here is the reconstructed definition:

[source,sql]
----
                    pg_get_indexdef
-------------------------------------------------------
 CREATE INDEX sample_index ON public.sample_table(col)
(1 row)
----
