= JOIN
:description: JOIN clause is used to create a new table by combining records and using common fields between two tables in a database.
:page-topic-type: reference

`JOIN` clause is used to create a new table by combining records and using common fields between two tables in a database.

TIP: Table aliasing is supported in the `JOIN` clause.

== Syntax

=== JOIN ... ON

[source,sql]
----
SELECT table_1.column_1, table_2.column_2...
FROM table_1
JOIN table_2
ON table_1.common_field = table_2.common_field
----

. `SELECT table_1.column_1, table_2.column_2...` selects the columns to display from both tables.
. `FROM table_1 JOIN table_2` represents the joined tables.
. `ON table_1.common_field = table_2.common_field` compares each row of table_1 with each row of table_2 to find all pairs of rows that meet the join condition.
. When the condition is met, column values for each matched pair of rows from table_1 and table_2 are combined into a result row.

=== JOIN ... USING

[source,sql]
----
SELECT column_1, column_2...
FROM table_1
JOIN table_2
USING (column_name [, column_name2 ...])
----

The `USING` clause is a shorthand for joining tables when both tables share columns with the same name. Instead of writing `ON table_1.id = table_2.id`, you can write `USING (id)`. When joining on multiple shared columns, separate them with commas: `USING (id, name)`.

=== Table alias

You can use table aliasing to refer to the table’s name. An alias is a temporary name given to a table, column, or expression in a query.

The results will stay the same, but it can help you to write the query easier.

[source,sql]
----
SELECT left.column_1, right.column_2...
FROM table_1 as left
JOIN table_2 as right
ON left.common_filed = right.common_field
----

== Examples

Before we move on, let us assume two tables:

*movies table*

[source,sql]
----
CREATE TABLE movies (
  movie_id int,
  movie_name text,
  category_id int
);
INSERT INTO movies
    (movie_id, movie_name, category_id)
VALUES
    (201011, 'The Avengers', 181893),
    (200914, 'Avatar', 181894),
    (201029, 'Shutter Island', 181891),
    (201925, 'Tune in Your Love', 181892);
----

[source,sql]
----
SELECT * FROM movies;
----

It will create a table as shown below:

[source,sql]
----
+------------+-----------------------+--------------+
| movie_id   | movie_name            | category_id  |
+------------+-----------------------+--------------+
| 201011     | The Avengers          | 181893       |
| 200914     | Avatar                | 181894       |
| 201029     | Shutter Island        | 181891       |
| 201925     | Tune in Your Love     | 181892       |
+------------+-----------------------+--------------+
----

*categories table*

[source,sql]
----
CREATE TABLE categories (
  id int,
  category_name text
);
INSERT INTO categories
    (id, category_name)
VALUES
    (181891, 'Psychological Thriller'),
    (181892, 'Romance'),
    (181893, 'Fantasy'),
    (181894, 'Science Fiction'),
    (181895, 'Action');
----

[source,sql]
----
SELECT * FROM categories;
----

It will create a table as shown below:

[source,sql]
----
+--------------+-----------------------+
| id        | category_name            |
+-----------+--------------------------+
| 181891    | Psychological Thriller   |
| 181892    | Romance                  |
| 181893    | Fantasy                  |
| 181894    | Science Fiction          |
| 181895    | Action                   |
+-----------+--------------------------+
----

'''''

. Based on the above tables, we can write a `JOIN` query as follows:
+
[source,sql]
----
SELECT a.movie_name, c.category_name
FROM movies AS a
JOIN categories AS c
ON a.category_id = c.id;
----

. The above query will give the following result:
+
[source,sql]
----
+-----------------------+---------------------------+
| movie_name            | category_name             |
+-----------------------+---------------------------+
| Shutter Island        | Psychological Thriller    |
| Tune in Your Love     | Romance                   |
| The Avengers          | Fantasy                   |
| Avatar                | Science Fiction           |
+-----------------------+---------------------------+
----
+
The JOIN checks each row of the *category_id* column in the first table (*movies*) with the value in the *id* column of each row in the second table (*categories*).
+
If the values are equal, it will create a new row that contains columns from both tables (*category_name)* and adds the new row *(movie_name)* to the result set.
+
Below is the Venn diagram based on the example:
