= Redpanda Cloud Overview
:description: Learn about Redpanda Serverless, Bring Your Own Cloud (BYOC), and Dedicated clusters.
:page-aliases: cloud:dedicated-byoc.adoc, deploy:deployment-option/cloud/dedicated-byoc.adoc, deploy:deployment-option/cloud/cloud-overview.adoc


Redpanda Cloud is a complete data streaming platform delivered as a fully-managed service with automated upgrades and patching, data and partition balancing, and 24x7 support. It continuously monitors and maintains your clusters along with the underlying infrastructure to meet strict performance, availability, reliability, and security requirements. All Redpanda Cloud clusters are deployed with an integrated glossterm:Redpanda Console[].

TIP: For more detailed information about the Redpanda platform, see xref:get-started:intro-to-events.adoc[], xref:get-started:architecture.adoc[], and xref:get-started:byoc-arch.adoc[].

== Redpanda Cloud cluster types

Redpanda offers fully-managed cloud clusters for Serverless, BYOC, and Dedicated. All products have access to unlimited storage and 300+ data connectors with xref:develop:connect/about.adoc[Redpanda Connect].
|===
| <<Serverless>> | <<Bring Your Own Cloud (BYOC)>> | <<Dedicated>>

| For starter projects and applications with low or variable traffic. | For production clusters requiring data sovereignty, the highest throughput, and added security. | For production clusters requiring expert cloud hosting, higher throughput, and extra isolation.
| Multi-tenant in Redpanda Cloud on AWS | In your cloud on AWS, Azure, or GCP | Single-tenant in Redpanda Cloud on AWS, Azure, or GCP
| 100 MB/s max write throughput | 2 GB/s max write throughput | 400 MB/s max write throughput
| 300 MB/s max read throughput | 4 GB/s max read throughput | 800 MB/s max read throughput
| 5000 partitions | 112,500 partitions | 45,600 partitions
| 99.9% SLA | 99.99% SLA | 99.99% SLA
| Public networking | Public or private networking | Public or private networking
| SSO (GitHub, Google), Kafka ACLs | SSO (GitHub, Google, OIDC), RBAC, audit logs | SSO (GitHub, Google, OIDC), RBAC, audit logs
| Enterprise support with annual contracts | Enterprise support | Enterprise support
|===

[NOTE]
====

* The partition limit is the number of logical partitions before replication occurs. Redpanda Cloud uses a replication factor of three.
* Enterprise support is staffed by streaming experts around the clock Monday through Friday, plus immediate escalation for production outages 24/7.
* See also: <<Serverless vs BYOC/Dedicated>>
==== 

=== Serverless

Serverless is the fastest and easiest way to start data streaming. With Serverless clusters, you host your data in Redpanda's VPC, and Redpanda handles automatic scaling, provisioning, operations, and maintenance. This is a production-ready deployment option with a cluster available instantly, and with pay-as-you-go billing after the free trial, you only pay for what you consume. You can view detailed billing activity for each cluster and edit payment methods on the *Billing* page. 

NOTE: Serverless is currently in a limited availability (LA) release with xref:get-started:cluster-types/serverless.adoc#serverless-usage-limits[usage limits].

==== Sign up for Serverless

include::get-started:partial$get-started-serverless.adoc[] 

=== Bring Your Own Cloud (BYOC)

With BYOC clusters, you deploy the Redpanda glossterm:data plane[] into your existing VPC (for AWS and GCP) or VNet (for Azure), and all data is
contained in your own environment. This provides an additional layer of security and isolation. (See xref:get-started:byoc-arch.adoc[].) Redpanda manages provisioning, monitoring, upgrades, and security policies, and it manages required resources in your VPC or VNet, including subnets (subnetworks in GCP), IAM roles, and object storage resources (for example, S3 buckets or Azure Storage accounts). 

==== Bring Your Own VPC/VNet (BYOVPC/BYOVNet) 

With BYOVPC/BYOVNet clusters, you take full control of the networking lifecycle. Compared to standard BYOC, BYOVPC/BYOVNet provides more security, but the configuration is more complex. See the xref:get-started:cloud-overview.adoc#shared-responsibility-model[shared responsibility model] to understand what you manage versus what Redpanda manages.

The BYOC infrastructure that Redpanda manages should not be used to deploy any other workloads.

==== Sign up for BYOC

To start using BYOC, contact https://redpanda.com/try-redpanda?section=enterprise-trial[Redpanda sales^] to request a private offer with possible discounts. You are billed directly or through Google Cloud Marketplace or AWS Marketplace. 

=== Dedicated

With Dedicated clusters, you host your data on Redpanda Cloud resources (AWS, GCP, or Azure), and Redpanda handles provisioning, operations, and maintenance. Dedicated clusters are single-tenant deployments that support private networking (for example, VPC peering to talk over private IPs) for better data isolation.
When you create a Dedicated cluster, you select the supported xref:reference:tiers/dedicated-tiers.adoc[tier] that meets your compute and storage needs. 

==== Sign up for Dedicated

[tabs]
=====
Redpanda Sales::
+
--
To request a private offer with possible discounts for monthly or annual committed use, contact https://www.redpanda.com/price-estimator[Redpanda Sales^]. With a usage-based billing commitment, you sign up for a minimum spend amount through xref:billing:aws-commit.adoc[AWS Marketplace], xref:billing:azure-commit.adoc[Azure Marketplace], or xref:billing:gcp-commit.adoc[Google Cloud Marketplace]. You can then provision Dedicated clusters in Redpanda Cloud, and you can view invoices and manage your subscription in the marketplace.

Redpanda creates a cloud organization for you and sends you a welcome email.
--
AWS Marketplace::
+
--
New subscriptions to Redpanda Cloud through xref:billing:aws-pay-as-you-go.adoc[AWS Marketplace] receive $300 (USD) in free credits to spend in the first 30 days. AWS Marketplace charges for anything beyond $300, unless you cancel the subscription. After your free credits have been used, you can continue using your cluster without any commitment, only paying for what you consume and canceling anytime. 

Redpanda creates a cloud organization for you and sends you a welcome email. 
--
=====

== Serverless vs BYOC/Dedicated

Serverless clusters are a good fit for the following use cases:

* Starter and growing workloads
* Spiky workloads (that is, development environments, systems that only occasionally get busy, or workloads that come and go)
* Fast and dynamic cluster creation: you can use a Serverless cluster as an isolated container for topics

With Serverless (and for Dedicated when procured through the AWS Marketplace), you only pay for what you consume, without any commitment. A cluster is created instantly, so you can surface it in your applications (for example, for tenant isolation). If your workload increases, you can migrate it to a BYOC or Dedicated cluster.

Consider BYOC or Dedicated if you need more control over the deployment or if you have workloads with consistently-high throughput. BYOC and Dedicated clusters offer the following features:

* Private networking
* Multiple availability zones (AZs). A multi-AZ cluster provides higher resiliency in the event of a failure in one of the zones. 
* Ability to export Redpanda metrics to a third-party monitoring system
* Kafka Connect
* Higher limits and quotas. See xref:reference:tiers/byoc-tiers.adoc[BYOC usage tiers] and xref:reference:tiers/dedicated-tiers.adoc[Dedicated usage tiers] compared to xref:get-started:cluster-types/serverless.adoc#serverless-usage-limits[Serverless limits].

== Redpanda Cloud architecture

When you sign up for a Redpanda account, Redpanda creates an organization for you. Your organization contains all your Redpanda resources, including your clusters and networks. Within your organization, Redpanda creates a default resource group to contain your resources. You can rename this resource group, and you can create more resource groups. For example, you may want different resource groups for production and testing.

For details about the control plane - data plane framework in BYOC, see xref:get-started:byoc-arch.adoc[BYOC architecture].

== Shared responsibility model

The Redpanda Cloud shared responsibility model lists the security areas owned by Redpanda and the security areas owned by customers. Responsibilities depend on the type of deployment. 

[tabs]
=====
BYOC::
+
--
|===
| Resource | Redpanda responsibility | Customer responsibility

| Redpanda upgrades and hotfixes | &#10003; |   
| Cost management and attribution | &#10003; | &#10003; 
| Software vulnerability remediation | &#10003; |  
| Infrastructure vulnerability remediation | &#10003; |   
| IAM (roles, service accounts, access segmentation) | &#10003; | &#10003;  
| Compute | &#10003; |    
| Redpanda agent VM maintenance | &#10003; |  
| VPC (subnets, routing, firewall) | &#10003; | &#10003; 
| VPC peering |  | &#10003;  
| VPC private links (service endpoint) | &#10003; |  
| VPC private links (consumer endpoint) |  | &#10003;  
| Local storage | &#10003; |  
| Tiered Storage | &#10003; |  
| Control plane | &#10003; |     
| Access controls and audit | &#10003; | &#10003;  
| Managed disaster recovery |  | &#10003; 
| Observability and monitoring (SLOs, SLIs, tracing, alerting, runbooks) | &#10003; |    
| Availability service-level agreement (SLA) | &#10003; (subject to required access to customer resources) |  
| Proactive threat detection | &#10003; | &#10003;  
| Static secret rotation | &#10003; |  
| Incident response | &#10003; |     
| Resilience verification  | &#10003; |
| Kafka Connect infrastructure | &#10003; | &#10003;
| Kafka Connect tasks state  |  | &#10003; 
|===

--
BYOVPC/BYOVNet::
+
--
|===
| Resource | Redpanda responsibility | Customer responsibility

| Redpanda upgrades and hotfixes | &#10003; |   
| Cost management and attribution | &#10003; | &#10003;  
| Software vulnerability remediation | &#10003; |   
| Infrastructure vulnerability remediation | &#10003; | &#10003;  
| IAM (roles, service accounts, access segmentation) |  | &#10003;  
| Compute | &#10003; |   
| Redpanda agent VM maintenance | &#10003; |  
| VPC (subnets, routing, firewall) |  | &#10003;  
| VPC peering |  | &#10003;  
| VPC private links (service endpoint) | &#10003; |   
| VPC private links (consumer endpoint) |  | &#10003;  
| Local storage | &#10003; |   
| Tiered Storage |  | &#10003;  
| Control plane | &#10003; |   
| Access controls and audit | &#10003; | &#10003;  
| Managed disaster recovery |  |  &#10003; 
| Observability and monitoring (SLOs, SLIs, tracing, alerting, runbooks) | &#10003; | &#10003; (for VPC components and cloud storage buckets/containers managed by customer) 
| Availability SLA | &#10003; (subject to required access to customer resources) | &#10003;  
| Proactive threat detection | &#10003; | &#10003;  
| Static secret rotation | &#10003; | &#10003;  
| Incident response | &#10003; |   
| Resilience verification | &#10003; |
| Kafka Connect infrastructure | &#10003; | &#10003;
| Kafka Connect tasks state  |  | &#10003; 
|===

--
Dedicated::
+
--
|===
| Resource | Redpanda responsibility | Customer responsibility

| Redpanda upgrades and hotfixes | &#10003; |  
| Cost management and attribution | &#10003; |   
| Software vulnerability remediation | &#10003; |    
| Infrastructure vulnerability remediation | &#10003; |   
| IAM (roles, service accounts, access segmentation) | &#10003; |  
| Compute | &#10003; |  
| Redpanda agent VM maintenance | &#10003; |  
| VPC (subnets, routing, firewall) | &#10003; |   
| VPC peering | &#10003; |  
| VPC private links (service endpoint) | &#10003; |    
| VPC private links (consumer endpoint) |  | &#10003; 
| Local storage | &#10003; |   
| Tiered Storage | &#10003; |  
| Control plane | &#10003; |  
| Access controls and audit | &#10003; |  
| Managed disaster recovery |  | &#10003; 
| Observability and monitoring (SLOs, SLIs, tracing, alerting, runbooks) | &#10003; |   
| Availability SLA | &#10003; |  
| Proactive threat detection | &#10003; |  
| Static secret rotation | &#10003; |  
| Incident response | &#10003; |   
| Resilience verification  | &#10003; |
| Kafka Connect infrastructure  | &#10003; |
| Kafka Connect tasks state  |  | &#10003;
|===

--
=====

== Redpanda Connect and Kafka Connect

xref:develop:connect/about.adoc[Redpanda Connect] is integrated into Redpanda Cloud and available as a fully-managed service. Choose from a range of connectors, processors, and other components to quickly build and deploy streaming data pipelines or AI applications from the Cloud UI or using the link:/api/doc/cloud-dataplane/group/endpoint-redpanda-connect-pipeline[Data Plane API]. Comprehensive metrics, monitoring, and per pipeline scaling are also available. To start using Redpanda Connect, xref:develop:connect/connect-quickstart.adoc[try this quickstart].

xref:develop:managed-connectors/index.adoc[Kafka Connect] is disabled by default on all new clusters. To unlock this feature for your account, contact https://support.redpanda.com/hc/en-us/requests/new[Redpanda Support^]. Note that when Kafka Connect is enabled, there is a node running for Kafka Connect, even if connectors are not used.

== Redpanda Cloud vs Self-Managed feature compatibility

Because Redpanda Cloud is a fully-managed service that provides maintenance, data and partition balancing, upgrades, and recovery, much of the cluster maintenance required for Self-Managed users is not necessary for Redpanda Cloud users. Also, Redpanda Cloud is opinionated about Kafka configurations. For example, automatic topic creation is disabled. Some systems expect the Kafka service to automatically create topics when a message is produced to a topic that doesn't exist. (You can create topics in Redpanda Cloud on the *Topics* page or with `rpk topic create`.)

New clusters in Redpanda Cloud generally include functionality added in Self-Managed versions immediately. Existing clusters include new functionality when they get upgraded to the latest version. 

Redpanda Cloud deployments do not support the following functionality available in Redpanda Self-Managed deployments:

- Remote Read Replicas. This is in beta for Redpanda Cloud on AWS and GCP.
- Kafka API OIDC authentication. However, Redpanda Cloud does support xref:security:cloud-authentication.adoc#single-sign-on[SSO to the Redpanda Cloud UI].
- Admin API.
- FIPS-compliance mode.
- Kerberos authentication.
- Redpanda debug bundles.
- Redpanda Console topic documentation.
- Configuring access to object storage with customer-managed encryption key.
- Kubernetes Helm chart and Redpanda Operator functionality.
- The following `rpk` commands:
 
** `rpk cluster health`
** `rpk cluster license`
** `rpk cluster maintenance`
** `rpk cluster partitions`
** `rpk cluster self-test`
** `rpk cluster storage restore` (But `rpk cluster storage` and subcommands for mountable topics are supported in BYOC and Dedicated clusters)
** `rpk connect` 
** `rpk container` 
** `rpk debug` 
** `rpk generate app` (This is supported in Serverless clusters only.)
** `rpk iotune`
** `rpk redpanda`
** `rpk topic describe-storage` (All other `rpk topic` commands are supported on both Redpanda Cloud and Self Managed.)
+
NOTE: The `rpk cloud` commands are not supported in Self-Managed deployments.

== Features in limited availability

Features in limited availability are production-ready and are covered by Redpanda Support for early adopters.

The following features are currently in limited availability in Redpanda Cloud:

* Serverless
* Dedicated for Azure

== Features in beta

Features in beta are available for testing and feedback. They are not covered by Redpanda Support and should not be used in production environments.

The following features are currently in beta in Redpanda Cloud:

* BYOVPC for AWS  
* BYOVNet for Azure
* Secrets Management for BYOVPC on GCP and AWS
* Integration with Apache Iceberg
* Remote Read Replicas for AWS and GCP
* AI agents
* Several Redpanda Connect components 

== Next steps
* xref:manage:maintenance.adoc[Learn about upgrades and maintenance]
* xref:get-started:cluster-types/serverless.adoc[Create a Serverless cluster]
* xref:get-started:cluster-types/byoc/index.adoc[Create a BYOC cluster]
* xref:get-started:cluster-types/dedicated/create-dedicated-cloud-cluster-aws.adoc[Create a Dedicated cluster]

include::shared:partial$suggested-reading.adoc[]

* https://redpanda.com/blog/deploy-redpanda-clusters-cloud-aws-gcp[Bring Your Own Cloud (BYOC): best of both worlds^]

* https://redpanda.com/blog/data-sovereignty-fully-managed-cloud-byoc[A middle path for data sovereignty: Bring Your Own Cloud^]

include::shared:partial$suggested-video.adoc[]

* https://www.youtube.com/watch?v=gVlzsJAYT64&ab_channel=RedpandaData[YouTube - What is Redpanda BYOC? (3 mins)^]
