= What's New in Redpanda Cloud
:description: Summary of new features in Redpanada Cloud.
:tag-pipeline-service: api:ROOT:cloud-dataplane-api.adoc#tag--PipelineService
:page-aliases: deploy:deployment-option/cloud/whats-new-cloud.adoc
:page-toclevels: 1


This page lists new features added to Redpanda Cloud.

== April 2025

=== Redpanda Terraform provider: GA

The xref:manage:terraform-provider.adoc[Redpanda Terraform provider] is now generally available (GA). The provider lets you create and manage resources in Redpanda Cloud, such as clusters, topics, users, ACLs, networks, and resource groups.

== March 2025

=== Support for additional regions

xref:reference:tiers/byoc-tiers.adoc#byoc-supported-regions[BYOC clusters] on GCP now support the europe-southwest1 (Madrid) region.

=== BYOVPC support in the Redpanda Terraform provider 0.14.0: Beta

The link:https://registry.terraform.io/providers/redpanda-data/redpanda/latest/docs/resources/cluster#byovpc[Redpanda Terraform provider] now supports BYOVPC clusters on AWS and GCP. You can use the provider to create and manage BYOVPC clusters in Redpanda Cloud.

== February 2025

=== Role-based access control (RBAC) 

With xref:security:authorization/rbac/rbac.adoc[RBAC in the control plane], you can manage access to organization-level resources like clusters, resource groups, and networks. For example, you could grant everyone access to clusters in a development resource group while limiting access to clusters in a production resource group. Or, you could limit access to geographically-dispersed clusters in accordance with data residency laws. With xref:security:authorization/rbac/rbac_dp.adoc[RBAC in the data plane], you can configure cluster-level permissions for provisioned users at scale. 

=== Improved Private Service Connect support with AZ affinity

The latest version of the Redpanda xref:networking:gcp-private-service-connect.adoc[GCP Private Service Connect] service provides the ability to allow requests from Private Service Connect endpoints to stay within the same availability zone, avoiding additional networking costs. The service is now fully supported (GA). To upgrade, contact https://support.redpanda.com/hc/en-us/requests/new[Redpanda Support^]. 

IMPORTANT: Deprecated: The original GCP Private Service Connect service is deprecated and will be removed in a future release.

=== Serverless Pro usage limits increased

xref:get-started:cluster-types/serverless-pro.adoc[Usage limits for Serverless Pro] clusters increased to: ingress = 100 MBps, egress = 300 MBps, partitions = 5000, and topics = 3000.

=== Cloud API reference

The Cloud API reference is now provided as separate references for the xref:api:ROOT:cloud-controlplane-api.adoc[Control Plane API] and xref:api:ROOT:cloud-dataplane-api.adoc[Data Plane APIs]. The Control Plane API and Data Plane APIs follow separate OpenAPI specifications, so the reference is updated to better reflect the structure of the Cloud APIs and to improve usability of the documentation. See also: xref:manage:api/cloud-api-overview.adoc[].

== January 2025

=== New tiers and regions on Azure

xref:reference:tiers/index.adoc[Tiers 1-5] are now supported for BYOC and Dedicated clusters running on Azure. Also, the following xref:reference:tiers/dedicated-tiers.adoc#dedicated-supported-regions[regions] were added for Dedicated clusters: Central US, East US 2, Norway East. 

=== Serverless Pro: LA

xref:get-started:cluster-types/serverless-pro.adoc[Serverless Pro] is a new enterprise-level cluster option. It is similar to Serverless Standard, but with higher usage limits and Enterprise support. This is a limited availability (LA) release. To start using Serverless Pro, contact https://redpanda.com/try-redpanda?section=enterprise-trial[Redpanda Sales^]. 

=== AWS PrivateLink: GA

AWS PrivateLink is now generally available for private networking in the xref:networking:configure-privatelink-in-cloud-ui.adoc[Cloud UI] and the xref:networking:aws-privatelink.adoc[Cloud API].

== December 2024

=== Support for additional regions

For xref:reference:tiers/byoc-tiers.adoc#byoc-supported-regions[BYOC clusters], Redpanda added support for the following regions:

* GCP: europe-west9 (Paris), southamerica-west1 (Santiago)
* AWS: ap-southeast-3 (Jakarta), eu-north-1 (Stockholm), eu-south-1 (Milan), eu-west-3 (Paris)

=== Redpanda Connect updates

Redpanda Connect is now available on Dedicated clusters. This is a limited availability (LA) release. xref:develop:connect/configuration/secret-management.adoc[Secret management] is also available on BYOC, Dedicated, and Serverless clusters so that you can add secrets to your pipelines without exposing them.

=== Leader pinning

For a Redpanda cluster deployed across multiple availability zones (AZs), xref:develop:produce-data/leader-pinning.adoc[leader pinning] ensures that a topic's partition leaders are geographically closer to clients. Leader pinning can lower networking costs and help guarantee lower latency by routing produce and consume requests to brokers located in certain AZs.

== November 2024

=== BYOVPC on AWS: beta

With standard BYOC clusters, Redpanda manages security policies and resources for your VPC, including subnetworks, service accounts, IAM roles, firewall rules, and storage buckets. For the highest level of security, you can manage these resources yourself with a xref:get-started:cluster-types/byoc/aws/vpc-byo-aws.adoc[BYOVPC on AWS], previously known as _customer-managed VPC_. 

=== Customer-managed VNet on Azure: LA

With standard BYOC clusters, Redpanda manages security policies and resources for your virtual network (VNet), including subnetworks, managed identities, IAM roles, security groups, and storage accounts. For the highest level of security, you can manage these resources yourself with a xref:get-started:cluster-types/byoc/azure/vnet-azure.adoc[customer-managed VNet on Azure]. Because Azure functionality is provided in limited availability, to unlock this feature, contact https://support.redpanda.com/hc/en-us/requests/new[Redpanda support^]. 

== October 2024

=== BYOC support in the Terraform provider 0.10

The xref:manage:terraform-provider.adoc[Terraform provider] now supports BYOC clusters. You can use the provider to create and manage BYOC clusters in Redpanda Cloud.

=== Azure Marketplace for Dedicated clusters

You can contact https://redpanda.com/try-redpanda?section=enterprise-trial[Redpanda sales^] to request a private offer for monthly or annual xref:billing:azure-commit.adoc[committed use through the Azure Marketplace]. You can then quickly provision Dedicated clusters in Redpanda Cloud, and you can view your bills and manage your subscription directly in Azure Marketplace.

=== Support for AWS Graviton3

Redpanda now supports compute-optimized tiers with AWS Graviton3 processors. This saves over 50% in instance costs in all xref:reference:tiers/byoc-tiers.adoc[BYOC tiers].

=== Redpanda Terraform Provider for Redpanda Cloud: beta

The xref:manage:terraform-provider.adoc[Redpanda Terraform provider] lets you create and manage resources in Redpanda Cloud, such as clusters, topics, users, ACLs, networks, and resource groups.

== September 2024

=== Schedule maintenance windows

Redpanda Cloud now offers greater flexibility to schedule upgrades to your cluster. By default, Redpanda Cloud may run maintenance operations on any day at any time. You can override this default and * xref:manage:maintenance.adoc#maintenance-windows[schedule a maintenance window], which requires Redpanda Cloud to run operations on your specified day and time. 

=== Redpanda Connect: LA for BYOC, beta for Serverless

xref:develop:connect/about.adoc[Redpanda Connect] is now integrated into Redpanda Cloud and available as a fully-managed service. This is a limited availability (LA) release for BYOC and a beta release for Serverless. xref:develop:connect/components/catalog.adoc[Choose from a range of connectors, processors, and other components] to quickly build and deploy streaming data pipelines or AI applications from the xref:develop:connect/connect-quickstart.adoc[Cloud UI] or using the pass:a,m[xref:{tag-pipeline-service}[Data Plane API\]]. Comprehensive metrics, monitoring, and per pipeline scaling are also available. To start using Redpanda Connect, xref:develop:connect/connect-quickstart.adoc[try this quickstart].

For more detailed information about recent component updates, see xref:redpanda-connect:ROOT:whats_new_rpcn.adoc[What's New in Redpanda Connect].

=== Dedicated on Azure: LA

Redpanda now supports xref:get-started:cluster-types/dedicated/create-dedicated-cloud-cluster-aws.adoc[Dedicated clusters on Azure]. This is a limited availability (LA) release for Dedicated clusters. 

=== Remote read replicas on customer-managed VPC

The beta release of xref:get-started:cluster-types/byoc/remote-read-replicas.adoc[remote read replicas] has been extended to support customer-managed VPC deployments. 

== July 2024

=== Redpanda Cloud docs

The https://docs.redpanda.com/home/[Redpanda Docs site] has been redesigned for an easier experience navigating Redpanda Cloud docs. We hope that our docs help and inspire our users. Please share your feedback with the links at the bottom of any doc page. 

=== BYOC on Azure: LA

Redpanda now supports xref:get-started:cluster-types/byoc/azure/create-byoc-cluster-azure.adoc[BYOC clusters on Azure]. This is a limited availability (LA) release for BYOC clusters. 

=== Enhancements to Serverless: LA 

* The xref:manage:api/cloud-serverless-controlplane-api.adoc[Redpanda Cloud API] now includes support for xref:get-started:cluster-types/serverless.adoc[Serverless]. 
* The Redpanda Schema Registry API is now exposed for Serverless.
* Serverless subscriptions can now see detailed billing activity on the *Billing* page. 
* Serverless added a 99.5% uptime https://www.redpanda.com/legal/redpanda-cloud-service-level-agreement[SLA] (service level agreement).

=== Self service sign up for Dedicated on AWS Marketplace

To start using Dedicated, sign up on the xref:billing:aws-pay-as-you-go.adoc[AWS Marketplace]. New subscriptions receive $300 (USD) in free credits to spend in the first 30 days. AWS Marketplace charges for anything beyond $300, unless you cancel the subscription. After your credits have been used, you can continue using your cluster without any commitment, only paying for what you consume.

=== Support for additional regions

For xref:reference:tiers/byoc-tiers.adoc#byoc-supported-regions[BYOC clusters] and xref:reference:tiers/dedicated-tiers.adoc#dedicated-supported-regions[Dedicated clusters], Redpanda added support for the following regions:

* GCP: asia-east1 (Taiwan), asia-northeast1 (Tokyo), southamerica-east1 (São Paulo)
* AWS: ap-east-1 (Hong Kong), ap-northeast-1 (Tokyo), me-central-1 (UAE)

== June 2024

=== Remote read replica topics on BYOC: beta

You can now create xref:get-started:cluster-types/byoc/remote-read-replicas.adoc[remote read replica topics] on a BYOC cluster with the Cloud API. A remote read replica topic is a read-only topic that mirrors a topic on a different cluster. It can serve any consumer, without increasing the load on the source cluster. 

=== Higher connection limits in usage tiers

Redpanda has increased the number of client connections in all xref:reference:tiers/byoc-tiers.adoc[tiers]. For example, tier 1 now supports up to 9,000 maximum connections, and tier 9 supports up to 450,000 maximum connections. Connections are regulated per broker for best performance. 

== May 2024

=== Cloud API: beta

The Cloud API allows you to programmatically manage clusters and resources in your Redpanda Cloud organization. For more information, see the xref:manage:api/cloud-api-quickstart.adoc[Cloud API Quickstart], the xref:manage:api/cloud-api-overview.adoc[Cloud API Overview], and the full xref:api:ROOT:cloud-controlplane-api.adoc[Control Plane API] and xref:api:ROOT:cloud-dataplane-api.adoc[Data Plane API] reference documentation.

=== mTLS authentication for Kafka API clients

mTLS authentication is now available for Kafka API clients. You can xref:security:cloud-authentication.adoc#mtls[enable mTLS] for your cluster using the Cloud API.

=== Manage private connectivity in the UI

You can now manage GCP Private Service Connect and AWS PrivateLink connections to your BYOC or Dedicated cluster on the *Cluster settings* page in Redpanda Cloud. See the steps for xref:networking:configure-privatelink-in-cloud-ui.adoc[PrivateLink] and xref:networking:configure-private-service-connect-in-cloud-ui.adoc[Private Service Connect].

=== Single message transforms

Redpanda now provides xref:develop:managed-connectors/transforms.adoc[single message transforms (SMTs)] to help you modify data as it passes through a connector, without needing additional stream processors.

=== Support for additional regions

* For xref:reference:tiers/byoc-tiers.adoc#byoc-supported-regions[BYOC clusters], Redpanda added support for the GPC us-west1 region (Oregon) and the AWS ap-south-1 region (Mumbai).

* For xref:reference:tiers/dedicated-tiers.adoc#dedicated-supported-regions[Dedicated clusters], Redpanda added support for the AWS ap-south-1 region. 

=== Simplified navigation and namespaces renamed resource groups

Redpanda Cloud has a simplified navigation, with clusters and networks available at the top level. It now has a global view of all resources in your organization. Namespaces are now called glossterm:resource group[,resource groups], although the functionality remains the same.

== April 2024

=== Additional cloud tiers for BYOC

When you create a BYOC or Dedicated cluster, you select a xref:reference:tiers/byoc-tiers.adoc[cloud tier] with the expected usage for your cluster, including the maximum ingress, egress, partitions (pre-replication), and connections. Redpanda has added tiers 8 and 9 for BYOC clusters, which provide higher supported configurations.

== March 2024

=== Serverless: limited availability

xref:get-started:cluster-types/serverless.adoc[Redpanda Serverless] moved out of beta and into limited availability (LA). This means that it has usage limits and no public SLA. During LA, existing clusters can scale to the usage limits, but new clusters may need to wait for availability. Serverless is the fastest and easiest way to start data streaming. It is a production-ready deployment option with automatically-scaling clusters available instantly. To start using Serverless, https://redpanda.com/try-redpanda/cloud-trial#serverless[sign up for a free trial^]. This is no base cost, and with pay-as-you-go billing after the trial, you only pay for what you consume. 

=== Authentication with SSO

Redpanda Cloud now supports OpenID Connect (OIDC) integration, so administrators can leverage existing identity providers for user authentication to your Redpanda organization with xref:security:cloud-authentication.adoc#single-sign-on[single sign-on] (SSO). Redpanda uses OIDC to delegate the authentication process to an external IdP, such as Okta. To enable this for your account, contact https://support.redpanda.com/hc/en-us/requests/new[Redpanda support^].

== February 2024

=== AWS PrivateLink

xref:networking:aws-privatelink.adoc[AWS PrivateLink] is now available as an easy and highly secure way to connect to Redpanda Cloud from your VPC. You can set up the PrivateLink endpoint service for a new cluster or an existing cluster. To enable AWS PrivateLink for your account, contact https://support.redpanda.com/hc/en-us/requests/new[Redpanda support^].

=== Additional cloud tiers

When you create a cluster, you select a xref:reference:tiers/byoc-tiers.adoc[cloud tier] with the expected throughput for your cluster, including the maximum ingress, egress, partitions, and connections. On February 5, Redpanda added tiers 6 and 7 for BYOC clusters, which provide higher throughput limits.

== January 2024

=== Usage-based billing in marketplace

Redpanda Cloud now supports xref:billing:billing.adoc[usage-based billing] for Dedicated clusters. Contact https://redpanda.com/try-redpanda?section=enterprise-trial[Redpanda sales^] to request a private offer for monthly or annual committed use. You can then use existing Google Cloud Marketplace or AWS Marketplace credits to quickly provision Dedicated Cloud clusters, and you can view your bills and manage your subscription directly in the marketplace.

== December 2023

=== Serverless clusters: beta

xref:get-started:cluster-types/serverless.adoc[Redpanda Serverless] is a managed streaming service (Kafka API) that completely abstracts users from scaling and operational concerns, and you only pay for what you consume. It's the fastest and easiest way to start event streaming in the cloud. You can try the beta release of Redpanda Serverless with a free trial. 

== November 2023

=== AWS BYOC support for ARM-based Graviton2

BYOC clusters on AWS now support ARM-based Graviton2 instances. This lowers VM costs and supports increased partition count.

=== Iceberg Sink connector

With the xref:develop:managed-connectors/create-iceberg-sink-connector.adoc[managed connector for Apache Iceberg], you can write data into Iceberg tables. This enables integration with the data lake ecosystem and efficient data management for complex analytics.

=== Schema Registry management

In the Redpanda Console UI, you can xref:manage:schema-reg/schema-reg-ui.adoc[perform Schema Registry operations], such as registering a schema, creating a new version of it, and configuring compatibility. The **Schema Registry** page lists verified schemas, including their serialization format and versions. Select an individual schema to see which topics it applies to.

=== Maintenance windows

With maintenance windows, you have greater flexibility to plan upgrades to your cluster. By default, Redpanda Cloud upgrades take place on Tuesdays. Optionally, on the **Cluster settings** page, you can select a window of specific off-hours for your business for Redpanda to apply updates. All times are in Coordinated Universal Time (UTC). Updates may start at any time during that window. 
