= ENDS_WITH
:description: The ENDS_WITH() function determines whether the first argument ends with a specified string in the second argument or not.
:page-topic-type: reference

The `ENDS_WITH()` function determines whether the first argument ends with a specified string in the second argument or not.

[source,sql]
----
ENDS_WITH(first_argument, 'second_argument')
----

* `first_argument`: the specified argument, which will be the search reference. It can be a string or a column name.
* `second_argument`: the specified argument, which will have the search keywords.

The input type will be `STRING`, and the return type is `BOOL`, shown as `true` or `false`.

*Special case:*

* Returns `NULL` for the `NULL` record.
* Returns `true` (including the `NULL` record) if the `second_argument` is not specified.

== Examples

=== `ENDS_WITH()` function using column

Consider a table named *courses*:

[source,sql]
----
CREATE TABLE courses (
  course_id int,
  course_name text,
  credits text
);
INSERT INTO courses
    (course_id, course_name, credits)
VALUES
    (2111,'Basics of Plant Biotechnology',2),
    (2102,'Biochemistry',3),
    (1241,'Statistics',3),
    (4142,'Microbial Biodiversity',2),
    (3262,'Introduction to Plant Pathology',3),
    (3233,'Enzyme Technology',2),
    (1201,'Rural Sociology',2);
----

[source,sql]
----
SELECT * FROM courses;
----

The query displays the table:

[source,sql]
----
+------------+----------------------------------+-----------+
| course_id  | course_name                      | credits   |
+------------+----------------------------------+-----------+
| 2111       | Basics of Plant Biotechnology    | 2         |
| 2102       | Biochemistry                     | 3         |
| 1241       | Statistics                       | 3         |
| 4142       | Microbial Biodiversity           | 2         |
| 3262       | Introduction to Plant Pathology  | 3         |
| 3233       | Enzyme Technology                | 2         |
| 1201       | Rural Sociology                  | 2         |
+------------+----------------------------------+-----------+
----

This query checks which values of the *course_name* column end with "`ology`" in the preceding table:

[source,sql]
----
SELECT course_name, ENDS_WITH(course_name, 'ology') FROM courses;
----

This returns true to all the courses with the name ending with **ology.** Otherwise*,* `false`.

[source,sql]
----
+----------------------------------+-------------+
| course_name                      | ends_with   |
+----------------------------------+-------------+
| Basics of Plant Biotechnology    | true        |
| Biochemistry                     | false       |
| Statistics                       | false       |
| Microbial Biodiversity           | false       |
| Introduction to Plant Pathology  | true        |
| Enzyme Technology                | true        |
| Rural Sociology                  | true        |
+----------------------------------+-------------+
----

=== `ENDS_WITH()` function with no specified argument

The **patients_data** table has a `NULL` value in the *allergies* column:

[source,sql]
----
CREATE TABLE patients_data (
  record_number int,
  patient_name text,
  height_in_cm int,
  weight_in_kg int,
  allergies text
);
INSERT INTO patients_data
    (record_number, patient_name, height_in_cm, weight_in_kg, allergies)
VALUES
    (2009000908,'Vivienne Desjardin',168,49,''),
    (2012000876,'Elizabeth Reinhard',163,55,''),
    (2015000965,'James McCarthy',188,70,'penicillin'),
    (2020000109,'Jose Ramirez',170,70,'sulfonamide'),
    (2020000222,'Stefani Ricci',170,70,'peniccilin');
----

[source,sql]
----
SELECT * FROM patients_data;
----

[source,sql]
----
+----------------+---------------------+---------------+--------------+-------------+
| record_number  | patient_name        | height_in_cm  | weight_in_kg | allergies   |
+----------------+---------------------+---------------+--------------+-------------+
| 2009000908     | Vivienne Desjardin  | 168           | 49           | null        |
| 2012000876     | Elizabeth Reinhard  | 163           | 55           | null        |
| 2015000965     | James McCarthy      | 188           | 70           | penicillin  |
| 2020000109     | Jose Ramirez        | 170           | 70           | sulfonamide |
| 2020000222     | Stefani Ricci       | 170           | 70           | peniccilin  |
+----------------+---------------------+---------------+--------------+-------------+
----

For example, run the `ENDS_WITH` function but with no specified `second_argument`:

[source,sql]
----
SELECT allergies, ENDS_WITH(allergies, '') FROM patients_data;
----

The result shows that `ENDS_WITH` returns true for all records (even the `null` one):

[source,sql]
----
+--------------+--------------+
| allergies    | ends_with    |
+--------------+--------------+
| null         | true         |
| null         | true         |
| penicillin   | true         |
| sulfonamide  | true         |
| peniccilin   | true         |
+--------------+--------------+
----
