= LOWER
:description: The LOWER() function returns a given string, an expression, or values in a column in all lowercase letters.
:page-topic-type: reference

The LOWER() function returns a given string, an expression, or values in a column in all lowercase letters. The syntax of the function is:

[source,sql]
----
LOWER(string)
----

It accepts input as a string and returns the text in the lowercase alphabet.

*Special Cases:* If there are characters in the input which are not of type string, they remain unaffected by the LOWER()function.

[NOTE]
====
Unicode is supported so that the ß is equivalent to the string ss.
====

== Examples

=== Basic `LOWER()` function

This basic query shows how to convert the given string in all lowercase alphabets:

[source,sql]
----
SELECT LOWER('PostGreSQL');
----

Output:

[source,sql]
----
+------------+
| lower      |
+------------+
| postgresql |
+------------+
----

=== `LOWER()` function using columns

This example shows how the `LOWER()` function works with columns. The *personal_details* table contains columns *id*, *first_name*, *last_name*, and *gender* of retail store employees.

[source,sql]
----
CREATE TABLE personal_details (
  id int,
  first_name text,
  last_name text,
  gender text
);
INSERT INTO personal_details
    (id, first_name, last_name, gender)
VALUES
    (1,'Mark','Wheeler','M'),
    (2,'Tom','Hanks','M'),
    (3,'Jane','Hopper','F'),
    (4,'Emily','Byers','F'),
    (5,'Lucas','Sinclair','M');
----

[source,sql]
----
SELECT * FROM personal_details;
----

This query shows the table:

[source,sql]
----
+-----+-------------+-------------+----------+
| id  | first_name  | last_name   | gender   |
+-----+-------------+-------------+----------+
| 1   | Mark        | Wheeler     | M        |
| 2   | Tom         | Hanks       | M        |
| 3   | Jane        | Hopper      | F        |
| 4   | Emily       | Byers       | F        |
| 5   | Lucas       | Sinclair    | M        |
+-----+-------------+-------------+----------+
----

Assume that the goal is to convert the first and last names of employees with *id* numbers 2, 4, and 5 to all lowercase letters. Use the following query:

[source,sql]
----
SELECT first_name,last_name,LOWER(first_name),LOWER(last_name)
FROM personal_details
where id in (2, 4, 5);
----

The output displays the first and last names of employees with the specified ids in lowercase letters:

[source,sql]
----
+------------+-------------+----------+----------+
| first_name | last_name   | lower    | lower    |
+------------+-------------+----------+----------+
| Tom        | Hanks       | tom      | hanks    |
| Emily      | Byers       | emily    | byers    |
| Lucas      | Sinclair    | lucas    | sinclair |
+------------+-------------+----------+----------+
----
