= STRPOS
:description: Use the STRPOS() to return the position from where the substring (the second argument) is matched with the string (the first argument).
:page-topic-type: reference

Use the `STRPOS()` function to return the position from where the substring (the second argument) is matched with the string (the first argument).

[source,sql]
----
STRPOS(string, substring)
----

The input and return must be of type `string`.

*Special cases:*

* Returns `NULL` if there are no input rows or `NULL` values.
* If the `substring` is not found in the string, then the `STRPOS()` function will return 0.

== Examples

=== Basic `STRPOS()` function

This example shows how to find the *ut* (substring) position in the *computer* (string):

[source,sql]
----
SELECT STRPOS('computer', 'ut') AS "Position of ut";
----

The result shows that *ut* is located at the fifth character of *computer*:

[source,sql]
----
+-----------------+
| Position of ut  |
+-----------------+
| 5               |
+-----------------+
----

=== STRPOS() function using column

The *listofwords* table stores word data:

[source,sql]
----
CREATE TABLE listofwords (
  words text
);
INSERT INTO listofwords
    (words)
VALUES
    ('corral'),
    ('traditionally'),
    ('real'),
    ('communal'),
    ('challenge'),
    ('fall'),
    ('wall'),
    ('gallop'),
    ('albatross');
----

[source,sql]
----
SELECT * FROM listofwords;
----

The preceding query shows the table:

[source,sql]
----
+----------------+
| words          |
+----------------+
| corral         |
| traditionally  |
| real           |
| communal       |
| challenge      |
| fall           |
| wall           |
| gallop         |
| albatross      |
+----------------+
----

This query returns the words and a position of a specific substring = ‘*al*’ using the `STRPOS()` function:

[source,sql]
----
SELECT words, STRPOS(words, 'al') AS "Position of al"
FROM listofwords;
----

The result displays the *al* position of different words:

[source,sql]
----
+----------------+------------------+
| words          | Position of al   |
+----------------+------------------+
| corral         | 5                |
| traditionally  | 10               |
| real           | 3                |
| communal       | 7                |
| challenge      | 3                |
| fall           | 2                |
| wall           | 2                |
| gallop         | 2                |
| albatross      | 1                |
+----------------+------------------+
----
