= UPPER
:description: The UPPER() function returns a given string, an expression, or values in a column in all uppercase letters.
:page-topic-type: reference

The `UPPER()` function returns a given string, an expression, or values in a column in all uppercase letters:

[source,sql]
----
UPPER(string)
----

It accepts input as a string and returns text in uppercase letters.

*Special Case:*

* If characters in the input are not of type string, they remain unaffected by the `UPPER()` function.
* Unicode is supported for the `UPPER()` function.

== Examples

=== Basic `UPPER()` function

This basic query converts the given string to all uppercase letters:

[source,sql]
----
SELECT UPPER('PostGreSQL');
----

Output:

[source,sql]
----
+-------------+
| upper       |
+-------------+
| POSTGRESQL  |
+-------------+
----

=== UPPER() function using columns and CONCAT() function

This example shows how the `UPPER()` function works with columns. A table named *personal_details* contains employee's *id*, *first_name*, *last_name*, and *gender* of a retail store:

[source,sql]
----
CREATE TABLE personal_details (
  id int,
  first_name text,
  last_name text,
  gender text
);
INSERT INTO personal_details
    (id, first_name, last_name, gender)
VALUES
    (1,'Mark','Wheeler','M'),
    (2,'Tom','Hanks','M'),
    (3,'Jane','Hopper','F'),
    (4,'Emily','Byers','F'),
    (5,'Lucas','Sinclair','M');
----

[source,sql]
----
SELECT * FROM personal_details;
----

This query returns:

[source,sql]
----
+-----+-------------+-------------+----------+
| id  | first_name  | last_name   | gender   |
+-----+-------------+-------------+----------+
| 1   | Mark        | Wheeler     | M        |
| 2   | Tom         | Hanks       | M        |
| 3   | Jane        | Hopper      | F        |
| 4   | Emily       | Byers       | F        |
| 5   | Lucas       | Sinclair    | M        |
+-----+-------------+-------------+----------+
----

Assume that:

. The goal is to convert employees’ first and last names with *id* numbers 1, 3, and 5 to all uppercase letters.
. Then, combine them using the `CONCAT()` function into one *full_name* column in uppercase.
+
Use this query:
+
[source,sql]
----
SELECT CONCAT (UPPER(first_name),' ', UPPER(last_name))
as full_name
FROM personal_details
where id in (1, 3, 5);
----
+
The output displays the first and last names of employees with the specified ids in uppercase letters:
+
[source,sql]
----
+---------------------+
| full_name           |
+---------------------+
| MARK WHEELER        |
| JANE HOPPER         |
| LUCAS SINCLAIR      |
+---------------------+
----
