= Java (JDBC)
:description: Java Database Connectivity (JDBC) is a Java API for connecting to and querying Redpanda SQL from Java applications.
:page-topic-type: how-to

https://docs.oracle.com/javase/8/docs/technotes/guides/jdbc/[Java Database Connectivity (JDBC)^] is the standard API for connecting Java and Kotlin applications to a database. Because Redpanda SQL implements the PostgreSQL wire protocol, you can use any PostgreSQL JDBC driver to connect from Java or Kotlin. This page describes how to use the Kotlin JDBC client with Redpanda SQL and lists unsupported functions and structures.

== Establishing connection

[source,kotlin]
----
    /**
     * @brief Establishes connection to a database at a given address and port.
     * @param address Address at which database is located (Can be in URL, IPv4 or IPv6 format).
     * @param port Port at which database is located (in [0, 65535] range).
     * @param databaseName Name of the database to connect to.
     * @param user (optional) Name of a user to connect as.
     * @param password (optional) Password of the given user.
     * @return Result containing a Connection object if connection was established successfully, otherwise Result(Failure) with an error message.
     */
    fun connect(
        address: String,
        port: Int,
        databaseName: String,
        user: String? = null,
        password: String? = null
    ): Result<Connection> {
        if (port !in 0..65535) {
            return Result.failure(IllegalArgumentException("Port must be in 0 - 65535 range."))
        }
        try {
            return Result.success(DriverManager.getConnection("jdbc:postgresql://$address:$port/$databaseName", user, password))
        } catch (e: SQLException) {
            return Result.failure(SQLException("Failed to establish connection to a database, because: $e"))
        } catch (_: SQLTimeoutException) {
            return Result.failure(SQLTimeoutException("Failed to establish connection to a database. Request timed out."))
        }
    }
----

[NOTE]
====
Support for SSL/TLS is not mandated in the JDBC specification. So you cannot expect it in every driver.
====

== Example usage

This example shows basic query execution, once the connection has been established:

[source,kotlin]
----
val statement: Statement = connection.createStatement()
statement.queryTimeout = QUERY_TIMEOUT
val query: String = "SELECT $columnName FROM $table"
try {
    // Execute the query and...
    val result: ResultSet = statement.executeQuery(query). also {
        // ... print the results.
        while (it.next()) {
            println(it.getString(1))
        }
    }
} catch (e: SQLException) {
    System.err.println("Failed to execute the following query: $query, error: $e")
}
----

== Unsupported functions and structures

The following functions and potentially related structures are not currently supported when working with Redpanda SQL and Kotlin JDBC:

* `JDBC.Connection`, https://docs.oracle.com/javase/8/docs/api/java/sql/Connection.html#createArrayOf-java.lang.String-java.lang.Object:A-[createArrayOf^]
* `JDBC.Connection`, https://docs.oracle.com/javase/8/docs/api/java/sql/Connection.html#getTransactionIsolation--[getTransactionIsolation^]
* `JDBC.Connection`, https://docs.oracle.com/javase/8/docs/api/java/sql/Connection.html#prepareStatement-java.lang.String-int:A-[prepareStatement with intArray (JDBC does not support)^]
* `JDBC.Connection`, https://docs.oracle.com/javase/8/docs/api/java/sql/Connection.html#setSavepoint--[setSavepoint^]
* `JDBC.Connection`, https://docs.oracle.com/javase/8/docs/api/java/sql/Connection.html#setTransactionIsolation-int-[setTransactionIsolation^]
* `JDBC.ResultSet`, https://docs.oracle.com/javase/8/docs/api/java/sql/ResultSet.html#refreshRow--[refreshRow^]
* `JDBC.ResultSet`, https://docs.oracle.com/javase/8/docs/api/java/sql/ResultSet.html#moveToCurrentRow--[moveToCurrentRow^]
* `JDBC.Statement`, https://docs.oracle.com/javase/8/docs/api/java/sql/Statement.html#RETURN_GENERATED_KEYS[RETURN_GENERATED_KEYS^]
* `JDBC.Statement`, https://docs.oracle.com/javase/8/docs/api/java/sql/Statement.html#executeUpdate-java.lang.String-int-[executeUpdate with autoGeneratedKeys^]
* `JDBC.Statement`, https://docs.oracle.com/javase/8/docs/api/java/sql/Statement.html#execute-java.lang.String-int:A-[execute with intArray^]
* `JDBC.Statement`, https://docs.oracle.com/javase/8/docs/api/java/sql/Statement.html#cancel--[cancel^]
* `JDBC.PreparedStatement`, https://docs.oracle.com/javase/8/docs/api/java/sql/PreparedStatement.html#setDate-int-java.sql.Date-[setDate^]
* `JDBC.PreparedStatement`, https://docs.oracle.com/javase/8/docs/api/java/sql/PreparedStatement.html#setObject-int-java.lang.Object-[setObject^]
* `JDBC.PreparedStatement`, https://docs.oracle.com/javase/8/docs/api/java/sql/PreparedStatement.html#setString-int-java.lang.String-[setString(1, PGInterval("1 day").toString())^]
