= Use AWS Pay As You Go
:description: Subscribe to Redpanda in AWS Marketplace with pay-as-you-go billing, and cancel anytime.

Subscribe to Redpanda Cloud through AWS Marketplace to quickly provision Redpanda Dedicated clusters. With a usage-based pay as you go subscription, you only pay for what you use and can cancel anytime. 

[IMPORTANT]
====
When you sign up for Redpanda Cloud through AWS Marketplace, you can only create clusters on AWS. 
====

== Sign up in AWS Marketplace

. On https://aws.amazon.com/marketplace[AWS Marketplace^], search for "redpanda". 

. Select *Redpanda Cloud - The proven Apache Kafka alternative (Pay as You Go)*. 

. On the *Redpanda Cloud - Pay as You Go** overview page, click *View purchase options*.

. Sign in to AWS. 
+
[NOTE]
====
If you don't have a billing account associated with your project, you're prompted to enable billing to link the subscription with a billing account.
====

. Review the purchase details, and click **Subscribe**. You're taken to the Redpanda sign-up page.

. On the Redpanda sign-up page: 
* For **Email**, enter your email address to register with Redpanda.
* For **Organization name**, enter a name for your new organization connected through AWS Marketplace. Redpanda organizations contain all resources, including clusters and networks. 
* Click **Sign up and create organization**.
+
You will receive an email sent to the address you entered.

. In the email, click **Verify email address**. 
+
This completes the registration and associates the email with a Redpanda account. 

. On the **Accept your invitation to sign up** page, click **Sign up** or **Log in**. 
+
You can now create resource groups, clusters, and networks in your organization.

== Next steps

* xref:get-started:cluster-types/dedicated/create-dedicated-cloud-cluster-aws.adoc#create-a-dedicated-cluster[Create a Dedicated cluster]