= Use AWS Pay As You Go
:description: Subscribe to Redpanda in AWS Marketplace with pay-as-you-go billing, and cancel anytime.

Subscribe to Redpanda Cloud through AWS Marketplace to quickly provision Redpanda Serverless and Dedicated clusters. With a usage-based pay as you go subscription, you only pay for what you use and can cancel anytime. 

[IMPORTANT]
====
When you sign up for Redpanda Cloud through AWS Marketplace, you can only create clusters on AWS. 
====

== Sign up in AWS Marketplace

. In the AWS Marketplace, select https://aws.amazon.com/marketplace/pp/prodview-ecbu7wwsfh644?applicationId=AWSMPContessa&ref_=beagle&sr=0-3[**Redpanda Cloud - The proven Apache Kafka alternative (Pay as You Go)**^]. 

. On the **Redpanda Cloud - Pay as You Go** overview page, click **View purchase options**, then click **Subscribe**. 

+
[NOTE]
====
If you don't have a billing account associated with your project, you're prompted to link the subscription with a billing account.
====

. On the **Subscribe to Redpanda Cloud** page, click **Set up your account**. You're taken to the Redpanda sign-up page.

. On the Redpanda sign-up page: 
* For **Email**, enter your email address to register with Redpanda.
* For **Organization name**, enter a name for your new organization connected through AWS Marketplace. 
+ 
TIP: This process creates a new organization, even for existing Redpanda customers. Organizations contain all resources, including clusters and networks.
* Click **Sign up and create organization**.
+
You will receive an email sent to the address you entered.

. In the email, click **Verify email address**. 
+
This associates the email with a Redpanda account. 

. On the **Accept your invitation to sign up** page, enter the credentials you want to use for Redpanda Cloud. 
+
You can now create resource groups, networks, and clusters in your organization.

== Next steps

* xref:get-started:cluster-types/dedicated/create-dedicated-cloud-cluster-aws.adoc#create-a-dedicated-cluster[Create a Dedicated cluster]