= Use Azure Commitments
:description: Subscribe to Redpanda in Azure Marketplace with committed use.

You can subscribe to Redpanda Cloud through Azure Marketplace and use your existing marketplace billing and credits to quickly provision Dedicated clusters. View your bills and manage your subscription directly in the marketplace.

With a usage-based billing commitment, you sign up for a monthly or an annual minimum spend amount. Commitments are minimums: 

- If you use less than your committed amount, you still pay the minimum. Any unused amount on a monthly commitment rolls over to the next month until the end of your term. 
- If you use more than your committed amount, you can continue using Redpanda Cloud without interruption. You're charged for any additional usage until the end of your term.

[IMPORTANT]
====
When you subscribe to Redpanda Cloud through Azure Marketplace, you can only create clusters on Azure. 
====

== Sign up in Azure Marketplace

. Contact https://redpanda.com/contact[Redpanda sales^] to request a private offer with possible discounts. 
+
You will receive a private offer on Azure Marketplace. This offer is associated with an Azure user account that has access to the Azure subscription used for billing. 

. In Azure Marketplace, review the policy and required terms, and click *Accept*.
+
You are taken to the Redpanda sign-up page.

. On the Redpanda sign-up page: 
* For **Email**, enter your email address to register with Redpanda.
* For **Organization name**, enter a name for your new organization connected through Azure Marketplace. Redpanda organizations contain all resources, including clusters and networks. 
* Click **Sign up and create organization**.
+
You will receive an email sent to the address you entered.

. In the email, click **Verify email address**. 
+
This completes the registration and associates the email with a Redpanda account. 

. On the **Accept your invitation to sign up** page, click **Sign up** or **Log in**. 
+
You can now create resource groups, clusters, and networks in your organization.

== Next steps

* xref:get-started:cluster-types/dedicated/create-dedicated-cloud-cluster.adoc[Create a Dedicated cluster]