= Usage Metrics
:description: Learn about the metrics Redpanda uses to measure consumption in Redpanda Cloud.
:page-aliases: deploy:deployment-option/cloud/manage-billing/billing.adoc

Redpanda Cloud uses various metrics to measure the consumption of resources. 

* All pricing is set in US dollars (USD). 
* All billing computations are conducted in Coordinated Universal Time (UTC). Billing accrues at hourly intervals. Any usage that is less than an hour is billed for the full hour. 

NOTE: Pricing information is available on https://redpanda.com/redpanda-cloud/serverless[redpanda.com]. For questions about billing, contact billing@redpanda.com.

== Serverless metrics

Pricing for Serverless clusters depends on the data in, data out, data stored, partitions (virtual streams), and for Serverless Pro clusters only, the time the instance is up.

|=== 
| Metric | Description 

| Uptime | Tracks the number of hours the instance is running. 

Note: Serverless Pro only. There is no base cost for Serverless Standard.

| Ingress | Tracks the data written into Redpanda (in GB).

The cost varies based on the region you select for your cluster. 

All Kafka protocol requests (_except_ message headers) are counted as ingress as soon as they are read by Redpanda's proxy process. 
| Egress | Tracks the data read out of Redpanda (in GB).

All Kafka protocol responses generated by the cluster (_except_ message headers) are counted as egress as soon as the cluster processes the request, even if the client drops the connection before they are delivered.
| Storage | Tracks the data in object storage per hour (in GB). 
| Partitions | Tracks the number of partitions used per hour.

|===

See also: xref:get-started:cluster-types/serverless.adoc#serverless-standard-usage-limits[Serverless Standard limits] and xref:get-started:cluster-types/serverless-pro.adoc#serverless-pro-usage-limits[Serverless Pro limits]

== Dedicated metrics

Pricing for Dedicated clusters depends on the time the instance is up, the data in, data out, and data stored.

|=== 
| Metric | Description 

| Uptime | Tracks the number of hours the instance is running. 

The cost varies based on the xref:reference:tiers/byoc-tiers.adoc[region and tier] you select for your cluster.   
| Ingress | Tracks the data written into Redpanda (in GB). 

The cost varies based on the region you select for your cluster. 

All Kafka protocol requests (_including_ message headers) are counted as ingress as soon as they are read by Redpanda's proxy process. 
| Egress | Tracks the data read out of Redpanda (in GB).

All Kafka protocol responses generated by the cluster (_including_ message headers) are counted as egress as soon as the cluster processes the request, even if the client drops the connection before they are delivered. 

The cost varies based on the number of availability zones (AZ) you select for your cluster. 
| Storage | Tracks the data in object storage per hour (in GB). 

Replication to object storage is implemented with glossterm:Tiered Storage[]. All topics have a fixed replication factor of 3, but Redpanda counts each byte only once.

|=== 

== Redpanda Connect pipeline metrics (Dedicated and Serverless)

Pricing per pipeline depends on the number of compute units you allocate and the cost of a compute unit, which varies based the cloud provider and region of the cluster on which your pipeline runs.

|=== 
| Metric | Description

| Compute | Tracks the server resources (CPU and memory) a pipeline uses while it is running in compute units per hour.

|=== 


== Next steps

* xref:billing:gcp-commit.adoc[]
* xref:billing:aws-commit.adoc[]
* xref:billing:azure-commit.adoc[]