= Redpanda Cloud Usage Metrics
:description: Learn about the metrics Redpanda uses to measure consumption in Redpanda Cloud.
:page-aliases: deploy:deployment-option/cloud/manage-billing/billing.adoc

Redpanda Cloud uses various metrics to measure the consumption of resources. 

* All pricing is set in US dollars (USD). 
* All billing computations are conducted in Coordinated Universal Time (UTC). Billing accrues at hourly intervals. Any usage that is less than an hour is billed for the full hour. 
* You can view detailed billing activity for each cluster and edit payment methods on the *Billing* page.

NOTE: Pricing information is available on https://www.redpanda.com/price-estimator[redpanda.com^]. For questions about billing, contact billing@redpanda.com.

== Usage metrics by cluster type

[tabs]
======
Serverless::
+
--
Pricing for Serverless clusters depends on the data in, data out, data stored, partitions (virtual streams), and the time the instance is up. The cost for each Serverless metric varies based on the region you select for your cluster.


|=== 
| Metric | Description  

| Uptime | Tracks the number of hours the instance is running. +

*NOTE*: Uptime is not charged if partitions = 0 and storage = 0. This condition is met when all topics are deleted.

| Ingress | Tracks the data written into Redpanda (in GB).

All Kafka protocol requests (_except_ message headers) are counted as ingress as soon as they are read by Redpanda's proxy process. 

| Egress | Tracks the data read out of Redpanda (in GB).

All Kafka protocol responses generated by the cluster (_except_ message headers) are counted as egress as soon as the cluster processes the request, even if the client drops the connection before they are delivered. 

| Partitions | Tracks the number of partitions used per hour.

| Storage | Tracks the data in object storage per hour (in GB). 

|===

See also: xref:get-started:cluster-types/serverless.adoc#serverless-usage-limits[Serverless limits]
--

Dedicated::
+
--
Pricing for Dedicated clusters depends on the time the instance is up, the data in, data out, and data stored.


|=== 
| Metric | Description 

| Uptime | Tracks the number of hours the instance is running. 

The cost varies based on the xref:reference:tiers/dedicated-tiers.adoc[region and tier] you select for your cluster.   
| Ingress | Tracks the data written into Redpanda (in GB). 

All Kafka protocol requests (_including_ message headers) are counted as ingress as soon as they are read by Redpanda's proxy process.

The cost varies based on the region you select for your cluster. 
| Egress | Tracks the data read out of Redpanda (in GB).

All Kafka protocol responses generated by the cluster (_including_ message headers) are counted as egress as soon as the cluster processes the request, even if the client drops the connection before they are delivered. 

The cost varies based on the number of availability zones (AZ) you select for your cluster. 
| Storage | Tracks the data in object storage per hour (in GB). 

Replication to object storage is implemented with glossterm:Tiered Storage[]. All topics have a fixed replication factor of 3, but Redpanda counts each byte only once.

|===
--

BYOC::
+
--
Pricing for BYOC clusters depends on compute, data in, data out, and data stored. The more resources you allocate to your cluster, the more the rate is discounted.



|=== 
| Metric | Description 

| Compute | Tracks the amount of compute per hour (in vCPU and memory). 

Compute is measured in Redpanda units (RPUs), where: 

1 RPU = 2 vCPU + 8 GB RAM

The cost varies based on the xref:reference:tiers/byoc-tiers.adoc[region and tier] you select for your cluster.   
| Ingress | Tracks the data written into Redpanda (in GB). 

All Kafka protocol requests (_including_ message headers) are counted as ingress as soon as they are read by Redpanda's proxy process.

| Ingress to Iceberg topics | Tracks the data written to Iceberg tables per hour (in GB).

NOTE: This metric applies only if you write to Iceberg topics.

| Egress | Tracks the data read out of Redpanda (in GB).

All Kafka protocol responses generated by the cluster (_including_ message headers) are counted as egress as soon as the cluster processes the request, even if the client drops the connection before they are delivered. 

The cost varies based on the number of availability zones (AZ) you select for your cluster. 
| Storage | Tracks the data in object storage per hour (in GB). 

Replication to object storage is implemented with glossterm:Tiered Storage[]. All topics have a fixed replication factor of 3, but Redpanda counts each byte only once.


|=== 
--
======


== Redpanda Connect pipeline metrics

Pricing per pipeline depends on:

- The number of xref:develop:connect/configuration/resource-management.adoc[compute units] you allocate.
- The cost of a compute unit, which varies based on the cloud provider and region you select for your cluster.

|=== 
| Metric | Description
| Compute | Tracks the server resources (CPU and memory) a pipeline uses in compute units per hour.
|=== 

== Next steps

* xref:billing:aws-commit.adoc[]
* xref:billing:azure-commit.adoc[]
* xref:billing:gcp-commit.adoc[]
* xref:get-started:cluster-types/serverless.adoc#create-a-serverless-cluster[Create a Serverless cluster]
* xref:get-started:cluster-types/byoc/index.adoc[Create a BYOC cluster]   
* xref:get-started:cluster-types/dedicated/create-dedicated-cloud-cluster-aws.adoc#create-a-dedicated-cluster[Create a Dedicated cluster]