= Billing and Support 
:description: Learn about the metrics Redpanda uses to measure consumption in Redpanda Cloud.
:page-aliases: deploy:deployment-option/cloud/manage-billing/billing.adoc

Redpanda Cloud uses various metrics to measure the consumption of resources. 

* All pricing is set in US dollars (USD). 
* All billing computations are conducted in Coordinated Universal Time (UTC). Billing accrues at hourly intervals. Any usage that is less than an hour is billed for the full hour. 
* You can view detailed billing activity for each cluster and edit payment methods on the *Billing* page.

NOTE: Pricing information is available on https://www.redpanda.com/price-estimator[redpanda.com^]. For questions about billing, contact billing@redpanda.com.

== Usage-based billing metrics

[tabs]
======
Serverless::
+
--
Pricing for Serverless clusters depends on the data in, data out, data stored, partitions (virtual streams), and the time the instance is up. The cost for each Serverless metric varies based on the region you select for your cluster.

[cols="1,3",options="header"]
|=== 
| Metric | Description  

| Uptime | Tracks the number of hours the instance is running. +

*NOTE*: Uptime is not charged if partitions = 0 and storage = 0. This condition is met when all topics are deleted.

| Ingress | Tracks the data written into Redpanda (in GB).

All Kafka protocol requests (_except_ message headers) are counted as ingress as soon as they are read by Redpanda's proxy process. 

| Egress | Tracks the data read out of Redpanda (in GB).

All Kafka protocol responses generated by the cluster (_except_ message headers) are counted as egress as soon as the cluster processes the request, even if the client drops the connection before they are delivered. 

| Partitions | Tracks the number of partitions used per hour.

| Storage | Tracks the data in object storage per hour (in GB). 

|===

See also: xref:get-started:cluster-types/serverless.adoc#serverless-usage-limits[Serverless limits]
--

Dedicated::
+
--
Pricing for Dedicated clusters depends on the time the instance is up, the data in, data out, and data stored.

[cols="1,3",options="header"]
|=== 
| Metric | Description 

| Uptime | Tracks the number of hours the instance is running. 

The cost varies based on the xref:reference:tiers/dedicated-tiers.adoc[region and tier] you select for your cluster.   
| Ingress | Tracks the data written into Redpanda (in GB). 

All Kafka protocol requests (_including_ message headers) are counted as ingress as soon as they are read by Redpanda's proxy process.

The cost varies based on the region you select for your cluster. 
| Egress | Tracks the data read out of Redpanda (in GB).

All Kafka protocol responses generated by the cluster (_including_ message headers) are counted as egress as soon as the cluster processes the request, even if the client drops the connection before they are delivered. 

The cost varies based on the number of availability zones (AZ) you select for your cluster. 
| Storage | Tracks the usage of object storage on an hourly basis during the billing period (in GB-hours).

Replication to object storage is implemented with glossterm:Tiered Storage[]. All topics have a fixed replication factor of 3, but Redpanda counts each byte only once.

|===
--

BYOC::
+
--
Pricing for BYOC clusters depends on compute, data in, data out, and data stored. The rate decreases as usage increases.


[cols="1,3",options="header"]
|=== 
| Metric | Description 

| Compute | Tracks the server resources (vCPU and memory) a cluster uses on an hourly basis in Redpanda units (RPUs). Where: 

1 RPU = 2 vCPU + 8 GB memory

| Ingress | Tracks the data written into Redpanda (in GB). 

All Kafka protocol requests (_including_ message headers) are counted as ingress as soon as they are read by Redpanda's proxy process.

| Ingress to Iceberg topics | Tracks the data written to Iceberg tables per hour (in GB).

NOTE: This metric applies only if you write to Iceberg topics. This charge is in addition to the standard ingress charge.

| Egress | Tracks the data read out of Redpanda (in GB).

All Kafka protocol responses generated by the cluster (_including_ message headers) are counted as egress as soon as the cluster processes the request, even if the client drops the connection before they are delivered. 

The cost varies based on the number of availability zones (AZ) you select for your cluster. 
| Storage | Tracks the usage of object storage on an hourly basis during the billing period (in GB-hours).

Replication to object storage is implemented with glossterm:Tiered Storage[]. All topics have a fixed replication factor of 3, but Redpanda counts each byte only once.


|=== 
--
======


== Redpanda Connect billing metrics

Pricing per pipeline depends on:

- The number of xref:develop:connect/configuration/resource-management.adoc[compute units] you allocate.
- The cost of a compute unit, which can vary based on the cloud provider and region you select for your cluster.

[cols="1,3",options="header"]
|===
| Metric | Description

| Compute | Tracks the server resources (vCPU and memory) a pipeline uses in compute units per hour.
|=== 

== Support plans

All organizations in Redpanda require one of the following support plans:

[cols="1,3",options="header"]
|===
| Support plan | Features

| Basic 
a| * Designed for non-production environments 
* Provides minimal support: priority 3 tickets within 8 business hours response time and priority 4 tickets with no target response time
* Support availability is 8:00 AM to 5:00 PM Pacific Time, Monday through Friday, excluding federal US holidays

| Enterprise 
a| * Designed for production environments needing continuous availability
* P1/P2 tickets may be submitted  
* Support availability is 24/7, including holidays

| Premium 
a| * Designed for mission-critical workloads
* 30-minute response times for production outages
* Includes a named Customer Success Manager to support planning and coordination, and 10 hours per month of consulting from a Solutions Architect
* Required for deployments with BYOVPC/BYOVnet clusters

|===


== Next steps

* xref:billing:aws-commit.adoc[]
* xref:billing:azure-commit.adoc[]
* xref:billing:gcp-commit.adoc[]
* xref:get-started:cluster-types/serverless.adoc#create-a-serverless-cluster[Create a Serverless cluster]
* xref:get-started:cluster-types/dedicated/create-dedicated-cloud-cluster-aws.adoc#create-a-dedicated-cluster[Create a Dedicated cluster]
* xref:get-started:cluster-types/byoc/index.adoc[Create a BYOC cluster]