= Use GCP Pay As You Go
:description: Subscribe to Redpanda in Google Cloud Marketplace with pay-as-you-go billing, and cancel anytime.

Subscribe to Redpanda Cloud through Google Cloud Marketplace to quickly provision Serverless and Dedicated clusters. With a usage-based pay-as-you-go subscription, you only pay for what you use and can cancel anytime.

[IMPORTANT]
====
When you sign up for Redpanda Cloud through Google Cloud Marketplace, you can only create clusters on GCP.
====

== Sign up in Google Cloud Marketplace

. In the Google Cloud Marketplace, select **Redpanda Cloud - The proven Apache Kafka alternative (Pay as You Go)**.

. On the **Redpanda Cloud - Pay as You Go** overview page, click **Subscribe**.

+
[NOTE]
====
If you don't have a billing account associated with your project, you're prompted to link the subscription with a billing account.
====

. On the **Subscribe to Redpanda Cloud** page, click **Set up your account**. You're taken to the Redpanda sign-up page.

. On the Redpanda sign-up page:
* For **Email**, enter your email address to register with Redpanda.
* For **Organization name**, enter a name for your new organization connected through Google Cloud Marketplace.
+
TIP: This process creates a new organization, even for existing Redpanda customers. Organizations contain all resources, including clusters and networks.
* Click **Sign up and create organization**.
+
You will receive an email sent to the address you entered.

. In the email, click **Verify email address**.
+
This associates the email with a Redpanda account.

. On the **Accept your invitation to sign up** page, enter the credentials you want to use for Redpanda Cloud.
+
You can now create resource groups, networks, and clusters in your organization.

== Next steps

* xref:get-started:cluster-types/serverless.adoc#create-a-serverless-cluster[Create a Serverless cluster]
* xref:get-started:cluster-types/create-dedicated-cloud-cluster.adoc[Create a Dedicated cluster]
