= Redpanda Connect Usage Metrics
:description: Learn about the metrics Redpanda uses to measure Redpanda Connect consumption in Redpanda Cloud.

Redpanda Cloud uses various metrics to measure the consumption of resources. 

* All pricing is set in US dollars (USD). 
* All billing computations are conducted in Coordinated Universal Time (UTC). Billing accrues at hourly intervals. Any usage that is less than an hour is billed for the full hour. 

NOTE: Pricing information is available on https://www.redpanda.com/price-estimator[redpanda.com^]. For questions about billing, contact billing@redpanda.com.

== Redpanda Connect pipeline metrics 

Pricing per pipeline depends on:

- The number of xref:develop:connect/configuration/resource-management.adoc[compute units] you allocate.
- The cost of a compute unit, which varies based on the cloud provider and region you select for your cluster.

|===
| Metric | Description

| Compute | Tracks the server resources (CPU and memory) a pipeline uses in compute units per hour.

|=== 
