= JSON_ARRAY_EXTRACT
:description: The JSON_ARRAY_EXTRACT() function returns the JSON array as a set of JSON values.

=== *Overview*

The `JSON++_++ARRAY++_++EXTRACT()` function returns the JSON array as a set of JSON values.

=== *Syntax*

The `JSON++_++ARRAY++_++EXTRACT()` has the basic syntax as seen below.

[source,sql]
----
JSON_ARRAY_EXTRACT('json_array'::JSON,id);
----

`JSON++_++ARRAY++_++EXTRACT()` requires the following parameters:

* `json++_++array`: the array to be extracted.
* `::JSON`: argument indicating that the query is of type JSON.
* `id`: ID of the element that we want to extract. It is read in an array format that starts with 0.

==== Another Option

`JSON++_++ARRAY++_++EXTRACT` can also be achieved with the `-++>++` operator, as shown in the syntax below:

[source,sql]
----
SELECT 'from_json'::JSON -> path;
----

* `from++_++json`: the JSON value from which to extract.
* `::JSON`: a symbol that casts the string literal to a JSON type.
* `path`: key of the field that we want to extract.

=== Examples

==== Case ++#++1: Basic JSON++_++ARRAY++_++EXTRACT() function

[arabic]
. In the below example, we will extract a JSON array as a JSON set.

[source,sql]
----
SELECT JSON_ARRAY_EXTRACT('["Bougenvile", 2, 12, "Lily"]'::JSON,3);
----

*or*

[source,sql]
----
SELECT ('["Bougenvile", 2, 12, "Lily"]'::JSON -> 3);
----

[arabic, start=2]
. The extracted array will look like the following.

[source,sql]
----
+------------+
| f          |
+------------+
| "Lily"     |
+------------+
----

==== Case ++#++2: Extract element of JSON array as text

[arabic]
. In this case, we will extract the element of the JSON array as text with the `-++>>++` operator.

[source,sql]
----
SELECT ('["Bougenvile", 2, 12, "Lily"]'::JSON ->> 1);
----

[arabic, start=2]
. You will get the final output as follows:

[source,sql]
----
+------------+
| f          |
+------------+
| 2.000000   |
+------------+
----
