= ABS
:description: The ABS() function returns an absolute number, i.e., the positive value of a number.
:page-topic-type: reference

The `ABS()` function returns an absolute number, i.e., the positive value of a number. The data type of the returned value will depend on the data type of the value passed to the `ABS()` function.

== Syntax

The syntax for the `ABS()`function is as follows:

[source,sql]
----
ABS(x)
----

The `ABS()` function requires one argument:

* `x`: An expression that evaluates to a number.

[NOTE]
====
The *ABS()* function will return the negation of the negative numbers.
====

== Examples

=== Absolute value of a negative number

The following example demonstrates how the `ABS()` function can be used to obtain the absolute value of a negative number:

[source,sql]
----
SELECT ABS(-10.25);
----

This returns an absolute value of the passed argument:

[source,sql]
----
+--------+
| f      |
+--------+
| 10.25  |
+--------+
----

=== ABS() function with an expression

The following example demonstrates how the `ABS()` function can be used with an expression to obtain the absolute value of the result:

[source,sql]
----
SELECT ABS( 100 - 250);
----

The result of this statement is *-150*. However, the output is *150*, as 150 is the positive version of -150.

[source,sql]
----
+------+
| f    |
+------+
| 150  |
+------+
----

=== Use the ABS() function with a table

The following example demonstrates how the `ABS()` function can be used with a table to obtain the absolute values of all numbers in a specific column:

. First, create a table named absTable containing an *_initialValue_* column with some positive and negative values:
+
[source,sql]
----
CREATE TABLE absTable(initialValue float);

INSERT INTO absTable(initialValue)
VALUES
(550),
(-210),
(72.12),
(-87.93),
(-0.0);
----

. Next, use the following query to find the absolute value of all numbers:
+
[source,sql]
----
SELECT initialValue, ABS(initialValue) AS absoluteValue
FROM absTable;
----

. This query retrieves all values in the *"`initialValue`"* column and their absolute values in the *"`absoluteValue`"* column. The output will look something like this:
+
[source,sql]
----
+---------------+----------------+
| initialValue  | absoluteValue  |
+---------------+----------------+
| 550           | 550            |
| -210          | 210            |
| 72.12         | 72.12          |
| -87.93        | 87.93          |
| -0            | 0              |
+---------------+----------------+
----
