= RANDOM
:description: The RANDOM() function in Redpanda SQL generates a random number within a defined range.
:page-topic-type: reference

The `RANDOM()` function in Redpanda SQL generates a random number within a defined range. By default, the range is between 0 (inclusive) and 1 (exclusive), resulting in a value greater than or equal to 0 and less than 1.

== Syntax

The syntax for generating a random integer or floating-point number using the `RANDOM()` function is:

[source,sql]
----
RANDOM()
----

[NOTE]
====
There are no parameters or arguments for the `RANDOM()` function.
====

== Examples

=== Generate a random number

The RANDOM() function generates a random number greater than or equal to zero but less than one by default. Use this syntax to retrieve a random number:

[source,sql]
----
SELECT RANDOM();
----

The result is a random number greater than 0 and less than 1. However, it will never return the maximum value of 1.

[source,sql]
----
+-----------------------+
| f                     |
+-----------------------+
| 0.9122627193276355    |
+-----------------------+
----

=== Generate a random decimal number within a range

To generate a random decimal number between two values:

[source,sql]
----
SELECT RANDOM()*(b-a)+a;
----

Where:

* *"`a`"* represents the lower bound of the range.
* *"`b`"* represents the upper bound of the range.

The return value will be a random floating-point number greater than or equal to a and less than b.

*Example*

To generate a random decimal number greater than or equal to 10 and less than 25:

[source,sql]
----
SELECT RANDOM()*(25 - 10)+10;
----

This example shows how to retrieve a random number:

[source,sql]
----
+-----------------------+
| f                     |
+-----------------------+
| 18.156098711616043    |
+-----------------------+
----

[WARNING]
====
It is important to note that the function will never return the maximum value of b.
====
