= DESCRIBE
:description: The DESCRIBE statement is used to show columns within a table as well as tables within a database.
:page-topic-type: reference

The `DESCRIBE` statement is used to show columns within a table as well as tables within a database.

== Syntax

[source,sql]
----
DESCRIBE DATABASE;
DESCRIBE TABLE table_name;
DESCRIBE TABLE catalog_name=>table_name;
DESCRIBE REDPANDA CATALOG catalog_name;
----

* `table_name`: Name of the table to describe.
* `catalog_name=>table_name`: Describes a table that is mapped to a Redpanda topic through a catalog.
* `catalog_name`: Name of a Redpanda catalog. Lists the tables and topic mappings in that catalog.

[NOTE]
====
This statement is available to all users with the `USAGE` privilege on the schema where the table is located.
====

== Examples

To get a better understanding of the `DESCRIBE` statement, take a look at the following examples:

=== Describe a table

This example shows the columns of the *part* table. Run the following query:

[source,sql]
----
DESCRIBE TABLE part;
----

As a result, you get a list of column names, column types, and nullable options from the *part* table:

[source,sql]
----
+----------------+------------+-------------+-------+----------+
| database_name  | table_name |    name     | type  | nullable |
+----------------+------------+-------------+-------+----------+
| public         | part       | p_partkey   | INT   | f        |
| public         | part       | p_name      | TEXT  | f        |
| public         | part       | p_mfgr      | TEXT  | f        |
| public         | part       | p_category  | TEXT  | f        |
| public         | part       | p_brand     | TEXT  | f        |
| public         | part       | p_color     | TEXT  | f        |
| public         | part       | p_type      | TEXT  | f        |
| public         | part       | p_size      | INT   | f        |
| public         | part       | p_container | TEXT  | f        |
+----------------+------------+-------------+-------+----------+
----

[TIP]
====
The example above shows that the tables reside in the `public` schema (the default schema in Redpanda SQL). You can also display tables from other schemas. See xref:reference:sql/schema.adoc[Schema] for details.
====

=== Describe a catalog table

To view column details for a table mapped through a Redpanda catalog:

[source,sql]
----
DESCRIBE TABLE my_catalog=>transactions;
----

[source,sql]
----
+----------------+--------------+-------------+-------+----------+
| database_name  | table_name   |    name     | type  | nullable |
+----------------+--------------+-------------+-------+----------+
| my_catalog     | transactions | tx_id       | INT   | f        |
| my_catalog     | transactions | amount      | REAL  | f        |
| my_catalog     | transactions | created_at  | TEXT  | f        |
+----------------+--------------+-------------+-------+----------+
----

=== Describe a Redpanda catalog

To list the tables and topic mappings in a Redpanda catalog:

[source,sql]
----
DESCRIBE REDPANDA CATALOG my_catalog;
----

[source,sql]
----
+----------------+--------------+
| table_name     | topic_name   |
+----------------+--------------+
| transactions   | transactions |
| user_events    | user-events  |
+----------------+--------------+
----

=== Describe a database

To describe the database, execute the following query:

[source,sql]
----
DESCRIBE DATABASE;
----

The output consists of all existing tables from the specified database:

[source,sql]
----
+-----------------------------+
| name                        |
+-----------------------------+
| supplier_scale_1_no_index   |
| features                    |
| orders                      |
| features2                   |
| featurestable               |
| featurestable1              |
| featurestable10             |
+-----------------------------+
----
