= SELECT
:description: The SELECT statement helps you obtain the data you need from one or more tables.
:page-topic-type: reference

The `SELECT` statement helps you obtain the data you need from one or more tables.

The application of this statement will be helpful in several cases listed below:

* Evaluating data from only particular fields in a table.
* Reviewing data from several tables at the same time.
* Retrieving the data based on specific criteria.

== Syntax

To request data from a table using the `SELECT` statement, you can use the following syntax:

[source,sql]
----
SELECT * FROM table_name;
----

You are allowed to filter the table by column. Refer to the syntax below.

[source,sql]
----
SELECT column1, column2, ...
FROM table_name;
----

Each syntax element is defined as follows.

* `SELECT` determines the data to retrieve from the database or a table.
* `*` referred to as "select star" or "asterisk", represents all columns. It defines that the query should return all columns of the queried tables.
* `FROM` clause indicates the table(s) to retrieve data from.
* `table_name` represents the table(s) name.
* `column1, column2, ...` these are used to specify the columns from which to retrieve the data.

[NOTE]
====
The `SELECT` statement is case insensitive, which means `select` or `SELECT` has the same result.
====

== Examples

The following examples query a table named `student_data` that contains student records with `id`, `name`, and `domicile` columns.

=== Query data from all columns

. To display all the data from the `student_data` table, refer to the syntax below:
+
[source,sql]
----
SELECT * FROM table_name;
----

. Use the `SELECT` statement within the table name to get all the data:
+
[source,sql]
----
SELECT * FROM student_data;
----

. If you have successfully run the query, you will get all the data from the `student_data` table.
+
[source,sql]
----
+--------+----------+----------------+
| id     | name     | domicile       |
+--------+----------+----------------+
| 119291 | Jordan   | Los Angeles    |
| 119292 | Mike     | Melbourne      |
| 119293 | Will     | Sydney         |
+--------+----------+----------------+
----

=== Query data from specific columns

. To get the list of students’ names with their IDs, refer to the syntax below:
+
[source,sql]
----
SELECT column_1, column_2 FROM table_name;
----

. Run the following query:
+
[source,sql]
----
SELECT id, name FROM student_data;
----

. If you have successfully run the query, you will get a list of students’ IDs & names from the `student_data` table.
+
[source,sql]
----
+--------+----------+
| id     | name     |
+--------+----------+
| 119291 | Jordan   |
| 119292 | Mike     |
| 119293 | Will     |
+--------+----------+
----

=== Query data from a specific column with the condition

. With a large number of data, skimming for the desired data will require a long time. Apply conditions to the `SELECT` statement to narrow the results. Refer to the syntax below:
+
[source,sql]
----
SELECT column_1 FROM table_name WHERE condition;
----

. To find the student’s name who lives in Sydney, run the query below:
+
[source,sql]
----
SELECT name FROM student_data WHERE domicile='Sydney';
----

. If you have successfully run the query, the result shows that Will lives in Sydney.
+
[source,sql]
----
+----------+
| name     |
+----------+
| Will     |
+----------+
----
