= SET/SHOW
:description: The SET statement lets you set specific options while the SHOW statement helps you see the current values in Redpanda SQL.
:page-topic-type: reference

The `SET` statement lets you set specific options while the `SHOW` statement helps you see the current values in Redpanda SQL.

== Syntax

The syntax for these functions is as follows:

[tabs]
====
SET::
+
[source,sql]
----
SET <option> TO <value>;
----
+
[NOTE]
====
For options that accept boolean values, `<value>` can be either `ON` or `OFF`, which correspond to `TRUE` or `FALSE` respectively.
====

SHOW::
+
[source,sql]
----
SHOW <option>;
----

====

The available options that can be set and shown are:

* `extra_float_digits`: by default, Redpanda SQL displays a limited number of digits, but you can set how many extra digits are displayed after the decimal point in floating-point numbers by using this option
* `application_name`: sets a custom name for the application
* `timezone`: determines the time zone used for date and time functions
* `client_min_messages`: sets the message levels sent to the client (valid values are `DEBUG5`, `DEBUG4`, `DEBUG3`, `DEBUG2`, `DEBUG1`, `LOG`, `NOTICE`, `WARNING` and `ERROR`)
* `search_path`: defines namespaces at which Redpanda SQL looks for tables
* `enable_fast_math`: enables mathematical optimizations that trade precision for speed by utilizing faster, less accurate mathematical functions

== Examples

=== SET Statement

[tabs]
====
Extra_float_digits::
+
To change the number of displayed digits for floating-point values, use the `SET` statement in a following way:

[source,sql]
----
SET extra_float_digits TO 2;
----

[source,sql]
----
SHOW extra_float_digits;
----

[source,sql]
----
 extra_float_digits
--------------------
 2
----

Client_min_messages::
+
To change the client message, use the `SET` statement as follows:

[source,sql]
----
SET client_min_messages TO 'WARNING';
----

[source,sql]
----
SHOW client_min_messages;
----

[source,sql]
----
 client_min_messages
---------------------
 warning
----

Enable_fast_math::
+
To change the mode of the fast math option, use the `SET` statement like this:

[source,sql]
----
SET oxla.enable_fast_math = ON;
----

[source,sql]
----
SHOW oxla.enable_fast_math;
----

[source,sql]
----
 oxla_enable_fast_math
-----------------------
 1
(1 row)
----

====

=== SHOW Statement

[tabs]
====
Timezone::
+
To display the current timezone setting, use the following query:

[source,sql]
----
SHOW timezone;
----

[source,sql]
----
 timezone
----------
 Etc/UTC
----

Search_path::
+
To display the current search path, run the query below:

[source,sql]
----
SHOW search_path;
----

[source,sql]
----
 search_path
-------------
 public
----

Enable_fast_math::
+
To check the status of the fast math option, use the following method:

[source,sql]
----
SHOW oxla.enable_fast_math;
----

[source,sql]
----
 oxla_enable_fast_math
-----------------------
 0
(1 row)
----

====
