= Disable Kafka Connect
:description: Learn how to disable Kafka Connect using the Cloud API.

Kafka Connect is disabled by default on new clusters. If you previously enabled Kafka Connect on a cluster and want to disable it, you can use the Cloud API. 

NOTE: Redpanda Support does not manage or monitor Kafka Connect connectors, but Support can enable the feature for your account.

== Prerequisites

- You have the cluster ID of a cluster that has Kafka Connect enabled. In the Redpanda Cloud UI, go to the cluster overview and copy the cluster ID from the **Details** section.
- You have an API token, and you are authenticated to the Cloud API. For details, see xref:manage:api/cloud-api-authentication.adoc[Authenticate to the API].

== Disable Kafka Connect

After you are authenticated to the Cloud API, make a xref:api:ROOT:cloud-controlplane-api.adoc#patch-/v1/clusters/-cluster.id-[`PATCH /v1/clusters/{cluster.id}`] request, replacing `{cluster.id}` with your actual cluster ID.

[,bash]
----
curl -X PATCH "https://api.redpanda.com/v1/clusters/{cluster.id}" \
  -H "Authorization: Bearer $AUTH_TOKEN" \
  -H "Content-Type: application/json" \
  -d '{"kafka_connect":{"enabled":false}}'
----


The `PATCH` request returns the ID of a long-running operation. You can check the status of the operation by polling the xref:api:ROOT:cloud-controlplane-api.adoc#get-/v1/operations/-id-[`GET /operations/{id}`] endpoint:

[,bash]
----
curl -X GET "https://api.redpanda.com/v1/operations/{operation.id}" \
  -H "Authorization: Bearer $AUTH_TOKEN"
----


IMPORTANT: Make sure to stop any active connectors gracefully before disabling Kafka Connect to avoid data loss or incomplete processing.
