= Create a BYOC Cluster on AWS
:description: Use the Redpanda Cloud UI to create a BYOC cluster on AWS.
:page-aliases: get-started:cluster-types/byoc/create-byoc-cluster-aws.adoc, cloud:create-byoc-cluster-aws.adoc, deploy:deployment-option/cloud/create-byoc-cluster-aws.adoc

To create a Redpanda cluster in your virtual private cloud (VPC), follow the instructions in the Redpanda Cloud UI. The UI contains the parameters necessary to successfully run `rpk cloud byoc apply`. See also: xref:get-started:byoc-arch.adoc[BYOC architecture].

NOTE: With standard BYOC clusters, Redpanda manages security policies and resources for your VPC, including subnetworks, service accounts, IAM roles, firewall rules, and storage buckets. For the highest level of security, you can manage these resources yourself with a xref:./vpc-byo-aws.adoc[BYOVPC cluster on AWS].

== Prerequisites

Before you deploy a BYOC cluster on AWS, check that the user creating the cluster has the following prerequisites: 

* A minimum version of Redpanda `rpk` v24.1. See xref:manage:rpk/rpk-install.adoc[].
* The user authenticating to AWS has `AWSAdministratorAccess` access to create the IAM policies specified in xref:security:authorization/cloud-iam-policies.adoc[AWS IAM policies].

* The user has the AWS variables necessary to authenticate. Use either:
+
--
** `AWS_PROFILE` or
** `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`

To verify access, you should be able to successfully run `aws sts get-caller-identity` for your region. See the https://awscli.amazonaws.com/v2/documentation/api/latest/reference/sts/get-caller-identity.html[AWS CLI reference^].
--

== Create a BYOC cluster

. Log in to https://cloud.redpanda.com[Redpanda Cloud^].
. On the Clusters page, click *Create cluster*, then click *Create BYOC cluster*. 
. Enter a cluster name, then select the resource group, provider (AWS), xref:reference:tiers/byoc-tiers.adoc[region, tier], availability, and Redpanda version.
+
[NOTE]
==== 
* If you plan to create a private network in your own VPC, select the region where your VPC is located.
* Three availability zones provide two backups in case one availability zone goes down.
====
+ 
Optionally, click *Advanced settings* to specify up to five key-value custom tags. After the cluster is created, the tags are applied to all AWS resources associated with this cluster. For more information, see the https://docs.aws.amazon.com/mediaconnect/latest/ug/tagging-restrictions.html[AWS documentation^].

. Click *Next*.
. On the Network page, enter the connection type: either *Public* or *Private*. For BYOC clusters, *Private* is best-practice.
** Your network name is used to identify this network.
** For a xref:networking:cidr-ranges.adoc[CIDR range], choose one that does not overlap with your existing VPCs or your Redpanda network.
. Click *Next*.
. On the Deploy page, follow the steps to log in to Redpanda Cloud and deploy the agent.
+
As part of agent deployment:
+
** Redpanda assigns the permission required to run the agent. For details about these permissions, see xref:security:authorization/cloud-iam-policies.adoc[AWS IAM policies].
** Redpanda allocates one Elastic IP (EIP) address in AWS for each BYOC cluster. 

include::get-started:partial$no-access.adoc[]

== Manage custom resource tags

After cluster creation, you may need to update resource tags for compliance or organizational requirements. You can manage custom cloud provider tags and labels using the xref:manage:api/cloud-byoc-controlplane-api.adoc[Cloud Control Plane API].

Make sure you have:

* The cluster ID. You can find this in the Redpanda Cloud UI, in the **Details** section of the cluster overview.
* A valid bearer token for the Cloud Control Plane API. For details, see link:/api/doc/cloud-controlplane/authentication[Authenticate to the API]. 

include::shared:partial$feature-flag.adoc[]

. To refresh agent permissions so the Redpanda agent can update tags, run:
+
[,bash]
----
export CLUSTER_ID="<cluster-id>"

rpk cloud byoc aws apply --redpanda-id="$CLUSTER_ID"
----
+
This step is required because tag management requires additional IAM permissions that may not have been granted during initial cluster creation:
+
* `ec2:DescribeTags`
* `ec2:DescribeVolumes`
* `ec2:DescribeNetworkInterfaces`
* `ec2:CreateTags`
* `ec2:DeleteTags`
* `iam:TagPolicy`
* `iam:UntagPolicy`
* `iam:TagInstanceProfile`
* `iam:UntagInstanceProfile`

. To update tags, invoke the Cloud API.
+
First, set your authentication token:
+
[,bash]
----
export AUTH_TOKEN="<your-bearer-token>"
----
+
The `PATCH` call sets the tags specified under `"cloud_provider_tags"`. It replaces the existing tags with the specified tags. Include all desired tags in the request. To remove a single entry, omit it from the map you send.
+
[,bash]
----
cluster_patch_body=$(cat <<'JSON'
{
  "cloud_provider_tags": {
    "Environment": "production",
    "CostCenter": "engineering"
  }
}
JSON
)

curl -X PATCH "https://api.redpanda.com/v1/clusters/$CLUSTER_ID" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $AUTH_TOKEN" \
  -d "$cluster_patch_body"
----
+
To remove all tags, send an empty `cloud_provider_tags` object:
+
[,bash]
----
cluster_patch_body='{"cloud_provider_tags": {}}'

curl -X PATCH "https://api.redpanda.com/v1/clusters/$CLUSTER_ID" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $AUTH_TOKEN" \
  -d "$cluster_patch_body"
----

== Next steps

xref:networking:byoc/aws/index.adoc[Configure private networking]
