= Configure Azure Private Link with the Cloud API
:description: Set up Azure Private Link with the Cloud API.

NOTE: For UI-based configuration of Azure Private Link on new clusters, see xref:networking:azure-private-link-in-ui.adoc[Configure Azure Private Link in the Cloud UI].

The Redpanda Azure Private Link service provides secure access to Redpanda Cloud from your own virtual network. Traffic over Azure Private Link does not go through the public internet, but instead through Microsoft's backbone network. While clients can initiate connections against the Redpanda Cloud cluster endpoints, Redpanda Cloud services cannot access your virtual networks directly.

Consider using Private Link if you have multiple virtual networks and require more secure network management. To learn more, see the https://learn.microsoft.com/en-us/azure/private-link/private-link-service-overview[Azure documentation].

[NOTE]
====
* Each client VNet can have one endpoint connected to the Private Link service.
* Private Link allows overlapping xref:networking:cidr-ranges.adoc[CIDR ranges] in virtual networks.
* The number of connections is limited only by your Redpanda usage tier. Private Link does not add extra connection limits. 
====

After <<get-a-cloud-api-access-token,getting an access token>>, you can <<create-new-cluster-with-private-link-service-enabled,enable Private Link when creating a new cluster>>, or you can <<enable-private-link-service-for-existing-clusters,enable Private Link for existing clusters>>.

== Requirements

* Install xref:manage:rpk/rpk-install.adoc[`rpk`].
* Install https://jqlang.org/download/[`jq`^], which is used to parse JSON values from API responses. 
* You will use the https://learn.microsoft.com/en-us/cli/azure/[Azure CLI^] to authenticate with Azure and configure resources in your Azure account.
* You will use the xref:deploy:deployment-option/cloud/api/cloud-api-overview.adoc[Redpanda Cloud API] to enable the Redpanda Private Link service for your clusters. Follow the steps on this page to <<get-a-cloud-api-access-token, get an access token>>.

TIP: In Kafka clients, set `connections.max.idle.ms` to a value less than 240 seconds. 

== Set up Redpanda Private Link Service

=== Get a Cloud API access token

include::networking:partial$private-links-api-access-token.adoc[]

=== Specify Azure subscriptions

Set the Azure subscriptions you want to use for the Private Link connection.

Replace these placeholder variables:

* `<redpanda-cluster-subscription-id>`: The ID of the subscription where the Redpanda cluster is provisioned.
* `<source-connection-subscription-id>`: The ID of the subscription from where you initiate connections to the Private Link service.

You may use the same subscription for both.

[,bash]
----
export REDPANDA_CLUSTER_SUBSCRIPTION_ID=<redpanda-cluster-subscription-id>
export SOURCE_CONNECTION_SUBSCRIPTION_ID=<source-connection-subscription-id>
----

If you have not yet created a cluster in Redpanda Cloud, <<create-new-cluster-with-private-link-service-enabled,create a Private Link-enabled cluster>>. If you already have a cluster where you want to use Private Link, see the steps to <<enable-private-link-service-for-existing-clusters,enable Private Link for existing clusters>>.

=== Create new cluster with Private Link service enabled

. In the Redpanda Cloud UI, go to https://cloud.redpanda.com/resource-groups[**Resource groups**^] and select the Redpanda Cloud resource group in which you want to create a cluster.
+
NOTE: Redpanda Cloud resource groups exist in your Redpanda Cloud account only. They do not correspond to Azure resource groups and do not appear in your Azure tenant.
+
Copy and store the resource group ID (UUID) from the URL in the browser.
+
[,bash]
----
export RESOURCE_GROUP_ID=<uuid>
----    

. Call link:/api/doc/cloud-controlplane/operation/operation-networkservice_createnetwork[`POST /v1/networks`] to create a Redpanda Cloud network for the cluster.
+
Make sure to supply your own values in the following example request. Store the network ID (`network_id`) after the network is created to check whether you can proceed to cluster creation.
+
--
- `cluster-type`: `TYPE_BYOC` or `TYPE_DEDICATED`
- `network-name`
- `cidr_block`
- `azure-region`
--
+
[,bash]
----
REGION=<azure-region>

NETWORK_POST_BODY=`cat << EOF
{
    "network": {
        "cloud_provider": "CLOUD_PROVIDER_AZURE",
        "cluster_type": "<cluster-type>",
        "name": "<network-name>",
        "cidr_block": "<10.0.0.0/20>",
        "resource_group_id": "$RESOURCE_GROUP_ID",
        "region": "$REGION"
    }
}
EOF`

NETWORK_ID=`curl -vv -X POST \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $AUTH_TOKEN" \
    -d "$NETWORK_POST_BODY" $PUBLIC_API_ENDPOINT/v1/networks | jq .metadata.network_id`

echo $NETWORK_ID
----
+
Wait for the network to be ready before creating the cluster in the next step. Check the state of the network creation by calling link:/api/doc/cloud-controlplane/operation/operation-networkservice_getnetwork[`GET /v1/networks/\{id}`]. You can create the cluster when the state is `STATE_READY`.

. Create a new cluster with the Private Link service enabled by calling link:/api/doc/cloud-controlplane/operation/operation-clusterservice_createcluster[`POST /v1/clusters`].
+
In the following example, make sure to set your own values for the following fields:
+
--
- `name`
- `type`: `TYPE_BYOC` or `TYPE_DEDICATED`
- `tier`: For example, `tier-1-azure`. See available Azure tiers in the link:/api/doc/cloud-controlplane/topic/topic-regions-and-usage-tiers[Control Plane API reference]. To learn more about tiers, see xref:reference:tiers/byoc-tiers.adoc[BYOC Tiers and Regions] or xref:reference:tiers/dedicated-tiers.adoc[Dedicated Tiers and Regions]. 
- `zones`: For example, `"uksouth-az1",  "uksouth-az2", "uksouth-az3"`
--
+
[,bash]
----
CLUSTER_POST_BODY=`cat << EOF
{
  "cluster": {
    "cloud_provider": "CLOUD_PROVIDER_AZURE",
    "connection_type": "CONNECTION_TYPE_PRIVATE",
    "name": "<name>",
    "resource_group_id": "$RESOURCE_GROUP_ID",
    "network_id": "$NETWORK_ID",
    "region": "$REGION",
    "throughput_tier": "<tier>",
    "type": "<type>",
    "zones": [ <zones> ],
    "azure_private_link": { 
        "allowed_subscriptions": ["$SOURCE_CONNECTION_SUBSCRIPTION_ID"],
        "enabled": true,
        "connect_console": true
    }
  }
}
EOF`

CLUSTER_ID=`curl -vv -X POST \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $AUTH_TOKEN" \
    -d "$CLUSTER_POST_BODY" $PUBLIC_API_ENDPOINT/v1/clusters | jq -r .operation.metadata.cluster_id`

echo $CLUSTER_ID
----

. **BYOC clusters only:** Check that the cluster operation is completed by calling link:/api/doc/cloud-controlplane/operation/operation-operationservice_getoperation[`GET /v1/operations/\{id}`], and passing the operation ID returned from the Create Cluster call.
+
When the Create Cluster operation is completed (`STATE_COMPLETED`), run the following `rpk cloud` command to finish setting up your BYOC cluster with Private Link enabled:
+
[,bash]
----
rpk cloud byoc azure apply --redpanda-id=$CLUSTER_ID --subscription-id=$REDPANDA_CLUSTER_SUBSCRIPTION_ID
----

. Continue to <<configure-azure-private-link-connection-to-redpanda-cloud,configure the Private Link connection to Redpanda>>.

=== Enable Private Link service for existing clusters

CAUTION: As soon as Private Link is available on your virtual network, all communication on existing Redpanda bootstrap server and broker ports is interrupted due to the change on the private DNS resolution. Make sure all applications running in your virtual network are ready to start using the corresponding Private Link ports.

. In the Redpanda Cloud UI, go to the cluster overview and copy the cluster ID from the **Details** section.
+
[,bash]
----
CLUSTER_ID=<cluster_id>
----

. Make a link:/api/doc/cloud-controlplane/operation/operation-clusterservice_updatecluster[`PATCH /v1/clusters/{cluster.id}`] request to update the cluster with the service enabled.
+
[,bash]
----
CLUSTER_PATCH_BODY=`cat << EOF
{
  "azure_private_link": { 
      "allowed_subscriptions": ["$SOURCE_CONNECTION_SUBSCRIPTION_ID"],
      "enabled": true,
      "connect_console": true
  }
}
EOF`

curl -vv -X PATCH \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $AUTH_TOKEN" \
  -d "$CLUSTER_PATCH_BODY" $PUBLIC_API_ENDPOINT/v1/clusters/$CLUSTER_ID
----

. Before proceeding, check the state of the Update Cluster operation by calling link:/api/doc/cloud-controlplane/operation/operation-operationservice_getoperation[`GET /v1/operations/\{id}`], and passing the operation ID returned from the Update Cluster call. When the state is `STATE_READY`, continue to <<configure-azure-private-link-connection-to-redpanda-cloud,configure the Private Link connection to Redpanda>>.

== Configure Azure Private Link connection to Redpanda Cloud

. In the Redpanda Cloud UI, go to https://cloud.redpanda.com/users?tab=users[**Users**^] and create a new user to authenticate the Private Link endpoint connections with the service. You will need the username and password to <<connect-to-redpanda-services-through-private-link-endpoints,access Redpanda services>> or <<test-the-connection,test the connection>> using `rpk` or cURL.

. Call the link:/api/doc/cloud-controlplane/operation/operation-clusterservice_getcluster[`GET /v1/clusters/\{id}`] endpoint to check the service status and retrieve the service ID, DNS name, and Redpanda Console URL to use.
+
[,bash]
----
DNS_RECORD=`curl -s -X GET \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $AUTH_TOKEN" \
  $PUBLIC_API_ENDPOINT/v1/clusters/$CLUSTER_ID | jq -r ".cluster.azure_private_link.status.dns_a_record"`

PRIVATE_SERVICE_ID=`curl -s -X GET \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $AUTH_TOKEN" \
  $PUBLIC_API_ENDPOINT/v1/clusters/$CLUSTER_ID | jq -r ".cluster.azure_private_link.status.service_id"`

CONSOLE_URL=`curl -s -X GET \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $AUTH_TOKEN" \
  $PUBLIC_API_ENDPOINT/v1/clusters/$CLUSTER_ID | jq -r ".cluster.redpanda_console.url"`

echo $DNS_RECORD
echo $PRIVATE_SERVICE_ID
echo $CONSOLE_URL

----

. Log in to Azure and set the subscription ID to the value you set for `SOURCE_CONNECTION_SUBSCRIPTION_ID`:
+
[,bash]
----
az login
az account set --subscription $SOURCE_CONNECTION_SUBSCRIPTION_ID
----

=== Set up Azure Private Link endpoint in your virtual network

. If you have not already done so, create the Azure resource group and virtual network for your Private Link source connections.
+
```
az group create --name <azure-pl-endpoint-resource-group-name> --location $REGION
```
+
```
az network vnet create \
    --resource-group <azure-pl-endpoint-resource-group-name> \
    --location $REGION \
    --name <azure-pl-endpoint-vnet-name> \
    --address-prefixes 10.0.0.0/16 \
    --subnet-name <subnet-name> \
    --subnet-prefixes 10.0.0.0/24
```

. Create the private endpoint.
+
```
az network private-endpoint create \
    --location $REGION \
    --connection-name <private-link-service-name> \
    --name redpanda-$CLUSTER_ID \
    --manual-request true \
    --private-connection-resource-id $PRIVATE_SERVICE_ID \
    --resource-group <azure-pl-endpoint-resource-group-name> \
    --subnet <subnet-name> \
    --vnet-name <azure-pl-endpoint-vnet-name>
``` 

. Create a private DNS zone using the outputted DNS record above (`echo $DNS_RECORD`) 
+
```
az network private-dns zone create \
    --resource-group <azure-pl-endpoint-resource-group-name> \
    --name "$DNS_RECORD"
``` 

. Link the private DNS zone to the virtual network you created earlier, so virtual machines (VMs) and containers can resolve the Redpanda cluster domain.
+
```
az network private-dns link vnet create \
    --resource-group <azure-pl-endpoint-resource-group-name> \
    --zone-name "$CLUSTER_ID.byoc.prd.cloud.redpanda.com" \
    --name redpanda-$CLUSTER_ID-dns-zone-link \
    --virtual-network <azure-pl-endpoint-vnet-name> \
    --registration-enabled false
```

. Create a wildcard record in the private DNS zone.
+
```
az network private-dns record-set a add-record \
    --resource-group <azure-pl-endpoint-resource-group-name> \
    --zone-name redpanda-$CLUSTER_ID \
    --record-set-name "*" \
    --ipv4-address "$PRIVATE_ENDPOINT_IP"
```


== Connect to Redpanda services through Private Link endpoints

After you enable Private Link for your cluster, your connection URLs are available in the *How to Connect* section of the cluster overview in the Redpanda Cloud UI.

include::networking:partial$private-links-access-rp-services-through-vpc.adoc[]

=== Test the connection

You can test the Private Link connection from any VM or container in the subscription where the endpoint is created. If configuring a Kafka client isn't possible right away, you can do these checks using xref:ROOT:get-started:rpk-install.adoc[`rpk`] or cURL:

include::networking:partial$private-links-test-connection.adoc[]

