= Configure Azure Private Link with the Cloud API
:description: Set up Azure Private Link to securely access Redpanda Cloud.

The Redpanda Azure Private Link service provides secure access to Redpanda Cloud from your own virtual network. Traffic over Azure Private Link does not go through the public internet, but instead through Microsoft's backbone network. While clients can initiate connections against the Redpanda Cloud cluster endpoints, Redpanda Cloud services cannot access your virtual networks directly.

Consider using Private Link if you have multiple virtual networks and require more secure network management:

* Private Link allows overlapping xref:networking:cidr-ranges.adoc[CIDR ranges] in virtual networks.
* Private Link does not limit the number of connections.
After <<get-a-cloud-api-access-token,getting an access token>>, you can <<create-new-cluster-with-private-link-service-enabled,enable Private Link when creating a new BYOC cluster>>, or you can <<enable-private-link-service-for-existing-cluster,enable Private Link for existing BYOC clusters>>.

== Requirements

* You will use the xref:deploy:deployment-option/cloud/api/cloud-api-overview.adoc[Redpanda Cloud API] to enable the Redpanda Private Link service for your clusters. Follow the steps on this page to <<get-a-cloud-api-access-token, get an access token>>.
* Install xref:manage:rpk/rpk-install.adoc[`rpk`].
* You will use the https://learn.microsoft.com/en-us/cli/azure/[Azure CLI^] to authenticate with Azure and configure resources in your Azure account.

Learn more about Azure Private Link in the https://learn.microsoft.com/en-us/azure/private-link/private-link-service-overview[official Azure documentation].

== Get a Cloud API access token

include::networking:partial$private-links-api-access-token.adoc[]

== Specify Azure subscriptions

Set the Azure subscriptions you want to use for the Private Link connection.

Replace these placeholder variables:
- `<azure-subscription-id>`: The ID of the subscription where the Redpanda cluster will be provisioned.
- `<azure-private-link-subscription-id>`: The ID of the subscription from where you will initiate connections to the Private Link service.

[,bash]
----
export REDPANDA_CLUSTER_SUBSCRIPTION_ID=<azure-subscription-id>
export SOURCE_CONNECTION_SUBSCRIPTION_ID=<azure-private-link-subscription-id>
----

== Create new cluster with Private Link service enabled

. In the Redpanda Cloud UI, go to https://cloud.redpanda.com/resource-groups[**Resource groups**^] and select the Redpanda Cloud resource group in which you want to create a cluster.
+
NOTE: Redpanda Cloud resource groups exist in your Redpanda Cloud account only. They do not correspond to Azure resource groups and do not appear in your Azure tenant.
+
Copy and store the resource group ID (UUID) from the URL in the browser.
+
[,bash]
----
export RESOURCE_GROUP_ID=<uuid>
----    

. Call xref:api:ROOT:cloud-api.adoc#post-/v1beta2/networks[`POST /v1beta2/networks`] to create a Redpanda Cloud network for the cluster.
+
Make sure to supply your own values in the following example request. Store the network ID (`network_id`) after the network is created to check whether you can proceed to cluster creation.
+
--
- `network-name`
- `cidr_block`
- `azure-region`
--
+
[,bash]
----
REGION=<azure-region>

NETWORK_POST_BODY=`cat << EOF
{
    "cloud_provider": "CLOUD_PROVIDER_AZURE",
    "cluster_type": "TYPE_BYOC",
    "name": "<network-name>",
    "cidr_block": "<10.0.0.0/20>",
    "resource_group_id": "$RESOURCE_GROUP_ID",
    "region": "$REGION"
}
EOF`

NETWORK_ID=`curl -vv -X POST \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $AUTH_TOKEN" \
    -d "$NETWORK_POST_BODY" $PUBLIC_API_ENDPOINT/v1beta2/networks | jq .metadata.network_id`

echo $NETWORK_ID
----
+
Wait for the network to be ready before creating the cluster in the next step. You can check the state of the network creation by calling xref:api:ROOT:cloud-api.adoc#get-/v1beta2/networks/-id-[`GET /v1beta2/networks/\{id}`]. You can create the cluster when the state is `STATE_READY`.

. Create a new cluster with the Private Link service enabled by calling xref:api:ROOT:cloud-api.adoc#post-/v1beta2/clusters[`POST /v1beta2/clusters`].
+
In the following example, make sure to set your own values for the following fields:
+
--
- `name`
- `tier`: for example, `tier-1-azure`. See available Azure tiers in the xref:api:ROOT:cloud-api.adoc#api-description[Cloud API reference]. To learn more about tiers, see xref:reference/tiers/byoc-tiers.adoc[BYOC Tiers and Regions]. 
- `type`: `TYPE_BYOC` for BYOC clusters
- `zones`: for example, `"uksouth-az1",  "uksouth-az2", "uksouth-az3"`
--
+
[,bash]
----
CLUSTER_POST_BODY=`cat << EOF
{
  "cloud_provider": "CLOUD_PROVIDER_AZURE",
  "connection_type": "CONNECTION_TYPE_PRIVATE",
  "name": "<name>",
  "resource_group_id": "$RESOURCE_GROUP_ID",
  "network_id": "$NETWORK_ID",
  "region": "$REGION",
  "throughput_tier": "<tier>",
  "type": "TYPE_BYOC",
  "zones": [ <zones> ],
  "azure_private_link": { 
      "allowed_subscriptions": ["$SOURCE_CONNECTION_SUBSCRIPTION_ID"],
      "enabled": true,
      "connect_console": true
  }
}
EOF`

CLUSTER_ID=`curl -vv -X POST \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $AUTH_TOKEN" \
    -d "$CLUSTER_POST_BODY" $PUBLIC_API_ENDPOINT/v1beta2/clusters | jq .operation.metadata.cluster_id | sed 's/"//g'`

echo $CLUSTER_ID
----

. Check that the cluster operation is completed by calling xref:api:ROOT:cloud-api.adoc#get-/v1beta2/operations/-id-[`GET /v1beta2/operations/\{id}`], and passing the operation ID returned from the Create Cluster call.
+
When the Create Cluster operation is completed (`STATE_COMPLETED`), run the following `rpk cloud` command to finish setting up your BYOC cluster with Private Link enabled:
+
[,bash]
----
rpk cloud byoc azure apply --redpanda-id=$CLUSTER_ID --subscription-id=$REDPANDA_CLUSTER_SUBSCRIPTION_ID
----

. See next steps to <<configure-private-link-connection-to-redpanda-cloud,configure the Private Link connection to Redpanda>>.

== Enable Private Link service for existing cluster

. In the Redpanda Cloud UI, go to the cluster overview and copy the cluster ID from the **Details** section.
+
[,bash]
----
CLUSTER_ID=<cluster_id>
----

. Make a xref:api:ROOT:cloud-api.adoc#patch-/v1beta2/clusters/-cluster.id-[`PATCH /v1beta2/clusters/{cluster.id}`] request to update the cluster with the service enabled.
+
[,bash]
----
CLUSTER_PATCH_BODY=`cat << EOF
{
  "azure_private_link": { 
      "allowed_subscriptions": ["$SOURCE_CONNECTION_SUBSCRIPTION_ID"],
      "enabled": true,
      "connect_console": true
  }
}
EOF`

curl -vv -X PATCH \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $AUTH_TOKEN" \
  -d "$CLUSTER_PATCH_BODY" $PUBLIC_API_ENDPOINT/v1beta2/clusters/$CLUSTER_ID
----

. Before proceeding, check the state of the Update Cluster operation by calling xref:api:ROOT:cloud-api.adoc#get-/v1beta2/operations/-id-[`GET /v1beta2/operations/\{id}`], and passing the operation ID returned from Update Cluster call. When the state is `STATE_READY`, proceed to the next step to <<configure-private-link-connection-to-redpanda-cloud,configure the Private Link connection to Redpanda>>.

== Configure Private Link connection to Redpanda Cloud

. In the Cloud UI, go to https://cloud.redpanda.com/users?tab=users[**Users**^] and create a new user to authenticate the Private Link endpoint connections with the service. You will need the username and password to <<access-redpanda-services-through-private-link-endpoint,access Redpanda services>> or <<test-the-connection,test the connection>> using `rpk` or cURL.

. Call the xref:api:ROOT:cloud-api.adoc#get-/v1beta2/clusters/-id-[`GET /v1beta2/clusters/\{id}`] endpoint to check the service status and retrieve the connection ID, DNS name, and Redpanda Console URL to use.
+
[,bash]
----
DNS_RECORD=`curl -s -X GET \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $AUTH_TOKEN" \
  $PUBLIC_API_ENDPOINT/v1beta2/clusters/$CLUSTER_ID | jq -r ".cluster.azure_private_link.status.dns_a_record"`

PRIVATE_SERVICE_ID=`curl -s -X GET \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $AUTH_TOKEN" \
  $PUBLIC_API_ENDPOINT/v1beta2/clusters/$CLUSTER_ID | jq -r ".cluster.azure_private_link.status.service_id"`

CONSOLE_URL=`curl -s -X GET \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $AUTH_TOKEN" \
  $PUBLIC_API_ENDPOINT/v1beta2/clusters/$CLUSTER_ID | jq -r ".cluster.redpanda_console.url"`

echo $DNS_RECORD
echo $PRIVATE_SERVICE_ID
echo $CONSOLE_URL

----

. Log in to Azure and set the subscription ID to the value you set for `SOURCE_CONNECTION_SUBSCRIPTION_ID`:
+
[,bash]
----
az login
az account set --subscription $SOURCE_CONNECTION_SUBSCRIPTION_ID
----

// https://github.com/redpanda-data/cloud-examples/pull/12/ needs to be merged
. Run Terraform to create a virtual machine (VM) inside the Private Link subscription. You can clone the Redpanda Cloud examples https://github.com/redpanda-data/cloud-examples[repository^] and run the following code, or modify the example and write your own module:
+
[,bash]
----
cd customer-managed/azure/private-link/terraform

# Write Terraform variables out to a file

export MYGROUP=<rg-group>

terraform init
cat << EOF > terraform.tfvars
region = "$REGION"
resource_group_name = "$MYGROUP"
rp_endpoint_service_id = "$PRIVATE_SERVICE_ID"
rp_id = "$CLUSTER_ID"
rp_domain = "$DNS_RECORD"
rp_node_count = 3
EOF

cd terraform
terraform init
terraform apply -var-file="terraform.tfvars"

# When Terraform completes execution, export values to variables

VM_IP=$(terraform output -raw instance_public_ip)
KEY_PATH=$(terraform output -raw private_key_file_path)
----


== Access Redpanda services through Private Link endpoints

After you have enabled Private Link for your cluster, your connection URLs are available in the *How to Connect* section of the cluster overview in the Redpanda Cloud UI.

If you followed the previous step to run Terraform, you can also run the following to retrieve Private Link connection details, and then SSH into the VM that was created. From there, run the `rpk` commands provided in the <<test-the-connection,next section>> to test the connection:

[,bash]
----
echo $USER
echo $PASS
echo "brokers.${DNS_RECORD}:30292"
echo $VM_IP
echo $DNS_RECORD
echo $PRIVATE_SERVICE_ID
echo $CONSOLE_URL

cat << EOF 
Copy and paste this after sshing in:

export RPK_USER=$USER
export RPK_PASS=$PASS
export CONSOLE_URL=$CONSOLE_URL
export RPK_BROKERS=brokers.${DNS_RECORD}:30292

EOF

ssh -i $KEY_PATH redpanda@$VM_IP
# When prompted, paste and enter the output from the previous command
----


include::networking:partial$private-links-access-rp-services-through-vpc.adoc[]

== Test the connection

You can test the Private Link connection from any VM or container in the consumer virtual network. If configuring a Kafka client isn't possible right away, you can do these checks using xref:ROOT:get-started:rpk-install.adoc[`rpk`] or cURL:

include::networking:partial$private-links-test-connection.adoc[]

Optional: When you have completed testing, you can tear down the Terraform-managed resources by running:

[,bash]
----
terraform destroy -var-file="terraform.tfvars"
----
