= Configure Azure Private Link in the Cloud UI
:description: Set up Azure Private Link in the Redpanda Cloud UI.

NOTE: This guide is for configuring Azure Private Link using the Redpanda Cloud UI. To configure and manage Private Link on an existing public cluster, you must use the xref:networking:azure-private-link.adoc[Cloud API].

The Redpanda Azure Private Link service provides secure access to Redpanda Cloud from your own VNet. Traffic over Private Link does not go through the public internet because these connections are treated as their own private Azure service. While your VNet has access to the Redpanda VPC, Redpanda cannot access your VNet.

Consider using the endpoint service if you have multiple VNets and could benefit from a more simplified approach to network management:

* Private Link allows overlapping xref:networking:cidr-ranges.adoc[CIDR ranges].
* You control which Azure principals are allowed to connect to the endpoint service.

== Requirements

* Your Redpanda cluster and VNet must be in the same region.
* Use the https://learn.microsoft.com/en-us/cli/azure/get-started-with-azure-cli?view=azure-cli-latest[Azure command-line interface (CLI)^] to create a new client VNet or modify an existing one to use the Private Link endpoint.

TIP: In Kafka clients, set `connections.max.idle.ms` to a value less than 350 seconds. 

== Enable endpoint service for new clusters

. In the Redpanda Cloud UI, create a new cluster.
. In the *Networking* section, for Connection type, select *Private*.
.. For *Azure Private Link*, select *Enabled*. 
.. For *Allowed subscriptions*, click *Add subscription*, and enter the Azure subscription ID that can access the cluster. You can add multiple subscriptions.     

== Enable endpoint service for existing clusters

. In the Redpanda Cloud UI, select your cluster, and go to the *Cluster settings* page.
. For Azure Private Link, click *Enable*.
. It may take several minutes for your cluster to update. When the update is complete, the Azure Private Link status on the Cluster settings page changes from *In progress* to *Enabled*.

== Access Redpanda services through VNet endpoint

After you have enabled Private Link for your cluster, your connection URLs are available in the *How to Connect* section of the cluster overview in the Redpanda Cloud UI.

include::networking:partial$private-links-access-rp-services-through-vpc.adoc[]

== Test the connection

You can test the connection to the endpoint service from any VM or container in the consumer VPC. If configuring a client isn't possible right away, you can do these checks using `rpk` or cURL:

include::networking:partial$private-links-test-connection.adoc[]

== Disable endpoint service

On the Cluster settings page for the cluster, click *Disable* for Private Link. Existing connections are closed after the Azure Private Link service is disabled. To connect using Private Link again, you must re-enable the service.
