# Asynchronous workflow pipeline
# Processes events in the background with acceptable latency
# tag::pipeline[]
input:
  redpanda:
    seed_brokers: ["${REDPANDA_BROKERS}"]
    topics: [daily-reports]
    consumer_group: report-analyzer
    tls:
      enabled: true
    sasl:
      - mechanism: SCRAM-SHA-256
        username: "${REDPANDA_USERNAME}"
        password: "${REDPANDA_PASSWORD}"

pipeline:
  processors:
    - a2a_message:
        agent_card_url: "${AGENT_CARD_URL}"
        prompt: "Summarize this report: ${!content()}"
# end::pipeline[]

output:
  redpanda:
    seed_brokers: ["${REDPANDA_BROKERS}"]
    topic: report-summaries
    tls:
      enabled: true
    sasl:
      - mechanism: SCRAM-SHA-256
        username: "${REDPANDA_USERNAME}"
        password: "${REDPANDA_PASSWORD}"
