= Dedicated
:description: Learn how to create a Dedicated cluster and start streaming.
:page-aliases: cloud:create-dedicated-cloud-cluster-aws.adoc, deploy:deployment-option/cloud/provision-a-dedicated-cluster/index.adoc, deploy:deployment-option/cloud/create-dedicated-cloud-cluster-aws.adoc, get-started:cluster-types/dedicated/create-dedicated-cloud-cluster-aws.adoc, get-started:cluster-types/dedicated/quick-start-cloud.adoc, get-started:cluster-types/dedicated/index.adoc, get-started:cluster-types/dedicated/create-dedicated-cloud-cluster.adoc

After you log in to https://cloud.redpanda.com[Redpanda Cloud^], you land on the *Clusters* page. This page lists all the clusters in your organization. 

== Create a Dedicated cluster

. On the Clusters page, click *Create cluster*, then click *Create Dedicated cluster*.
+
Enter a cluster name, then select the resource group, cloud provider (AWS, GCP, or Azure), xref:reference:tiers/dedicated-tiers.adoc[region, tier], availability, and Redpanda version.
+
[NOTE]
====
* If you plan to create a private network in your own VPC, select the region where your VPC is located.
* Three availability zones provide two backups in case one availability zone goes down.
====

. Click *Next*.
. On the Network page, enter the connection type: public or private. For private networks:
** Your network name is used to identify this network.
** For a xref:networking:cidr-ranges.adoc[CIDR range], choose one that does not overlap with your existing VPCs or your Redpanda network.
+
Private networks require either a VPC peering connection or a private connectivity service, such as xref:networking:configure-privatelink-in-cloud-ui.adoc[AWS PrivateLink], xref:networking:configure-private-service-connect-in-cloud-ui.adoc[GCP Private Service Connect], or xref:networking:azure-private-link.adoc[Azure Private Link]. 
** Clusters with private networking include a setting for API gateway access. Public access exposes endpoints for Redpanda Console, the Data Plane API, and the MCP Server API, but they are still protected by authentication and authorization controls. Private access restricts endpoint access to your VPC/VNet only.
+
NOTE: If you change from public access to private access after cluster creation, users without VPN access to your VPC/VNet will lose access to these services.

. Click *Create*.
+
After the cluster is created, you can select the cluster on the *Clusters* page to see the overview for it.

== Start streaming: example

Use `rpk`, Redpanda's CLI, to build a basic streaming application that creates a topic, produces messages to it, and consumes messages from it. To learn about `rpk`, see the xref:manage:rpk/intro-to-rpk.adoc[].

. Login to Redpanda Cloud, and select your resource group using the interactive prompt.
+ 
```bash
rpk cloud login
```

. On the **Overview** page, copy your bootstrap server address and set it as an environment variable on your local machine:
+
```bash
export REDPANDA_BROKERS="<bootstrap-server-address>"
```

. Go to the **Security** page, and create a user called **redpanda-chat-account** that uses the SCRAM-SHA-256 mechanism.

. Copy the password, and set the following environment variables on your local machine:
+
```bash
export REDPANDA_SASL_USERNAME="redpanda-chat-account"
export REDPANDA_SASL_PASSWORD="<password>"
export REDPANDA_SASL_MECHANISM="SCRAM-SHA-256"
```

. Click the name of your user, and add the following permissions to the ACL (access control list):
+
- **Host**: *
- **Topic name**: `chat-room`
- **Operations**: All
+ 
. Click **Create**.

. Use `rpk` on your local machine to authenticate to Redpanda as the **redpanda-chat-account** user and get information about the cluster:
+
```bash
rpk cluster info -X tls.enabled=true
```

. Create a topic called `chat-room`.
+
You granted permissions to the **redpanda-chat-account** user to access only this topic.
+
```bash
rpk topic create chat-room -X tls.enabled=true
```
+
Output:
+
[.no-copy]
----
TOPIC       STATUS
chat-room  OK
----

. Produce a message to the topic:
+
```bash
rpk topic produce chat-room -X tls.enabled=true
```

. Enter a message, then press kbd:[Enter]:
+
```text
Pandas are fabulous!
```
+
Example output:
+
[.no-copy]
----
Produced to partition 0 at offset 0 with timestamp 1663282629789.
----

. Press kbd:[Ctrl + C] to finish producing messages to the topic.

. Consume one message from the topic:
+
```bash
rpk topic consume chat-room --num 1 -X tls.enabled=true
```
+
Your message is displayed along with its metadata:
+
```json
{
  "topic": "chat-room",
  "value": "Pandas are fabulous!",
  "timestamp": 1663282629789,
  "partition": 0,
  "offset": 0
}
```

=== Explore your topic

In Redpanda Cloud, go to **Topics** > **chat-room**.

The message that you produced to the topic is displayed along with some other details about the topic.

=== Clean up

If you don't want to continue experimenting with your cluster, you can delete it.

Go to **Cluster settings** and click **Delete cluster**.

== Next steps

- xref:get-started:cloud-overview.adoc[Learn more about Redpanda Cloud]
- xref:networking:dedicated/index.adoc[Learn about private networking]

