= Serverless
:description: Learn how to create a Serverless cluster and start streaming.
:page-aliases: get-started:cluster-types/serverless-pro.adoc, ROOT:deploy:deployment-option/cloud/serverless.adoc 


Serverless is the fastest and easiest way to start data streaming. With Serverless clusters, you host your data in Redpanda's VPC, and Redpanda handles automatic scaling, provisioning, operations, and maintenance. This is a production-ready deployment option with a cluster available instantly, and you only pay for what you consume. You can view detailed billing activity for each cluster and edit payment methods on the *Billing* page. 

[NOTE]
====
* Serverless on AWS is currently in a glossterm:LA[,limited availability (LA)] release. During LA, existing clusters can scale to the usage limits, but new clusters may need to wait for availability.
* Serverless on GCP is currently in a glossterm:beta[] release. To unlock this feature, contact https://support.redpanda.com/hc/en-us/requests/new[Redpanda Support^].

====

== Serverless usage limits

Each Serverless cluster has the following maximum usage limits:

[cols="1,3",options="header"]
|===
| Metric | Limit

| Ingress | 100 MB/s
| Egress | 300 MB/s
| Partitions | 5,000
| Message size | 20 MB
| Retention | unlimited
| Storage | unlimited
| Users | 30
| ACLs | 120
| Consumer groups | 200
| Connections | 10,000
|===


NOTE: The partition limit is the number of logical partitions before replication occurs. Redpanda Cloud uses a replication factor of 3.

== Get started with Serverless

Choose the option that fits how you want to subscribe:

include::get-started:partial$get-started-serverless.adoc[]

== Prerequisites

Make sure you have the latest version of `rpk`, the Redpanda CLI. See xref:get-started:rpk-install.adoc[].

== Create a Serverless cluster

To create a Serverless cluster: 

. In the https://cloud.redpanda.com[Redpanda Cloud UI^], on the **Clusters** page, click **Create cluster**, then click **Create Serverless cluster**. 

. Enter a cluster name, then select the resource group. If you don't have an existing resource group, you can create one. Refresh the page to see newly-created resource groups. 
+
TIP: Serverless clusters are available in the regions listed in xref:reference:tiers/serverless-regions.adoc[Serverless regions]. Redpanda expects your applications to be deployed in the same region. For best performance, select the region closest to your applications. Serverless is not guaranteed to be pinned to a particular availability zone within that region.

=== Get started

A Serverless cluster's *Overview* page provides a quick way to get started with a xref:develop:connect/about.adoc[Redpanda Connect] pipeline. Pipelines help you stream data into and out of Redpanda without writing producer/consumer code. If you skip the wizard, you can come back to it here later, or you can create a pipeline anytime on the *Connect* page. The get started wizard helps you:

1. Select your data sources: Pick an input data source (to send data into Redpanda) or an output data source (to send data in Redpanda to an external system).
2. Configure minimal settings. You can fine-tune the pipeline later.
3. Verify data flow: Open the Redpanda glossterm:topic[] to see messages streaming.

=== Interact with your cluster

Explore the rest of the UI: Go to the *Topics* page to create new topics for data streams. Under the *Actions* dropdown, you can produce messages to topics. Add team members and grant them access with glossterm:ACL[,access control lists (ACLs)] on the *Security* page.

Go to the *How to connect - CLI* part of the *Overview* page for steps on how to use `rpk` to interact with your cluster from the command line. Here are some helpful commands:

* xref:reference:rpk/rpk-cloud/rpk-cloud-login.adoc[`rpk cloud login`]: Use this to log in to Redpanda Cloud or to refresh the session.
* xref:reference:rpk/rpk-topic.adoc[`rpk topic`]: Use this to manage topics, produce data, and consume data. 
* xref:reference:rpk/rpk-profile/rpk-profile-print.adoc[`rpk profile print`]: Use this to view your `rpk` configuration and see the URL for your Serverless cluster.
* xref:reference:rpk/rpk-security/rpk-security-user.adoc[`rpk security user`]: Use this to manage users and permissions. 

NOTE: Redpanda Serverless is opinionated about Kafka configurations. For example, automatic topic creation is disabled. Some systems expect the Kafka service to automatically create topics when a message is produced to a topic that doesn't exist. Create topics on the *Topics* page or with `rpk topic create`.

The *How to connect - Kafka API* tab lists your bootstrap server URL and security settings. This area includes code examples for creating a Kafka client to interact with your cluster.

Or, Redpanda can generate a sample application to interact with your cluster. Run xref:reference:rpk/rpk-generate/rpk-generate-app.adoc[`rpk generate app`], and select your preferred programming language. Follow the commands in the terminal to run the application, create a demo topic, produce to the topic, and consume the data back.

== Supported features

* Redpanda Serverless supports the Kafka API. Serverless clusters work with all Kafka clients. See xref:develop:kafka-clients.adoc[].
* Serverless clusters support all major Apache Kafka messages for managing topics, producing/consuming data (including transactions), managing groups, managing offsets, and managing ACLs. (User management is available in the Redpanda Cloud UI or with `rpk security acl`.) 

=== Unsupported features

Not all features included in BYOC clusters are available in Serverless. For example, the following features are not supported:

* HTTP Proxy API
* Ability to export metrics to a third-party monitoring system
* Private networking (VPC peering or AWS PrivateLink)
* Multiple availability zones (AZs)
* RBAC in the data plane and mTLS authentication for Kafka API clients
* Kafka Connect 

== Next steps

* xref:get-started:cloud-overview.adoc[Learn more about Redpanda Cloud]
* xref:get-started:config-topics.adoc[Manage topics]
* xref:billing:billing.adoc[Learn about billing]