= Serverless
:description: Learn how to create a Serverless cluster and start streaming.
:page-aliases: get-started:cluster-types/serverless-pro.adoc, ROOT:deploy:deployment-option/cloud/serverless.adoc 


Serverless is the fastest and easiest way to start data streaming. With Serverless clusters, you host your data in Redpanda's VPC, and Redpanda handles automatic scaling, provisioning, operations, and maintenance. This is a production-ready deployment option with a cluster available instantly, and you only pay for what you consume. You can view detailed billing activity for each cluster and edit payment methods on the *Billing* page. 

[NOTE]
====
Serverless on GCP is currently in a glossterm:beta[] release. 

====

== Serverless usage limits

Each Serverless cluster has the following maximum usage limits:

* **Ingress**: 100 MB/s
* **Egress**: 300 MB/s
* **Partitions**: 5,000 
* **Message size**: 20 MiB
* **Retention**: unlimited
* **Storage**: unlimited
* **Users**: 30
* **ACLs**: 120
* **Consumer groups**: 200
* **Connections**: 10,000 


NOTE: The partition limit is the number of logical partitions before replication occurs. Redpanda Cloud uses a replication factor of 3.

== Prerequisites

Make sure you have the latest version of `rpk`, the Redpanda CLI. See xref:get-started:rpk-install.adoc[].

== Get started with Serverless

Choose the option that fits how you want to subscribe:

include::get-started:partial$get-started-serverless.adoc[]

== Create a Serverless cluster

To create a Serverless cluster: 

. In the https://cloud.redpanda.com[Redpanda Cloud Console^], on the **Clusters** page, click **Create cluster**, then click **Create** for Serverless. 

. Enter a cluster name, then select the resource group. 
+
If you don't have an existing resource group, you can create one. Refresh the page to see newly-created resource groups. 

. Select a cloud provider and xref:reference:tiers/serverless-regions.adoc[region]. For best performance, select the region closest to your applications. Redpanda expects your applications to be deployed in the same cloud provider and region as your Serverless cluster. 
+
Clusters on AWS can enable private access between their VPC and Redpanda, so data does not traverse the public internet. Private connectivity is implemented using AWS PrivateLink for secure ingress traffic.
+
** A Serverless cluster can have both public and private access enabled.
** You can either create a new PrivateLink or use an existing one from the same resource group.
** You can enable or disable private access at any time on the cluster's *Settings* page. 
** Enabling private access incurs additional charges.
+
NOTE: After private access is disabled, attempts to reach the private endpoints will fail. However, the PrivateLink endpoint in your AWS account and the PrivateLink resource in Redpanda Cloud both remain provisioned and continue to incur charges until you explicitly delete them.     

. Click **Create cluster**.

. To start working with your cluster, go to the *Topics* page to create a topic and produce messages to it. Add team members and grant them access with ACLs on the *Security* page. 

== Interact with your cluster

include::get-started:partial$cloud-quickstart.adoc[]

The *Overview* page lists your bootstrap server URL and security settings in the *How to connect - Kafka API* tab. Here you can add a Kafka client to interact with your cluster. 

Or, Redpanda can generate a sample application to interact with your cluster. Run xref:reference:rpk/rpk-generate/rpk-generate-app.adoc[`rpk generate app`], and select Go as the language. Follow the commands in the terminal to run the application, create a demo topic, produce to the topic, and consume the data back.

Follow the steps in the Console to use `rpk` to interact with your cluster from the command line. Here are some helpful commands:

* xref:reference:rpk/rpk-cloud/rpk-cloud-login.adoc[`rpk cloud login`]: Use this to log in to Redpanda Cloud or to refresh the session.
* xref:reference:rpk/rpk-topic.adoc[`rpk topic`]: Use this to manage topics, produce data, and consume data. 
* xref:reference:rpk/rpk-profile/rpk-profile-print.adoc[`rpk profile print`]: Use this to view your `rpk` configuration and see the URL for your Serverless cluster.
* xref:reference:rpk/rpk-security/rpk-security-user.adoc[`rpk security user`]: Use this to manage users and permissions. 

NOTE: Redpanda Serverless is opinionated about Kafka configurations. For example, automatic topic creation is disabled. Some systems expect the Kafka service to automatically create topics when a message is produced to a topic that doesn't exist. Create topics on the *Topics* page or with `rpk topic create`.

== Supported features

* Redpanda Serverless supports the Kafka API. Serverless clusters work with all Kafka clients. See xref:develop:kafka-clients.adoc[].
* Serverless clusters support all major Apache Kafka messages for managing topics, producing/consuming data (including transactions), managing groups, managing offsets, and managing ACLs. (User management is available in the https://cloud.redpanda.com[Redpanda Cloud Console^] or with `rpk security acl`.) 

=== Unsupported features

Not all features included in BYOC clusters are available in Serverless. For example, the following features are not supported:

* HTTP Proxy API
* Multiple availability zones (AZs)
* RBAC in the data plane and mTLS authentication for Kafka API clients
* Kafka Connect 

== Next steps

* xref:networking:serverless/aws/index.adoc[Set up private access for Serverless clusters]
* xref:get-started:cloud-overview.adoc[Learn more about Redpanda Cloud]
* xref:get-started:config-topics.adoc[Manage topics]
* xref:billing:billing.adoc[Learn about billing]