= Serverless Pro
:description: Learn how to create a Serverless Pro cluster.

Redpanda Serverless is the fastest and easiest way to start data streaming. Serverless Pro is an enterprise-level version of xref:get-started:cluster-types/serverless.adoc[Serverless Standard]. It comes with higher usage limits and dedicated support. A cluster is available instantly, and you only pay for what you consume. For information about all Redpanda Cloud cluster types, see xref:get-started:cloud-overview.adoc[].

NOTE: Serverless Pro is currently in a limited availability (LA) release with xref:get-started:cluster-types/serverless-pro.adoc#limits[usage limits]. During LA, existing clusters can scale to the usage limits, but new clusters may need to wait for availability.

== Prerequisites

Make sure you have the latest version of `rpk`. See xref:get-started:rpk-install.adoc[].

== Serverless Pro usage limits

Each Serverless Pro cluster has the following limits:

* Ingress: 10 MBps
* Egress: 20 MBps
* Partitions: 500 partitions
* Message size: 20 MB
* Retention: unlimited time
* Storage: unlimited
* Users: 30
* ACLs: 120
* Consumer groups: 200


[NOTE]
====
* The partition limit is the number of logical partitions before replication occurs. Redpanda Cloud uses a replication factor of 3.
* To increase your limits, contact https://support.redpanda.com/hc/en-us/requests/new[Redpanda Support^]. 
====

== Get started with Serverless Pro

To start using Serverless Pro, contact https://redpanda.com/try-redpanda?section=enterprise-trial[Redpanda sales^]. 

You can also subscribe to Redpanda Cloud through xref:billing:aws-pay-as-you-go.adoc[AWS Marketplace] to quickly provision Serverless clusters. New subscriptions receive $300 (USD) in free credits to spend in the first 30 days. AWS Marketplace charges for anything beyond $300, unless you cancel the subscription. After your free credits have been used, you can continue using your cluster without any commitment, only paying for what you consume and canceling anytime. You can view detailed billing activity for each cluster and edit payment methods on the *Billing* page. 

== Explore your cluster

After you click to sign up for Serverless Pro, Redpanda instantly prepares an account for you. Your account includes a `welcome` cluster with a `hello-world` demo topic you can explore. The `hello-world` topic starts as a free read-only topic. It is materialized and becomes billable with your credits if you produce messages to it. 

Follow the steps in the UI to use `rpk` to interact with your cluster from the command line:

. Log in:
+
```
rpk cloud login
```

. Consume from the `hello-world` topic:
+
```
rpk topic consume hello-world
```

In the https://cloud.redpanda.com[Redpanda Cloud UI^], you can navigate to the *Topics* page and open the `hello-world` topic to see the included messages. Under the *Actions* dropdown, you can produce messages to it. Add team members and grant them access with ACLs on the *Security* page. 

== Connect with your cluster

Create a Kafka client to interact with your cluster. The *Overview* page lists your bootstrap server URL and security settings in the *How to connect - Kafka API* tab. 

Or, Redpanda can generate a sample application to interact with your cluster. Run xref:reference:rpk/rpk-generate/rpk-generate-app.adoc[`rpk generate app`], and select your preferred programming language. Follow the commands in the terminal to run the application, create a demo topic, produce to the topic, and consume the data back.

Here are some helpful `rpk` commands:

* xref:reference:rpk/rpk-cloud/rpk-cloud-login.adoc[`rpk cloud login`]: Use this to log in to Redpanda Cloud or to refresh the session.
* xref:reference:rpk/rpk-topic.adoc[`rpk topic`]: Use this to manage topics, produce data, and consume data. 
* xref:reference:rpk/rpk-profile/rpk-profile-print.adoc[`rpk profile print`]: Use this to view your `rpk` configuration and see the URL for your Serverless cluster.
* xref:reference:rpk/rpk-security/rpk-security-user.adoc[`rpk security user`]: Use this to manage users and permissions. 

NOTE: Redpanda Serverless is opinionated about Kafka configurations. For example, automatic topic creation is disabled. Some systems expect the Kafka service to automatically create topics when a message is produced to a topic that doesn't exist. Create topics on the *Topics* page or with `rpk topic create`.

== Create a new Serverless Pro cluster

To create additional Serverless Pro clusters: 

. In Redpanda Cloud UI, on the **Clusters** page, click **Create cluster**, then click **Create Serverless Pro cluster**. 

. Enter a cluster name, then select the resource group. If you don't have an existing resource group, you can create one. Refresh the page to see newly-created resource groups. 
+
Serverless clusters are currently available in certain AWS regions. Redpanda expects your applications to be deployed in the same AWS region. For best performance, select the region closest to your applications. Serverless is not guaranteed to be pinned to a particular availability zone within that region.

== Supported features

* Redpanda Serverless supports the Kafka API. 
* Serverless clusters work with all Kafka clients. For more information, see xref:develop:kafka-clients.adoc[].
* Serverless clusters support all major Apache Kafka messages for managing topics, producing/consuming data (including transactions), managing groups, managing offsets, and managing ACLs. (User management is available in the Redpanda Cloud UI or with `rpk security acl`.) 

=== Unsupported features

* Kafka Connect managed connectors
* Data transforms
* Redpanda Admin API 
* HTTP Proxy API

== Next steps

* xref:get-started:cloud-overview.adoc[Learn more about Redpanda Cloud]
* xref:get-started:config-topics.adoc[Manage topics]
* xref:billing:billing.adoc[Learn about billing]