= Authorization
:description: Learn about user authorization and agent authorization in Redpanda Cloud.
:page-aliases: deploy:deployment-option/cloud/security/authorization/cloud-authorization.adoc

There are two types of authorization in Redpanda Cloud:

* User authorization
+
** Use xref:security:authorization/rbac/index.adoc[role-based access control (RBAC)] in the glossterm:control plane[] and in the glossterm:data plane[] to assign users access to specific resources. For example, you could assign all users with a certain job title read access on the entire organization and write access only on your non-production resource group. This alleviates the process of manually maintaining and verifying a set of ACLs for a user base that may contain thousands of users.
** Use Kafka glossterm:ACL[,access control lists (ACLs)] to grant users permission to perform specific types of operations on specific resources (such as topics, groups, clusters, or transactional IDs).

* BYOC agent authorization
+
When deploying an agent as part of BYOC cluster
provisioning, Redpanda Cloud automatically assigns IAM policies to the agent.
The IAM policy permissions granted to the agent provide it the authorization
required to fully manage Redpanda Cloud clusters in xref:security:authorization/cloud-iam-policies.adoc[AWS], xref:security:authorization/cloud-iam-policies-azure.adoc[Azure], or xref:security:authorization/cloud-iam-policies-gcp.adoc[GCP]. 
+
IMPORTANT: IAM policies do not apply or act as deployment permissions, and there are no
explicit user actions associated with IAM policies. Rather, IAM policy
permissions apply to Redpanda Cloud agents _only_, and serve to provide Redpanda
agents access to AWS, GCP, or Azure clusters so Redpanda brokers can communicate
with them.
