= Authorization
:description: Learn about user authorization and agent authorization in Redpanda Cloud.
:page-aliases: deploy:deployment-option/cloud/security/authorization/cloud-authorization.adoc

There are two types of authorization in Redpanda Cloud:

* User authorization
+
User authorizations, managed by Kafka glossterm:ACL[,access control lists (ACLs)],
grant users permission to perform specific types of operations on specific
resources (such as topics, groups, clusters, or transactional IDs).

* Agent authorization
+
When deploying an agent as part of BYOC cluster
provisioning, Redpanda Cloud automatically assigns IAM policies to the agent.
The IAM policy permissions granted to the agent provide it the authorization
required to fully manage Redpanda Cloud clusters in xref:security:authorization/cloud-iam-policies.adoc[AWS], xref:security:authorization/cloud-iam-policies-azure.adoc[Azure], or xref:security:authorization/cloud-iam-policies-gcp.adoc[GCP]. 
+
IMPORTANT: IAM policies do not apply or act as deployment permissions, and there are no
explicit user actions associated with IAM policies. Rather, IAM policy
permissions apply to Redpanda Cloud agents _only_, and serve to provide Redpanda
agents access to AWS, GCP, or Azure clusters so Redpanda brokers can communicate
with them.
