= Role-Based Access Control
:description: Role-based access control (RBAC) lets you manage and restrict access to specific resources in your organization.
:page-categories: Management, Security
:page-beta: true

Use role-based access control (RBAC) in Redpanda Cloud to manage and restrict access to specific resources in your organization. For example, you can allow all users with a certain job reader access to your development clusters but only allow some users writer access to your production clusters.

You can manage your RBAC configurations with the https://cloud.redpanda.com[Redpanda Cloud UI^] or the xref:api:ROOT:cloud-api.adoc[Cloud API]. 

== RBAC terminology

**Role**: A role is a list of permissions. With RBAC, permissions are attached to roles, and you assign permissions to users based on their role. Users with multiple roles receive the union of all permissions defined in those roles. Redpanda Cloud has three predefined roles: 

- Admin
- Writer
- Reader

**Account**: An RBAC account is either a user account (human user) or a service account (machine or programmatic user).

**Role binding**: Role binding connects, or _assigns_ a role to an account. 

When a user is associated with more than one role, the user is granted all the permissions defined in each role they are assigned. For example, if a user is assigned both the reader and writer roles, they have all the permissions of a reader as well as the additional permissions of a writer. Duplicate role bindings do not cause errors or conflicts. If a user is assigned the same role multiple times through role bindings, the duplicate role bindings do not affect the user's final set of permissions.

**RBAC resources**: The following resources can be assigned in a role: 

- Organization 	
- Resource group
- Network
- Cluster
- Network peering

== Manage access for organization

In the Redpanda Cloud UI, go to the *Organization IAM* page to see a list of your organization's existing users and service accounts and their associated roles. You can edit a user's access, invite users, or create service accounts. When you add a user, you define the roles for it. Service accounts are assigned admin permission to all resources in the organization. 

Select a user or service account to see their roles. For example, for a user with admin access on the whole organization, the user's _resource_ is the organization name, the _scope_ is the organization, and the _role_ is admin. 

You could assign a user the reader role on the organization, the admin role on a specific resource group, and the writer role on a specific cluster.

When you change the permissions for a given role, all users and service accounts with that role automatically get the modified permissions. You can assign any number of roles to an account. 

You can edit by selecting the user (Org IAM - Users) and deleting the role binding. Users may see that resources exist, but they cannot access them without the necessary role. 

When starting with a new Redpanda organization, no roles are provisioned by default. 

When you delete a role, Redpanda removes it from any user or service account it is attached to, and permissions are revoked.

Link to Control Plane API? 

== Predefined roles

Redpanda Cloud provides the following predefined roles: <<viewer,viewer>>, <<editor,editor>>, and <<admin,admin>>.

=== Viewer

The viewer role grants permission to view all resources. This includes:

* View all topic aspects (messages, configs, partitions, using search filters)
* View all cluster aspects (node configs, ACLs, service accounts, quotas)
* View all consumer group aspects (consumer groups, group offsets, and lags)
* View all schema registry aspects (registered schemas with their contents)
* View all Kafka Connect aspects (list configured clusters and their connectors, including the status and connector configs)
* It does not include permission to view the list of users.

=== Editor

The editor role grants all permissions that come with the viewer role and additionally includes:

* Manage all topic aspects, such as creating topics, editing topic configurations, deleting topics, and publishing and deleting topic records.
* Manage all cluster configuration aspects, such as editing node or cluster configs.
* Manage all consumer group aspects, such as editing group offsets or deleting group offsets.
* Manage all Kafka connect aspects, such as creating/updating/deleting or starting/pausing/stopping connectors.
* It does not include permission to create/remove ACLs or to create or remove a service account.

=== Admin

The admin role grants all permissions that come with the editor role and additionally includes:

* Manage all service account aspects (create/remove service accounts)
* Manage all ACL aspects (create/remove ACLs)