= pg_get_expr()
:description: The link:https://www.postgresql.org/docs/current/functions-info.html#FUNCTIONS-INFO-CATALOG[pg_get_expr()] is a system catalog information function th

The link:https://www.postgresql.org/docs/current/functions-info.html++#++FUNCTIONS-INFO-CATALOG[pg++_++get++_++expr()] is a system catalog information function that retrieves the internal form of an individual expression, such as the default value for a column.

=== Syntax

There are two available syntax versions of the `pg++_++get++_++expr()` function:

.Version 1
[source,sql]
----
SELECT pg_get_expr('expr_text', relation_oid);
----

.Version 2
[source,sql]
----
SELECT pg_get_expr('expr_text', relation_oid, pretty_bool);
----
Both versions of the `pg++_++get++_++expr()` function return an empty string `""`.

=== Parameters

The following parameters are required to execute this function:

* `expr++_++text`: expression for which you want to obtain the internal representation (can be any string value)
* `relation++_++oid`: OID (Object Identifier) of the table the expression belongs to (integer type)
* `pretty++_++bool`: boolean value determining whether to format the expression in a more human-readable format (`TRUE`) or not (`FALSE`)

=== Example

For the needs of this section, first we will create a sample table named *employees*

[source,sql]
----
CREATE TABLE employees (
    id INT,
    name TEXT,
    salary TEXT
);
----

Then we will get the OID of the table

[source,sql]
----
SELECT oid FROM pg_class WHERE relname = 'employees';
----

[source,sql]
----
 oid
------
 1018
----

As the last step, we will retrieve the internal form for the `salary` column using `pg++_++get++_++expr()` function

[source,sql]
----
-- Version 1
SELECT pg_get_expr('salary', 1018);

-- Version 2
SELECT pg_get_expr('salary', 1018, TRUE);
----

By executing any of the queries above, we will get the following output:

[source,sql]
----
 pg_get_expr
-------------
----
