= Configure AWS PrivateLink in the Cloud Console
:description: Set up AWS PrivateLink in the Redpanda Cloud Console for Serverless clusters.


The Redpanda AWS PrivateLink endpoint service provides secure access to Redpanda Cloud from your own VPC. Traffic over PrivateLink does not go through the public internet because these connections are treated as their own private AWS service. While your VPC has access to the Redpanda VPC, Redpanda cannot access your VPC.

Consider using the endpoint service if you have multiple VPCs and could benefit from a more simplified approach to network management.

[NOTE]
====
* Each client VPC can have one endpoint connected to the PrivateLink service.
* PrivateLink allows overlapping xref:networking:cidr-ranges.adoc[CIDR ranges] in VPC networks.
* PrivateLink does not add extra connection limits. However, VPC peering is limited to 125 connections. See https://aws.amazon.com/privatelink/faqs/[How scalable is AWS PrivateLink?^]
* You control which AWS principals are allowed to connect to the endpoint service.
====

== Requirements

* Your Redpanda Serverless cluster and VPC must be in the same region.
* Use the https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html[AWS CLI] to create a new client VPC or modify an existing one to use the PrivateLink endpoint.

TIP: In Kafka clients, set `connections.max.idle.ms` to a value less than 350 seconds.

== DNS resolution with PrivateLink

include::networking:partial$dns_resolution.adoc[]

== Enable endpoint service for existing clusters

. In the Redpanda Cloud Console, select your https://cloud.redpanda.com/clusters[cluster^], and go to the *Cluster settings* page.
. For AWS PrivateLink, click *Enable*.
. Click *Add* after entering each ARN, and when finished, click *Enable*.
. It may take several minutes for your cluster to update. When the update is complete, the AWS PrivateLink status on the Cluster settings page changes to *Enabled*.

NOTE: For help with issues when enabling PrivateLink, contact https://support.redpanda.com/hc/en-us/requests/new[Redpanda support^].

== Access Redpanda services through VPC endpoint

After you have enabled PrivateLink for your cluster, your connection URLs are available in the *How to Connect* section of the cluster overview in the Redpanda Cloud Console.

include::networking:partial$private-links-access-rp-services-through-vpc.adoc[]

== Test the connection

You can test the connection to the endpoint service from any VM or container in the consumer VPC. If configuring a client isn't possible right away, you can do these checks using `rpk` or cURL:

include::networking:partial$private-links-test-connection.adoc[]

== Disable endpoint service

On the Cluster settings page for the cluster, click *Disable* for PrivateLink. Existing connections are closed after the AWS PrivateLink service is disabled.

NOTE: Disabling private access in Redpanda Cloud does not delete the PrivateLink endpoint in your AWS account. The endpoint remains provisioned and continues to incur charges until you explicitly delete it from your AWS account.

include::shared:partial$suggested-reading.adoc[]

* xref:networking:serverless/aws/privatelink-api.adoc[]
