
[NOTE]
====

* This guide is for configuring GCP Private Service Connect using the Redpanda Cloud UI. To configure and manage Private Service Connect on an existing *public* cluster, you must use the xref:networking:gcp-private-service-connect.adoc[Cloud API for BYOC] or the xref:networking:dedicated/gcp/configure-psc-in-api.adoc[Cloud API for Dedicated].
* The latest version of Redpanda GCP Private Service Connect (available March, 2025) supports AZ affinity. This allows requests from Private Service Connect endpoints to stay within the same availability zone, avoiding additional networking costs. 
* DEPRECATION: The original Redpanda GCP Private Service Connect is deprecated and will be removed in a future release. For more information, see xref:manage:maintenance.adoc#deprecated-features[Deprecated features].
==== 


The Redpanda GCP Private Service Connect service provides secure access to Redpanda Cloud from your own VPC network. Traffic over Private Service Connect does not go through the public internet because these connections are treated as their own private GCP service. While your VPC network has access to the Redpanda VPC network, Redpanda cannot access your VPC network.

Consider using Private Service Connect if you have multiple VPC networks and could benefit from a more simplified approach to network management.

[NOTE]
====
* Each consumer VPC network can have one Private Service Connect endpoint connected to the Redpanda service attachment.
* Private Service Connect allows overlapping xref:networking:cidr-ranges.adoc[CIDR ranges] in VPC networks.
* The number of connections is limited only by your Redpanda usage tier. Private Service Connect does not add extra connection limits. 
* You control from which GCP projects connections are allowed.
====

== Requirements

* Use the https://cloud.google.com/sdk/docs/install[gcloud^] command-line interface (CLI) to create the consumer-side resources, such as a consumer VPC network and forwarding rule, or to modify existing resources to use the Private Service Connect service attachment created for your cluster.
* The consumer VPC network must be in the same region as your Redpanda cluster.

== Enable Private Service Connect for existing clusters

. In the Redpanda Cloud UI, open your https://cloud.redpanda.com/clusters[cluster^], and click **Cluster settings**.
. Under Private Service Connect, click **Enable**. 
ifdef::env-byoc[]
. For xref:get-started:cluster-types/byoc/gcp/vpc-byo-gcp.adoc[BYOVPC clusters], you need a NAT subnet with `purpose` set to `PRIVATE_SERVICE_CONNECT`. You also need to create VPC network firewall rules to allow Private Service Connect traffic. You can use the `gcloud` CLI:
+
NOTE: The firewall rules support up to 20 Redpanda brokers. If you have more than 20 brokers, or for help enabling Private Service Connect, contact https://support.redpanda.com/hc/en-us/requests/new[Redpanda support^].
+
[,bash]
----
gcloud compute networks subnets create <subnet-name> \
    --project=<host-project-id> \
    --network=<shared-vpc-name> \
    --region=<region> \
    --range=<subnet-range> \
    --purpose=PRIVATE_SERVICE_CONNECT
----
+
[,bash]
----
gcloud compute firewall-rules create redpanda-psc-ingress \
  --description="Allow access to Redpanda PSC endpoints" \
  --network="<shared-vpc-name>" \
  --project="<host-project-id>" \
  --direction="INGRESS" \
  --target-tags="redpanda-node" \
  --source-ranges="10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,100.64.0.0/10" \
  --allow="tcp:30181,tcp:30282,tcp:30292,tcp:31004,tcp:31082-31101,tcp:31182-31201,tcp:31282-31301,tcp:32092-32111,tcp:32192-32211,tcp:32292-32311"
----
+
Provide your values for the following placeholders:
+
- `<subnet-name>`: The name of the NAT subnet.
- `<host-project-id>`: The host GCP project ID.
- `<shared-vpc-name>`: The name of the VPC network being used for your Redpanda Cloud cluster.
- `<region>`: The region of the Redpanda Cloud cluster.
- `<subnet-range>`: The CIDR range of the subnet. The mask should be at least `/29`. Each Private Service Connect connection takes up one IP address from the NAT subnet, so the CIDR must be able to accommodate all projects from which connections to the service attachment will be issued.
+
See the GCP documentation for https://cloud.google.com/vpc/docs/configure-private-service-connect-producer#add-subnet-psc[creating a subnet for Private Service Connect^]. 
endif::[]
. For the accepted consumers list, you need the GCP project IDs from which incoming connections will be accepted.
. It may take several minutes for your cluster to update. When the update is complete, the Private Service Connect status in **Cluster settings** changes from **In progress** to **Enabled**.

== Deploy consumer-side resources

For each consumer VPC network, you must complete the following steps to successfully connect to the service attachment and use the Kafka API and other Redpanda services, such as HTTP Proxy.

. In **Cluster settings**, copy the **Service attachment URL** under **Private Service Connect**. Use this URL to create the Private Service Connect endpoint in GCP.

. Get the name of the consumer VPC network and the subnet `<psc-endpoint-subnet>`, where the Private Service Connect endpoint forwarding rule will be created.

. Create a Private Service Connect IP address for the endpoint:
+
[,bash]
----    
gcloud compute addresses create <psc-endpoint-ip-name> --subnet=<psc-endpoint-subnet> --addresses=<psc-endpoint-ip> --region=<region>
----

. Create the Private Service Connect endpoint forwarding rule:
+
[,bash]
----    
gcloud compute forwarding-rules create <psc-endpoint-forwarding-rule-name> --region=<region> --network=<consumer-vpc-name> --address=<psc-endpoint-ip> --target-service-attachment=<rp-psc-service-attachment-url>
----

. Create firewall rules allowing egress traffic to the Private Service Connect endpoint:
+
[,bash]
----
gcloud compute firewall-rules create redpanda-psc-egress \
  --description="Allow access to Redpanda PSC endpoint" \
  --network="<consumer-vpc-name>" \
  --direction="EGRESS" \
  --destination-ranges=<psc-endpoint-ip> \
  --allow="tcp:443,tcp:30081,tcp:30282,tcp:30292,tcp:32092-32141,tcp:35082-35131,tcp:32192-32241,tcp:35182-35231,tcp:32292-32341,tcp:35282-35331"
----

. Create a private DNS zone. Use the cluster **DNS zone** value as the DNS name:
+
[,bash]
----
gcloud dns managed-zones create <dns-zone-name> \
  --project=<gcp-project-id> \
  --description="Redpanda Private Service Connect DNS zone" \
  --dns-name="<dns-zone-from-the-ui>" \
  --visibility="private" \
  --networks="<consumer-vpc-name>"
----

. In the newly-created DNS zone, create a wildcard DNS record using the cluster **DNS record** value:
+
[,bash]
----
gcloud dns record-sets create '*.<dns-zone-from-the-ui>' \
  --project=<gcp-project-id> \
  --zone="<dns-zone-name>" \
  --type="A" \
  --ttl="300" \
  --rrdatas="<psc-endpoint-ip>"
----

== Access Redpanda services through Private Service Connect endpoint

After you have enabled Private Service Connect for your cluster, your connection URLs are available in the *How to Connect* section of the cluster overview in the Redpanda Cloud UI.

include::networking:partial$private-links-access-rp-services-through-vpc.adoc[]

== Test the connection

You can test the connection to the service attachment from any VM or container in the consumer VPC network. If configuring a client isn't possible right away, you can do these checks using `rpk` or cURL:

include::networking:partial$private-links-test-connection.adoc[]

== Disable Private Service Connect

In **Cluster settings**, click **Disable**. Existing connections are closed after GCP Private Service Connect is disabled. To connect using Private Service Connect again, you must re-enable the service.