
== Deploy consumer-side resources

For each consumer VPC network, you must complete the following steps to successfully connect to the service attachment and use the Kafka API and other Redpanda services, such as HTTP Proxy.

. In **Cluster settings**, copy the **DNS zone** and **Service attachment URL** under **Private Service Connect**. Use this URL to create the Private Service Connect endpoint in GCP.

. Get the name of the consumer VPC network and the subnet `<psc-endpoint-subnet>`, where the Private Service Connect endpoint forwarding rule will be created.

. Create a Private Service Connect IP address for the endpoint:
+
[,bash]
----    
gcloud compute addresses create <psc-endpoint-ip-name> --subnet=<psc-endpoint-subnet> --addresses=<psc-endpoint-ip> --region=<region>
----

. Create the Private Service Connect endpoint forwarding rule:
+
NOTE: If you have enabled global access when creating the cluster, you must also include the `--allow-psc-global-access` flag to configure the endpoint to accept client connections from different regions.
+
[,bash]
----    
gcloud compute forwarding-rules create <psc-endpoint-forwarding-rule-name> --region=<region> --network=<consumer-vpc-name> --address=<psc-endpoint-ip> --target-service-attachment=<rp-psc-service-attachment-url>
----

. Create firewall rules allowing egress traffic to the Private Service Connect endpoint:
+
[,bash]
----
gcloud compute firewall-rules create redpanda-psc-egress \
  --description="Allow access to Redpanda PSC endpoint" \
  --network="<consumer-vpc-name>" \
  --direction="EGRESS" \
  --destination-ranges=<psc-endpoint-ip> \
  --allow="tcp:443,tcp:30081,tcp:30282,tcp:30292,tcp:32092-32141,tcp:35082-35131,tcp:32192-32241,tcp:35182-35231,tcp:32292-32341,tcp:35282-35331"
----

. Create a private DNS zone. Use the cluster **DNS zone** value as the DNS name:
+
[,bash]
----
gcloud dns managed-zones create <dns-zone-name> \
  --project=<gcp-project-id> \
  --description="Redpanda Private Service Connect DNS zone" \
  --dns-name="<dns-zone-from-the-ui>" \
  --visibility="private" \
  --networks="<consumer-vpc-name>"
----

. In the newly-created DNS zone, create a wildcard DNS record using the cluster **DNS record** value:
+
[,bash]
----
gcloud dns record-sets create '*.<dns-zone-from-the-ui>' \
  --project=<gcp-project-id> \
  --zone="<dns-zone-name>" \
  --type="A" \
  --ttl="300" \
  --rrdatas="<psc-endpoint-ip>"
----

== Access Redpanda services through Private Service Connect endpoint

After you have enabled Private Service Connect for your cluster, your connection URLs are available in the *How to Connect* section of the cluster overview in the Redpanda Cloud UI.

include::networking:partial$private-links-access-rp-services-through-vpc.adoc[]

== Test the connection

You can test the Private Service Connect connection from any VM or container in the consumer VPC. If configuring a client isn't possible right away, you can do these checks using `rpk` or curl:

include::networking:partial$private-links-test-connection.adoc[]