= Redpanda Connect Cloud Quickstart
:description: Learn how to quickly start working with Redpanda Connect in Redpanda Cloud.

Learn how to build, run, and update a data pipeline on a cluster using Redpanda Connect.

This quickstart introduces you to Redpanda Connect fully integrated into the Redpanda Cloud UI. Using a single YAML configuration file, Redpanda Connect lets you quickly build, run, and seamlessly update streaming data pipelines. No third-party connectors are required. 

== Prerequisites

A Redpanda XXXXXX account.

== Before you start

Create the cluster, topic, and user you need to build and run your data pipeline.

. Log in to Redpanda Cloud.
. On the **Clusters** page, click **Create cluster**, then click **Create XXXXX cluster**.
For cluster settings, enter connect-quickstart for the cluster name. Use default values for the remaining properties and click Next.
On the Networking page, use the default Public connection type, and click Create.
	Wait while your cluster is created.
Go to the Topics page, click Create topic and enter connect-output for the topic name. Use default values for the remaining properties and click Create.
Go to the Security page, and click Create user. Enter the username connect. Use the default values for the remaining properties and click Create. Remember to take a note of your password.
Stay on the Access control page and click the ACLs tab.
Select the connect user you have just created. Click Allow all operations and then OK. 
Finally, go to the Overview page and click the Kafka API tab. 
Copy the bootstrap server URL into a text file. You will need it for the next steps.


