= Configure GCP Private Service Connect with the Cloud API
:description: Set up GCP Private Service Connect to securely access Redpanda Cloud.
:env-dedicated: true

include::networking:partial$psc-api.adoc[]

== Create a new cluster with Private Service Connect

. In the https://cloud.redpanda.com/[Redpanda Cloud UI], go to **Resource groups** and select the resource group in which you want to create a cluster.
+
Copy and store the resource group ID (UUID) from the URL in the browser.
+
[,bash]
----
export RESOURCE_GROUP_ID=<uuid>
----

. Make a request to the link:/api/doc/cloud-controlplane/operation/operation-networkservice_createnetwork[`POST /v1/networks`] endpoint to create a network.
+
[,bash]
----
NETWORK_POST_BODY=`cat << EOF
{
    "network": {
        "cloud_provider": "CLOUD_PROVIDER_GCP",
        "cluster_type": "TYPE_DEDICATED",
        "name": "<shared-vpc-name>",
        "resource_group_id": "$RESOURCE_GROUP_ID",
        "region": "<region>"
    }
}
EOF`

curl -vv -X POST \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $AUTH_TOKEN" \
-d "$NETWORK_POST_BODY" $PUBLIC_API_ENDPOINT/v1/networks
----
+
Replace the following placeholder variables for the request body:
+
--
- `<shared-vpc-name>`: The name for the network. 
- `<region>`: The GCP region where the network will be created.
- `<network-gcp-project-id>`: The ID of the GCP project where your VPC is created.
- `<network-name>`: The name of your VPC.
- `<management-bucket>`: The name of the Google Storage bucket you created for the cluster.
--


. Store the network ID (`metadata.network_id`) returned in the response to the Create Network request.
+
[,bash]
----
export NETWORK_ID=<metadata.network_id>
----

. Make a request to the link:/api/doc/cloud-controlplane/operation/operation-clusterservice_createcluster[`POST /v1/clusters`] endpoint to create a Redpanda Cloud cluster with Private Service Connect enabled.
+
[,bash]
----
export CLUSTER_POST_BODY=`cat << EOF
{
    "cluster": {
        "cloud_provider": "CLOUD_PROVIDER_GCP",
        "connection_type": "CONNECTION_TYPE_PRIVATE",
        "type": "TYPE_DEDICATED",
        "name": "<cluster-name>",
        "resource_group_id": "$RESOURCE_GROUP_ID",
        "network_id": "$NETWORK_ID",
        "region": "<region>",
        "zones": <zones>,
        "throughput_tier": "<throughput-tier>",
        "redpanda_version": "<redpanda-version>",
        "gcp_private_service_connect": {
            "enabled": true,
            "consumer_accept_list": <consumer-accept-list>
        }
    }
}
EOF`

curl -vv -X POST \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $AUTH_TOKEN" \
-d "$CLUSTER_POST_BODY" $PUBLIC_API_ENDPOINT/v1/clusters
----
+
--
- `<cluster-name>`: Provide a name for the new cluster.
- `<region>`: Choose a GCP region where the network will be created.
- `<zones>`: Provide the list of GCP zones where the brokers will be deployed. Format: `["<zone 1>", "<zone 2>", "<zone N>"]`
- `<throughput-tier>`: Choose a Redpanda Cloud cluster tier. For example, `tier-1-gcp-v2-x86`.
- `<redpanda-version>`: Choose the Redpanda Cloud version.
- `<consumer-accept-list>`: The list of IDs of GCP projects from which Private Service Connect connection requests are accepted. Format: `[{"source": "<GCP-project-ID-1>"}, {"source": "<GCP-project-ID-2>"}, {"source": "<GCP-project-ID-N>"}]`
--

== Enable Private Service Connect on an existing cluster

[CAUTION]
====
As soon as Private Service Connect is available on your VPC, all communication on existing Redpanda bootstrap server and broker ports is interrupted due to the change on the private DNS resolution. Make sure all applications running in your VPC are ready to start using the corresponding Private Service Connect ports. 

To avoid disruption, consider using a staged approach. See: xref:networking:dedicated/gcp/vpc-peering-gcp.adoc#switch-from-vpc-peering-to-private-service-connect[Switch from VPC peering to Private Service Connect].
====

. In the Redpanda Cloud UI, go to the cluster overview and copy the cluster ID from the **Details** section.
+
[,bash]
----
export CLUSTER_ID=<cluster-id>
----


. Make a link:/api/doc/cloud-controlplane/operation/operation-clusterservice_updatecluster[`PATCH /v1/clusters/{cluster.id}`] request to update the cluster to enable Private Service Connect.
+
[,bash]
----
CLUSTER_PATCH_BODY=`cat << EOF
{
    "gcp_private_service_connect": {
        "enabled": true,
         "consumer_accept_list": <consumer-accept-list>
    }
}
EOF`
curl -v -X PATCH \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $AUTH_TOKEN" \
-d "$CLUSTER_PATCH_BODY" $PUBLIC_API_ENDPOINT/v1/clusters/$CLUSTER_ID
----
+
Replace the following placeholder:
+
`<consumer-accept-list>`: A JSON list specifying the projects from which incoming connections will be accepted. All other sources are rejected. For example, `[{"source": "consumer-project-ID-1"},{"source": "consumer-project-ID-2"}]`.
+
Wait for the cluster to apply the new configuration (around 15 minutes). The Private Service Connect attachment is available when the cluster update is complete. To monitor the service attachment creation, run the following `gcloud` command with the project ID:
+
[,bash]
----
gcloud compute service-attachments list --project '<service-project-id>'
----


include::networking:partial$psc-ui.adoc[]

== Disable Private Service Connect

Make a link:/api/doc/cloud-controlplane/operation/operation-clusterservice_updatecluster[`PATCH /v1/clusters/{cluster.id}`] request to update the cluster to disable Private Service Connect.

[,bash]
----
CLUSTER_PATCH_BODY=`cat << EOF
{
    "gcp_private_service_connect": {
        "enabled": false
    }
}
EOF`
curl -v -X PATCH \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $AUTH_TOKEN" \
-d "$CLUSTER_PATCH_BODY" $PUBLIC_API_ENDPOINT/v1/clusters/$CLUSTER_ID
----