= Configure Cluster Properties
:description: Learn how to configure cluster properties to enable and manage features.

Cluster configuration properties are set to their default values and are automatically replicated across all brokers. You can use cluster properties to enable and manage features such as xref:manage:iceberg/about-iceberg-topics.adoc[Iceberg topics], xref:develop:data-transforms/index.adoc[data transforms], and xref:manage:audit-logging.adoc[audit logging].

For a complete list of the cluster properties available in Redpanda Cloud, see xref:reference:properties/cluster-properties.adoc[Cluster Configuration Properties] and xref:reference:properties/object-storage-properties.adoc[Object Storage Properties].

NOTE: Some properties are read-only and cannot be changed. For example, `cluster_id` is a read-only property that is automatically set when the cluster is created. 

== Prerequisites

Clusters must be running Redpanda version 25.1.2 or later to configure cluster properties. You can find the version on your cluster's Overview page in the Redpanda Cloud UI.

== Limitations

Cluster properties are supported on BYOC and Dedicated clusters running on AWS and GCP. 

- They are not available on BYOC and Dedicated clusters running on Azure.
- They are not available on Serverless clusters. 


== Set cluster configuration properties 

You can set cluster configuration properties using the `rpk` command-line tool or the Cloud API.

[tabs]
====
`rpk`::
+
--
Use `rpk cluster config` to set cluster properties. 

For example, to enable audit logging, set xref:reference:properties/cluster-properties.adoc#audit_enabled[`audit_enabled`] to `true`:

[source,bash]
----
rpk cluster config set audit_enabled true
----

To set a cluster property with a secret, you must use the following notation:

[source,bash]
----
rpk cluster config set iceberg_rest_catalog_client_secret ${secrets.<secret-name>}
----

NOTE: Some properties require a rolling restart, and it can take several minutes for the update to complete. The `rpk cluster config set` command returns the operation ID.  


--
Cloud API::
+
--
Use the Cloud API to set cluster properties:

* Create a cluster by making a xref:api:ROOT:cloud-controlplane-api.adoc#post-/v1/clusters[`POST /v1/clusters`] request. Edit `cluster_configuration` in the request body with a key-value pair for `custom_properties`.

* Update a cluster by making a xref:api:ROOT:cloud-controlplane-api.adoc#patch-/v1/clusters/-cluster.id-[`PATCH /v1/clusters/{cluster.id}`] request, passing the cluster ID as a parameter. Include the properties to update in the request body.

For example, to set xref:reference:properties/cluster-properties.adoc#audit_enabled[`audit_enabled`] to `true`:

[source,bash]
----
# Store your cluster ID in a variable.
export RP_CLUSTER_ID=<cluster-id>

# Retrieve a Redpanda Cloud access token.
export RP_CLOUD_TOKEN=`curl -X POST "https://auth.prd.cloud.redpanda.com/oauth/token" \
    -H "content-type: application/x-www-form-urlencoded" \
    -d "grant_type=client_credentials" \
    -d "client_id=<client-id>" \
    -d "client_secret=<client-secret>"`

# Update your cluster configuration to enable audit logging.
curl -H "Authorization: Bearer ${RP_CLOUD_TOKEN}" -X PATCH \
  "https://api.cloud.redpanda.com/v1/clusters/${RP_CLUSTER_ID}" \
 -H 'accept: application/json'\
 -H 'content-type: application/json' \
 -d '{"cluster_configuration":{"custom_properties": {"audit_enabled":true}}}'
----

The xref:api:ROOT:cloud-controlplane-api.adoc#patch-/v1/clusters/-cluster.id-[`PATCH /clusters/{cluster.id}`] request returns the ID of a long-running operation. You can check the status of the operation by polling the xref:api:ROOT:cloud-controlplane-api.adoc#get-/v1/operations/-id-[`GET /operations/\{id}`] endpoint.

To set a cluster property with a secret, you must use the following notation with the secret name:

[source,bash]
----
curl -H "Authorization: Bearer <token>" -X PATCH \
"https://api.cloud.redpanda.com/v1/clusters/<cluster-id>" \
  -H 'accept: application/json'\
  -H 'content-type: application/json' \
  -d '{"cluster_configuration": {
        "custom_properties": {
            "iceberg_rest_catalog_client_secret": "${secrets.<secret-name>}"
            }
        }
    }'
----

NOTE: Some properties require a rolling restart for the update to take effect. This triggers a xref:manage:api/cloud-byoc-controlplane-api.adoc#lro[long-running operation] that can take several minutes to complete.

--
====

== View cluster property values

You can see the value of a cluster configuration property using `rpk` or the Cloud API.

[tabs]
====
`rpk`::
+
--
Use `rpk cluster config get` to view the current cluster property value. 

For example, to view the current value of xref:reference:properties/cluster-properties.adoc#audit_enabled[`audit_enabled`], run:

[source,bash]
----    
rpk cluster config get audit_enabled
----    


--
Cloud API::
+  
--
Use the Cloud API to get the current configuration property values for a cluster.

Make a xref:api:ROOT:cloud-controlplane-api.adoc#get-/v1/clusters/-id-[`GET /clusters/{cluster.id}`] request, passing the cluster ID as a parameter. The response body contains the current `computed_properties` values. For example, to get the current value of xref:reference:properties/cluster-properties.adoc#audit_enabled[`audit_enabled`]:

[source,bash]
----
# Store your cluster ID in a variable.
export RP_CLUSTER_ID=<cluster-id>

# Retrieve a Redpanda Cloud access token.
export RP_CLOUD_TOKEN=`curl -X POST "https://auth.prd.cloud.redpanda.com/oauth/token" \
    -H "content-type: application/x-www-form-urlencoded" \
    -d "grant_type=client_credentials" \
    -d "client_id=<client-id>" \
    -d "client_secret=<client-secret>"`

# Get your cluster configuration property values.
curl -H "Authorization: Bearer ${RP_CLOUD_TOKEN}" -X GET \
  "https://api.cloud.redpanda.com/v1/clusters/${RP_CLUSTER_ID}" \
 -H 'accept: application/json'\
 -H 'content-type: application/json' \
----


--
====

== Suggested reading

* xref:manage:rpk/intro-to-rpk.adoc[]
* xref:manage:api/cloud-api-overview.adoc[Redpanda Cloud API Overview]
* xref:manage:api/cloud-api-quickstart.adoc[Redpanda Cloud API Quickstart]