= Configure Cluster Properties
:description: Learn how to configure cluster properties to enable and manage additional features.

Redpanda cluster configuration properties are automatically set to the default values and are replicated across all brokers. 

Some properties can be configured at either the cluster level or the topic level, such as `retention_bytes` (cluster-level) and `retention.bytes` (topic-level). Topic-level properties override cluster-level properties. Most Redpanda configuration properties are cluster properties.

You can edit certain cluster configuration properties with the Cloud API. For example, you can enable and manage Iceberg topics, data transforms, audit logging, and server-side schema ID validation. 

For information about using the Cloud API, see:

* xref:manage:api/cloud-api-overview.adoc[Redpanda Cloud API Overview]
* xref:manage:api/cloud-api-quickstart.adoc[Redpanda Cloud API Quickstart]

== Limitations

Cluster configuration with the Cloud API is supported on BYOC and Dedicated clusters running on AWS and GCP. 

- It is not available on Serverless clusters. 
- It is not available on BYOC and Dedicated clusters running on Azure.

== Set cluster configuration properties

You can set cluster configuration properties when you create a cluster, or you can edit an existing cluster.

* Create a cluster by making a xref:api:ROOT:cloud-controlplane-api.adoc#post-/v1/clusters[`POST /v1/clusters`] request.

* Update a cluster by making a xref:api:ROOT:cloud-controlplane-api.adoc#patch-/v1/clusters/-cluster.id-[`PATCH /v1/clusters/{cluster.id}`] request.

To set a cluster property, edit `cluster_configuration` in the request body with a key-value pair for `custom_properties`.

For a complete list of the cluster configuration properties you can edit in Redpanda Cloud, see xref:reference:properties/cluster-properties.adoc[Cluster Configuration Properties].

NOTE: Some properties require a cluster restart for updates to take effect. This triggers a xref:manage:api/cloud-byoc-controlplane-api.adoc#lro[long-running operation] that can take several minutes to complete.

