= Configure Cluster Properties
:description: Learn how to configure cluster properties to enable and manage features.

Cluster configuration properties are set to their default values and automatically replicated across all brokers. You can use cluster properties to enable and manage features such as xref:manage:iceberg/about-iceberg-topics.adoc[Iceberg topics], xref:develop:data-transforms/index.adoc[data transforms], and xref:manage:audit-logging.adoc[audit logging].

For a complete list of the cluster properties you can set in Redpanda Cloud, see xref:reference:properties/cluster-properties.adoc[Cluster Configuration Properties].

== Limitations

Cluster configuration is supported on BYOC and Dedicated clusters running on AWS and GCP. 

- It is not available on Serverless clusters. 
- It is not available on BYOC and Dedicated clusters running on Azure.

== Set cluster configuration properties 

You can set cluster configuration properties using the `rpk` command-line tool or the Cloud API.

[tabs]
======
`rpk`::
+
--
Use `rpk cluster config` to set cluster properties. 

For example, to enable data transforms, set xref:reference:properties/cluster-properties.adoc#data_transforms_enabled[`data_transforms_enabled`] to `true`:

[source,bash]
----
rpk cluster config set data_transforms_enabled true
----

NOTE: The `rpk cluster config set` command returns the operation ID. Cluster configuration operations can take up to ten minutes to complete. 

--
Cloud API::
+
--
Use the Cloud API to set cluster properties:

* Create a cluster by making a xref:api:ROOT:cloud-controlplane-api.adoc#post-/v1/clusters[`POST /v1/clusters`] request. Edit `cluster_configuration` in the request body with a key-value pair for `custom_properties`.

* Update a cluster by making a xref:api:ROOT:cloud-controlplane-api.adoc#patch-/v1/clusters/-cluster.id-[`PATCH /v1/clusters/{cluster.id}`] request, passing the cluster ID as a parameter. Include the properties to update in the request body.

For example, to set xref:reference:properties/cluster-properties.adoc#data_transforms_enabled[`data_transforms_enabled`] to `true`:

[source,bash]
----
# Store your cluster ID in a variable
export RP_CLUSTER_ID=<cluster-id>

# Retrieve a Redpanda Cloud access token
export RP_CLOUD_TOKEN=`curl -X POST "https://auth.prd.cloud.redpanda.com/oauth/token" \
    -H "content-type: application/x-www-form-urlencoded" \
    -d "grant_type=client_credentials" \
    -d "client_id=<client-id>" \
    -d "client_secret=<client-secret>"`

# Update your cluster configuration to enable data transforms.
curl -H "Authorization: Bearer ${RP_CLOUD_TOKEN}" -X PATCH \
  "https://api.cloud.redpanda.com/v1/clusters/${RP_CLUSTER_ID}" \
 -H 'accept: application/json'\
 -H 'content-type: application/json' \
 -d '{"cluster_configuration":{"custom_properties": {"data_transforms_enabled":true}}}'
----

The xref:api:ROOT:cloud-controlplane-api.adoc#patch-/v1/clusters/-cluster.id-[`PATCH /clusters/{cluster.id}`] request returns the ID of a long-running operation. The operation may take up to ten minutes to complete. You can check the status of the operation by polling the xref:api:ROOT:cloud-controlplane-api.adoc#get-/v1/operations/-id-[`GET /operations/\{id}`] endpoint.


--
======

== Suggested reading

* xref:manage:rpk/intro-to-rpk.adoc[]
* xref:manage:api/cloud-api-overview.adoc[Redpanda Cloud API Overview]
* xref:manage:api/cloud-api-quickstart.adoc[Redpanda Cloud API Quickstart]