Redpanda Cloud provides the following predefined roles: <<Reader,Reader>>, <<Writer,Writer>>, and <<Admin,Admin>>.

=== Reader

The Reader role grants permission to view all resources. This includes:

* View all networks and clusters (Serverless, BYOC, and Dedicated).
* View all cluster aspects (ACLs, service accounts, quotas).
* View all topic aspects (messages, configs, partitions, using search filters).
* View all consumer group aspects (consumer groups, group offsets, and lags).
* View all schema registry aspects (registered schemas with their contents).
* View all Kafka Connect aspects (list configured clusters and their connectors, including the status and connector configurations).
* This does not include permission to view the list of users.

=== Writer

The Writer role grants all permissions that come with the Reader role and additionally includes:

* Manage all topic aspects, such as create topics, edit topic configurations, delete topics, and publish and delete topic records.
* Manage all consumer group aspects, such as edit group offsets and delete group offsets.
* Manage all Kafka Connect aspects, such as create/update/delete and start/pause/stop Kafka Connect.
* This does not include permission to create/remove ACLs and service accounts.

=== Admin

The Admin role grants all permissions that come with the Writer role and additionally includes:

* Manage all service account aspects (create/remove service accounts).
* Manage all ACL aspects (create/remove ACLs).
