= Upgrades and Maintenance
:description: Learn how Redpanda Cloud manages maintenance operations.

As a fully-managed service, the Redpanda Cloud glossterm:control plane[] handles all maintenance operations, such as upgrades to your software and infrastructure.

Redpanda runs maintenance operations on clusters in a rolling fashion, accompanied by a series of health checks, so there is no disruption to the availability of your service. As part of the Kafka protocol, recycling nodes triggers client connections to be restarted. All mainstream client libraries support automatic reconnections when a restart occurs.

== Maintenance windows

Redpanda Cloud may run maintenance operations on any day, at any time. You can override this default and schedule a specific maintenance window on your cluster's *Cluster settings* page. 

If you select a *Scheduled* maintenance window, then Redpanda Cloud runs operations on the day and time specified. Maintenance windows typically take six hours. All operations begin during your maintenance window, but some operations may complete after the window closes. All times are in Coordinated Universal Time (UTC).

TIP: Redpanda Cloud maintenance cycles always start on Tuesdays. Clusters scheduled for maintenance on Tuesdays are updated first, and clusters scheduled on Mondays are updated last. Keep this in mind when sequencing updates for multiple clusters.

== Minor upgrades

During your defined maintenance window, Redpanda Cloud runs minor upgrades. Minor upgrades include standard Redpanda state changes that clients handle gracefully, such as leader elections. 


[cols="1,4", options="header"]
|===
| Category
| Details

| Impact
| Minimal.

| Examples
a|
* Patches to known issues. +
* Cluster rolling restart.  +
* Upgrade Redpanda to a fully backward-compatible version. 

| Frequency
| Minor upgrades could happen multiple times a day.

| Communication
| Prior communication happens only if necessary. +

There could be email notifications, updated documentation, release notes, or communication from your Redpanda account team.

| Timing
| At Redpanda's discretion during your defined maintenance window.
|===

== Major upgrades

Major upgrades may require code changes to customer applications, such as Kafka clients or API integrations. 

[cols="1,4", options="header"]
|===
| Category
| Details

| Impact
| Potentially large.

| Examples
a|
* Upgrade Kafka to a version that is not fully backward-compatible with the previous version.
* Update an API version.
* Security update that materially changes cluster or client throughput.

| Frequency
| Rare.

| Communication
| Email notifications may be sent to registered users with details about the change and available options. +

There could be updated documentation, release notes, and communication from your Redpanda account team.

| Timing
| Major upgrades may be coordinated with customers, but the final date set by Redpanda is not negotiable.
|===

== Deprecations

Deprecations indicate future removal of features that you can currently use. There is no guarantee of equivalent functionality in new versions. Deprecations could be included in major upgrades. 


[cols="1,4", options="header"]
|===
| Category
| Details

| Impact
| Potentially large, if you depend on the feature being deprecated.

| Examples
a|
* Remove a feature from the UI. +
* Shut down an API version. +
* Remove a connector as an option.

| Frequency
| Rare.

| Communication
| Email notifications may be sent to registered users with details about the change and available alternatives. +

There could be updated documentation, release notes, and communication from your Redpanda account team.

| Timing
| At Redpanda's discretion.
|===

See also: link:/api/doc/cloud-controlplane/topic/topic-deprecation-policy[Cloud API Deprecation Policy].


=== Deprecated features


[cols="1,2,3", options="header"]
|===
| Deprecated in | Feature | Details

| November 2025 | Subset of TLS v1.2 cipher suites | The following TLSv1.2 cipher suites will no longer be used for managed services such as Schema Registry, HTTP Proxy, and Kafka API:

- AES128-GCM-SHA256
- AES256-GCM-SHA384
- ECDHE-RSA-AES128-SHA
- AES128-SHA
- AES128-CCM
- ECDHE-RSA-AES256-SHA
- AES256-SHA
- AES256-CCM

| May 2025 | Cloud API beta versions a| The Cloud Control Plane API versions v1beta1 and v1beta2, and Data Plane API versions v1alpha1 and v1alpha2 are deprecated. These Cloud API versions will be removed in a future release and are not recommended for use. 

The deprecation timeline is: 

- Announcement date: May 27, 2025
- End-of-support date: November 28, 2025
- Retirement date: May 28, 2026

See the link:/api/doc/cloud-controlplane/topic/topic-deprecation-policy[Cloud API Deprecation Policy] for more information.
| March 2025 | Serverless Standard | For a better customer experience, the Serverless Standard and Serverless Pro products merged into a single offering. Serverless Standard is deprecated.  

All existing Serverless Standard clusters will be migrated to the new xref:get-started:cluster-types/serverless.adoc[Serverless] platform (with higher usage limits, 99.9% SLA, and additional regions) on August 31, 2025.

Retirement date: August 30, 2025

| February 2025 | Private Service Connect v1 | The Redpanda xref:networking:gcp-private-service-connect.adoc[GCP Private Service Connect v2] service provides the ability to allow requests from Private Service Connect endpoints to stay within the same availability zone, avoiding additional networking costs. 

To check the version of your Private Service Connect attachment, run: 

`gcloud compute service-attachments list --filter="region:( ${GCP_REGION} )"`

The attachment name should show the suffix `psc2`; for example, `projects/my-gcp-project/regions/us-west1/serviceAttachments/rp-d0f0mqk5ktzznib2j9g-psc2`. If the name shows the suffix `psc`, then you have the deprecated version. To upgrade, contact https://support.redpanda.com/hc/en-us/requests/new[Redpanda Support^].
|===
