= COPY TO STDOUT
:description: The COPY TO STDOUT command is used to export data directly from a table to the client.

The `COPY TO STDOUT` command is used to export data directly from a table to the client. This approach allows for data transfer by sending the data directly to the client, eliminating the need for server-side file operations.

== Syntax

The basic syntax for using `COPY TO STDOUT` is:

[source,sql]
----
COPY table_name TO STDOUT;
----

Parameters:

* `table++_++name`: The table from which the data will be exported.
* `stdout`: Indicates that the data will be sent to the standard output (client application).

[NOTE]
====
- *Format*: Only .csv is supported
 - *Delimiter*: For CSV format, the default delimiter is a comma (,)
====

== Examples

=== Step 1. Create the Table

[arabic]
. Create the table and insert some data into it.

[source,sql]
----
CREATE TABLE book_inventory (
    title TEXT,
    copies_available INT
);
INSERT INTO book_inventory (title, copies_available) VALUES
('To Kill a Mockingbird', 5),
('1984', 8),
('The Great Gatsby', 3),
('Moby Dick', 2),
('War and Peace', 4);
----

[arabic, start=2]
. Upon successful creation, you should see the output below:

[source,sql]
----
CREATE
INSERT 0 5
----

=== Step 2. Start the Export Operation

[arabic]
. Run the `COPY TO STDOUT` command to export the data from the `book++_++inventory` table:

[source,sql]
----
COPY book_inventory TO STDOUT;
----

[arabic, start=2]
. You will get the output with the table values, which you can use to create or copy into a CSV file:

[source,sql]
----
"To Kill a Mockingbird",5
1984,8
"The Great Gatsby",3
"Moby Dick",2
"War and Peace",4
----
