= COPY TO with HEADER
:description: When you export data from a table to a CSV file using the COPY TO command, you can include or skip the header.
:page-topic-type: reference

== Overview

When you export data from a table to a CSV file using the `COPY TO` command, you can include or skip the header. Redpanda SQL provides options for handling headers: `HEADER OFF` and `HEADER ON`.

== Syntax

[source,sql]
----
COPY table_name TO 'file_path' (Header_Syntax);
----

Parameters in the syntax include:

* `table_name`: The table containing the data to export.
* `file_path`: The CSV file location where the data is saved.
* `Header_Syntax`: The specified header options.

== Header options

* *HEADER OFF*
+
Does not include the header row in the CSV file. The available syntax is:
+
[source,none]
----
HEADER OFF
HEADER FALSE
HEADER 0
----
+
NOTE: This option is the default behavior if `HEADER` is not provided.

* *HEADER ON*
+
Includes the header row with column names in the CSV file. The available syntax is:
+
[source,none]
----
HEADER ON
HEADER TRUE
HEADER 1
----

== Examples

The following examples use a table mapped to a Redpanda topic through a catalog. For information on setting up catalogs and tables, see xref:reference:sql/sql-statements/create-table.adoc[CREATE TABLE].

=== HEADER OFF

Export a table without column headers:

[source,sql]
----
COPY my_catalog=>personal_details TO '/path/to/personalinfo.csv';
----

The data in the table is copied directly to the file without a header row:

[source,text]
----
1,'Mark','Wheeler','M'
2,'Tom','Hanks','M'
3,'Jane','Hopper','F'
4,'Emily','Byers','F'
5,'Lucas','Sinclair','M'
----

TIP: To include headers, use the `HEADER ON` option.

=== HEADER ON

Export a table with column headers:

[source,sql]
----
COPY my_catalog=>personal_details TO '/path/to/personalinfo.csv' (HEADER ON);
----

The header from the table is included in the CSV file:

[source,none]
----
id,first_name,last_name,gender
1,'Mark','Wheeler','M'
2,'Tom','Hanks','M'
3,'Jane','Hopper','F'
4,'Emily','Byers','F'
5,'Lucas','Sinclair','M'
----
