= COPY TO with NULL
:description: A NULL value indicates that the value does not exist in the database.
:page-topic-type: reference

A `NULL` value indicates that the value does not exist in the database. In Redpanda SQL, you can use the `NULL` option in the `COPY TO` statement to specify a string that replaces `NULL` values when copying data from the table to a CSV file.

== Syntax

[source,sql]
----
COPY table_name TO 'file_path' (NULL 'replacement_string');
----

Parameters in the syntax include:

* `table_name`: The table containing the data to export.
* `file_path`: A CSV file location where the data is saved.
* `NULL 'replacement_string'`: The specified string that replaces NULL values in the exported CSV file. The default value is `' '`.

== Example

The following examples use a table mapped to a Redpanda topic through a catalog. For information on setting up catalogs and tables, see xref:reference:sql/sql-statements/create-table.adoc[CREATE TABLE].

Export a table with `NULL` values replaced by an empty string:

[source,sql]
----
COPY my_catalog=>example_table TO '/path/to/exampleexport.csv' (NULL '');
----

The `NULL` values in the table are replaced with the empty string in the CSV file:

[source,text]
----
1,John,25,"New York"
2,Alice,,"Chicago"
3,Bob,30,
----

TIP: You can specify another string to replace the null value, such as `blank`, `empty`, or `invalid`.
