= Export data to a CSV file
:description: Exporting data from Redpanda SQL to a CSV file using the COPY TO command.
:page-topic-type: reference

Exporting data from Redpanda SQL to a CSV file can be accomplished using the `COPY TO` command. This guide outlines the methods for exporting data, including specifying delimiters, handling headers, and controlling null value representation.

== Syntax

[source,sql]
----
COPY table_name (column_name) TO {'file_path' | STDOUT} WITH (option, ...);
----

== Parameters

* `table_name`: Existing table from which the data is exported.
* `column_name`: Optional list of columns to export. If omitted, all columns are exported.
* `TO`: Destination for the exported data.
** `file_path`: Path to the CSV file where the data is written.
** `STDOUT`: Exports the data to the standard output stream.
* `option`: Available options:
** *FORMAT*: Output format (currently only CSV is supported).
** *DELIMITER*: Delimiter character represented as a single-quote string literal. By default, this function uses commas as the delimiter.
** *NULL*: String to use for representing NULL values (for example, `NULL 'unknown'`).
** *HEADER*: Boolean value indicating whether to include a header row with column names. Values can be `TRUE` or `FALSE`, with default set to `FALSE`.
** *Endpoint*: Object-based storage credentials.

== Examples

The following examples use a table mapped to a Redpanda topic through a catalog. For information on setting up catalogs and tables, see xref:reference:sql/sql-statements/create-table.adoc[CREATE TABLE].

=== Export data to a local CSV file

Export data from a table to a CSV file named `film_export.csv`, including a header row and using a semicolon as the delimiter:

[source,sql]
----
COPY my_catalog=>film TO '/path/to/film_export.csv' WITH (FORMAT CSV, HEADER TRUE, DELIMITER ';');
----

The contents of `film_export.csv`:

[source,text]
----
public.film.title;public.film.length;public.film.rating
"ATTRACTION NEWTON";83;PG-13
"CHRISTMAS MOONSHINE";150;NC-17
"DANGEROUS UPTOWN";121;PG
"KILL BROTHERHOOD";54;G
"HALLOWEEN NUTS";47;PG-13
"HOURS RAGE";122;NC-17
"PIANIST OUTFIELD";136;NC-17
"PICKUP DRIVING";77;G
"INDEPENDENCE HOTEL";157;NC-17
"PRIVATE DROP";106;PG
"SAINTS BRIDE";125;G
"FOREVER CANDIDATE";131;NC-17
"MILLION ACE";142;PG-13
"SLEEPY JAPANESE";137;PG
"WRATH MILE";176;NC-17
"YOUTH KICK";179;NC-17
"CLOCKWORK PARADISE";143;PG-13
----

=== Export data to cloud storage

To export data to an object storage from a Redpanda SQL table, use the `COPY TO` command with object storage credentials:

[source,sql]
----
COPY table_name TO 'cloud_storage_file_path' (object_storage(object_storage_credentials));
----

* `object storage`: `AWS_CRED`, `AZURE_CRED`, or `GCS_CRED` (depending on your provider).
* `object_storage_credentials`: Credentials for accessing your cloud storage.

Provide provider-specific credentials to authenticate access to your files. Use the following authentication parameters to access your cloud storage.

==== AWS S3 bucket

* `aws_region`: AWS region associated with the storage service.
* `key_id`: Key identifier for authentication.
* `access_key`: Access key for authentication.
* `endpoint_url`: URL endpoint for the storage service.

[source,sql]
----
COPY my_catalog=>film TO 's3://your-bucket/file_name' WITH (AWS_CRED(AWS_REGION 'us-west-1', AWS_KEY_ID 'key_id', AWS_PRIVATE_KEY 'access_key', ENDPOINT 's3.us-west-1.amazonaws.com'), FORMAT CSV, HEADER ON, NULL 'unknown');
----

TIP: In the exported file, `NULL` values are represented as `unknown` as specified in the `NULL` option.

==== Google Cloud Storage

* `<path_to_credentials>`: Path to the JSON credentials file.
* `<json_credentials_string>`: Contents of the GCS credentials file.

[source,sql]
----
COPY my_catalog=>film TO 'gs://your-bucket/file_name' (GCS_CRED('/path/to/credentials.json'));
----

TIP: For Google Cloud Storage, it is recommended to use HMAC keys for authentication. See the link:https://cloud.google.com/storage/docs/authentication/hmackeys[HMAC keys - Cloud Storage^] page for details.

==== Azure Blob Storage

* `tenant_id`: Tenant identifier representing your organization's identity in Azure.
* `client_id`: Client identifier used for authentication.
* `client_secret`: Secret identifier acting as a password for authentication.

[source,sql]
----
COPY my_catalog=>film TO 'wasbs://container-name/your_blob' (AZURE_CRED(TENANT_ID 'your_tenant_id' CLIENT_ID 'your_client_id', CLIENT_SECRET 'your_client_secret'));
----
