= Redpanda Cloud API Deprecation Policy
:description: Deprecation and versioning policy for Redpanda Cloud API.
:page-api: cloud

This document outlines the Cloud API deprecation and versioning policy to ensure a smooth transition for Redpanda Cloud users. To maintain a reliable and robust API that supports your integration needs, it is sometimes necessary to deprecate older versions or features of the Redpanda Cloud API as Redpanda introduces improvements, addresses security concerns, and updates the technology stack. Redpanda adheres to this policy to maintain a balance between innovation and stability, ensuring the best possible experience for customers and partners. 

For questions and concerns regarding the policy, contact https://support.redpanda.com/hc/en-us/requests/new[Redpanda Support^]. 

== Definition

Deprecation is the process of phasing out an API version or specific features within an API. When deprecated, these versions or features no longer receive updates, support, or guarantees of availability, and are not usable at the end of the deprecation period.

=== Availability

The Cloud API follows these availability phases: 

* Limited availability (LA): The API is available to select customers in a subset of regions, providers, or networks. Recommended for production usage.
* Generally available (GA): The API is stable. Protocol breaking changes are not introduced on short notice. Recommended for production usage. 
* Deprecated: The API version or method is no longer under active development. Existing workflows and integrations using the API continue to function, but new use cases should be built against the new version. The deprecated API version or method is retired on the retirement date. 
* Retired: The API version or method is no longer supported nor available.

== Deprecation notice and timelines

. Redpanda provides a formal deprecation notice to users when an API version or API method is scheduled for deprecation. This notice includes:
+
--
* The specific API version or method to be deprecated.
* The reason for deprecation.
* The deprecation timeline, including key dates:
** Announcement date: The date when the deprecation is officially announced. The API version or method remains available through the end-of-support date, until the retirement date.
** End-of-Support date: The last date the deprecated API version or call is supported. The API is available, but is not under active development and no longer receives support. This date is six months after the announcement date.
** Retirement date: The date when the deprecated API or feature is removed and no longer available. This date is 12 months after the announcement date.
--
. Users have a transition period between the announcement date and the retirement date to migrate to new API versions or methods.
. Starting from the retirement date, calls to the deprecated API version or method may:
+
--
* Be rejected with appropriate error codes.
* Result in degraded performance.
* Result in unexpected behavior.
--

To avoid disruption, you are encouraged to monitor usage of deprecated methods and update integrations promptly.

=== Exceptions to standard timeline

In rare cases, the deprecation process may need to be accelerated due to:

* Critical security vulnerabilities.
* Compliance requirements.
* External infrastructure changes outside Redpanda's control.

== Notification channels

Redpanda communicates deprecation notices through the following:

* A `Sunset` HTTP header in the response 
* `deprecated: true` field in the API specification
* Updates to xref:manage:api/index.adoc[Cloud API documentation]
* xref:get-started:whats-new-cloud.adoc[What’s New in Redpanda Cloud]
* Announcements in internal customer Slack channels
* #cloudapi Slack channel at redpandacommunity.slack.com
* Emails to “Sign up for updates” recipients (sign up on the xref:api:ROOT:cloud-controlplane-api.adoc[Control Plane API] and xref:api:ROOT:cloud-dataplane-api.adoc[Data Plane APIs] reference documentation)

== Versioning policy

Redpanda Cloud API versions are denoted in the API URL with the following format: `vX`, for example, `v1`. The version number is incremented when there are breaking changes to the API.

The Control Plane API and Data Plane API may be versioned independently of each other, and individual components such as RBAC (IAM) consisting of Control Plane Users, Control Plane Service Accounts, and Control Plane Role Bindings may also have a different version number than the base API. 

=== Breaking changes

* Renaming a field
* Changing a field data type
* Renaming a method or service 
* Removing a method or service


