= Use the Data Plane APIs
:description: Use the Data Plane APIs to manage your Redpanda Cloud clusters.
:page-aliases: deploy:deployment-option/cloud/api/cloud-dataplane-api.adoc
:page-beta: true

The Redpanda Cloud API is a collection of REST APIs that allow you to interact with different parts of Redpanda Cloud. The Data Plane APIs enable you to programmatically manage the resources within your clusters, including topics, users, access control lists (ACLs), and connectors. You can call the API endpoints directly, or use tools like Terraform or Python scripts to automate resource management.

For the full Cloud API reference documentation, see xref:api:ROOT:cloud-api.adoc[Redpanda Cloud API Reference].

The xref:manage:api/cloud-api-overview.adoc#cloud-api-architecture[data plane] contains the actual Redpanda clusters. Every cluster is its own data plane, and so it has its own distinct xref:manage:api/cloud-api-overview.adoc#data-plane-apis-url[Data Plane API URL].

== Get Data Plane API URL

[tabs]
======
BYOC or Dedicated::
+
--
To retrieve the Data Plane API URL of a cluster, make a request to xref:api:ROOT:cloud-api.adoc#get-/v1beta2/clusters/-id-[`GET /v1beta2/clusters/\{id}`].
--

Serverless::
+
--
To retrieve the Data Plane API URL of a cluster, make a request to xref:api:ROOT:cloud-api.adoc#get-/v1beta2/serverless/clusters/-id-[`GET /v1beta2/serverless/clusters/\{id}`].
--
======

The response includes a `dataplane_api.url` value:

[,bash,lines=5]
----
  "id": "....",
  "name": "my-cluster",
....
  "dataplane_api": {
    "url": "https://api-xyz.abc.fmc.ppd.cloud.redpanda.com"
  },
...
----

== Data Plane APIs

=== Create a user

To create a new user in your Redpanda cluster, make a POST request to the xref:api:ROOT:cloud-api.adoc#post-/v1alpha2/users[`/v1alpha2/users`] endpoint, including the SASL mechanism, username, and password in the request body:

[,bash]
----
curl -X POST "https://<dataplane-api-url>/v1alpha2/users" \
 -H "Authorization: Bearer <token>" \
 -H "accept: application/json" \
 -H "content-type: application/json" \
 -d '{"mechanism":"SASL_MECHANISM_SCRAM_SHA_256","name":"payment-service","password":"secure-password"}'
----

TIP: When using a shell substitution variable for the token, use double quotes to wrap the header value.

The success response returns the newly-created username and SASL mechanism:

[.no-copy]
----
{
  "user": {
    "name": "payment-service",
    "mechanism": "SASL_MECHANISM_SCRAM_SHA_256"
  }
}
----

=== Create an ACL

To create a new ACL in your Redpanda cluster, make a xref:api:ROOT:cloud-api.adoc#post-/v1alpha2/acls[`POST /v1alpha2/acls`] request. The following example ACL allows all operations on any Redpanda topic for a user with the name `payment-service`.

[,bash]
----
curl -X POST "https://<dataplane-api-url>/v1alpha2/acls" \
 -H "Authorization: Bearer <token>" \
 -H "accept: application/json" \
 -H "content-type: application/json" \
 -d '{"host":"*","operation":"OPERATION_ALL","permission_type":"PERMISSION_TYPE_ALLOW","principal":"User:payment-service","resource_name":"*","resource_pattern_type":"RESOURCE_PATTERN_TYPE_LITERAL","resource_type":"RESOURCE_TYPE_TOPIC"}'
----

The success response is empty, with a 201 status code.

[.no-copy]
----
{}
----

=== Create a topic

To create a new Redpanda topic without specifying any further parameters, such as the desired topic-level configuration or partition count, make a POST request to xref:api:ROOT:cloud-api.adoc#post-/v1alpha2/topics[`/v1alpha2/topics`] endpoint:

[,bash]
----
curl -X POST "<dataplane-api-url>/v1alpha2/topics" \
 -H "Authorization: Bearer <token>" \
 -H "accept: application/json" \
 -H "content-type: application/json" \
 -d '{"name":"<topic-name>"}'
----

=== Redpanda Connect

Use the API to manage xref:develop:connect/about.adoc[Redpanda Connect pipelines] in Redpanda Cloud.

NOTE: The Pipeline APIs for Redpanda Connect are supported in BYOC and Serverless clusters only.

==== Get Redpanda Connect pipeline

To get details of a specific pipeline, make a xref:api:ROOT:cloud-api.adoc#get-/v1alpha2/redpanda-connect/pipelines/-id-[`GET /v1alpha2/redpanda-connect/pipelines/\{id}]` request.

[,bash]
----
curl "https://<dataplane-url>/v1alpha2/redpanda-connect/pipelines/<pipeline-id>"
----

==== Stop a Redpanda Connect pipeline

To stop a running pipeline, make a xref:api:ROOT:cloud-api.adoc#put-/v1alpha2/redpanda-connect/pipelines/-id-/stop[`PUT /v1alpha2/redpanda-connect/pipelines/\{id}/stop`] request.

[,bash]
----
curl -X PUT "https://<dataplane-url>/v1alpha2/redpanda-connect/pipelines/<pipeline-id>/stop"
----

==== Start a Redpanda Connect pipeline

To start a previously stopped pipeline, make a xref:api:ROOT:cloud-api.adoc#put-/v1alpha2/redpanda-connect/pipelines/-id-/start[`PUT /v1alpha2/redpanda-connect/pipelines/\{id}/start`] request.

[,bash]
----
curl -X PUT "https://<dataplane-url>/v1alpha2/redpanda-connect/pipelines/<pipeline-id>/start"
----

==== Update a Redpanda Connect pipeline

To update a pipeline, make a xref:api:ROOT:cloud-api.adoc#put-/v1alpha2/redpanda-connect/pipelines/-id-[`PUT /v1alpha2/redpanda-connect/pipelines/\{id}`] request. You update a pipeline configuration to scale resources, for example the number of CPU cores and amount of memory allocated.

[,bash]
----
curl -X PUT "https://api.redpanda.com/v1alpha2/redpanda-connect/pipelines/" \
 -H 'accept: application/json'\
 -H 'content-type: application/json' \
 -d '{"resources":{"cpu_shares":"8","memory_shares":"8G"}}' 
----

=== Kafka Connect

Use the API to configure your xref:develop:managed-connectors/index.adoc[Kafka Connect] clusters.

NOTE: Kafka Connect is supported in BYOC and Dedicated clusters only.

==== Create a Kafka Connect connector

To create a connector, make a POST request to xref:api:ROOT:cloud-api.adoc#post-/v1alpha2/kafka-connect/clusters/-cluster_name-/connectors[`/v1alpha2/kafka-connect/clusters/\{cluster_name}/connectors`]. 

The following example shows how to create an S3 sink connector with the name `my-connector`:

[,bash]
----
curl -X POST "<dataplane-api-url>/v1alpha2/kafka-connect/clusters/redpanda/connectors" \
 -H "Authorization: Bearer <token>" \
 -H "accept: application/json" \
 -H "content-type: application/json" \
 -d '{"config":{"connector.class":"com.redpanda.kafka.connect.s3.S3SinkConnector","topics":"test-topic","aws.secret.access.key":"${secretsManager:<secret-id>}","aws.s3.bucket.name":"bucket-name","aws.access.key.id":"access-key","aws.s3.bucket.check":"false","region":"us-east-1"},"name":"my-connector"}'
----

[CAUTION]
====
The field `aws.secret.access.key` in the example contains sensitive information that usually shouldn't be added to a configuration directly. Use the xref:api:ROOT:cloud-api.adoc#post-/v1alpha2/kafka-connect/clusters/-cluster_name-/secrets[Secrets API] to create a secret that stores the value of the key. You can then use the secret ID to inject the value of the secret in your request.

To create a secret that you can reference in the connector configuration request:

[,bash]
----
curl -X POST "https://<dataplane-api-url>/v1alpha2/kafka-connect/clusters/redpanda/secrets" \
 -H 'accept: application/json'\
 -H 'content-type: application/json' \
 -d '{"name":"<connector-name>","secret_data":"<secret-value>"}' 
----

Use the `id` returned in the Create Secret response to replace the placeholder `<secret-id>` in the previous Create Connector example. The syntax `${secretsManager:<secret-id>}` tells the Kafka Connect cluster to load `<secret-id>`. 
====

Example success response:

[.no-copy]
----
{
  "name": "my-connector",
  "config": {
    "aws.access.key.id": "access-key",
    "aws.s3.bucket.check": "false",
    "aws.s3.bucket.name": "bucket-name",
    "aws.secret.access.key": "secret-key",
    "connector.class": "com.redpanda.kafka.connect.s3.S3SinkConnector",
    "name": "my-connector",
    "region": "us-east-1",
    "topics": "test-topic"
  },
  "tasks": [],
  "type": "sink"
}
----

==== Restart a Kafka Connect connector

To restart a connector, make a POST request to the xref:api:ROOT:cloud-api.adoc#post-/v1alpha2/kafka-connect/clusters/-cluster_name-/connectors/-name-/restart[`/v1alpha2/kafka-connect/clusters/\{cluster_name}/connectors/\{name}/restart`] endpoint:

[,bash]
----
curl -X POST "<dataplane-api-url>/v1alpha2/kafka-connect/clusters/redpanda/connectors/my-connector/restart" \
 -H "Authorization: Bearer <token>" \
 -H "accept: application/json"\
 -H "content-type: application/json" \
 -d '{"include_tasks":false,"only_failed":false}'
----

== Limitations

* Client SDKs are not available.

