= UNIX_MILLIS
:description: The UNIX_MILLIS() function returns a given timestamp to a UNIX timestamp in milliseconds from 1970-01-01 00:00:00-00 (can be negative).
:page-topic-type: reference

The `UNIX_MILLIS()` function returns a given timestamp to a UNIX timestamp in milliseconds from 1970-01-01 00:00:00-00 (can be negative). Its syntax is illustrated below:

[source,sql]
----
SELECT UNIX_MILLIS(TIMESTAMP)
----

Its input type is a TIMESTAMP expression, and the return data type is `BIGINT` representing time in milliseconds.

== Examples

=== Basic `UNIX_MILLIS()` function

The below example uses the `UNIX_MILLIS()` function to convert a given timestamp into a UNIX timestamp in milliseconds:

[source,sql]
----
SELECT UNIX_MILLIS(TIMESTAMP "1996-5-02 7:15:00+00") AS unix_millisvalues;
----

The final output will be as follows:

[source,sql]
----
+-----------------------------+
| unix_millisvalues           |
+-----------------------------+
| 831021300000.000000         |
+-----------------------------+
----

=== `UNIX_MILLIS()` function using columns

Suppose you have a table named **time_example** with the following timestamp values in the *time_stamp* column:

[source,sql]
----
CREATE TABLE time_example (
  time_stamp timestamp
);

INSERT INTO time_example VALUES
('2004-07-23 11:30:00+00'),
('2011-02-12 04:45:00+00'),
('1975-08-03 07:50:00+00');
----

[source,sql]
----
SELECT * FROM time_example;
----

The above query will show the following table:

[source,sql]
----
+-------------------------+
| time_example            |
+-------------------------+
| 2004-07-23 11:30:00     |
| 2011-02-12 04:45:00     |
| 1975-08-03 07:50:00     |
+-------------------------+
----

To convert all timestamp values into UNIX timestamp values in milliseconds, run the following query:

[source,sql]
----
SELECT time_stamp, UNIX_MILLIS(time_stamp) AS time_millis FROM time_example;
----

The output displays all the timestamp entries of the table in the **time_stamp** column and the converted UNIX milliseconds timestamp entries in the column *time_millis*.

[source,sql]
----
+-------------------------+-----------------------+
| time_stamp              | time_millis           |
+-------------------------+-----------------------+
| 2004-07-23 11:30:00     | 1090582200000.000000  |
| 2011-02-12 04:45:00     | 1297485900000.000000  |
| 1975-08-03 07:50:00     | 176284200000.000000   |
+-------------------------+-----------------------+
----
