= Create a BYOC Cluster on Azure
:description: Use the Redpanda Cloud UI to create a BYOC cluster on Azure.
:page-aliases: deploy:deployment-option/cloud/create-byoc-cluster-azure.adoc, get-started:cluster-types/byoc/create-byoc-cluster-azure.adoc


To create a Redpanda cluster in your virtual network (VNet), follow the instructions in the Redpanda Cloud UI. The UI contains the parameters necessary to successfully run `rpk cloud byoc apply`. See also: xref:get-started:byoc-arch.adoc[BYOC architecture].

NOTE: With standard BYOC clusters, Redpanda manages security policies and resources for your virtual network (VNet), including subnetworks, managed identities, IAM roles, security groups, and storage accounts. For the most security, you can manage these resources yourself with a xref:get-started:cluster-types/byoc/azure/vnet-azure.adoc[BYOVNet cluster on Azure].

== Prerequisites

Before you deploy a BYOC cluster on Azure, check all prerequisites to ensure that your Azure subscription meets requirements.

===  Configure Azure CLI

* https://learn.microsoft.com/en-us/cli/azure/install-azure-cli[Install the Azure CLI^].
* https://learn.microsoft.com/en-us/cli/azure/authenticate-azure-cli[Sign in^] with the Azure CLI:
+
```
az login
```
* Set the desired subscription for the Azure CLI:
+
```
az account set --subscription <subscription-name>
```

=== Verify rpk version

Confirm you have a minimum version of Redpanda `rpk` v24.1. See xref:manage:rpk/rpk-install.adoc[].

=== Prepare your Azure subscription

In the https://login.microsoftonline.com/[Azure Portal^], confirm that the dedicated subscription you intend to use with Redpanda includes the following: 

* **Role**: The Azure user must have the _Owner_ role in the subscription.

* **Resources**: The subscription must be registered for the following resource providers (AKS + common dependencies). See the https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/resource-providers-and-types[Microsoft documentation^]. 
+
--
** Microsoft.Compute
** Microsoft.ManagedIdentity
** Microsoft.Storage
** Microsoft.KeyVault
** Microsoft.Network
** Microsoft.ContainerService
--
+
To check if a resource provider is registered, run the following command using the Azure CLI or in the Azure Cloud Shell:
+
```
az provider show -n Microsoft.Compute --query registrationState -o tsv
az provider show -n Microsoft.ManagedIdentity --query registrationState -o tsv
az provider show -n Microsoft.Storage --query registrationState -o tsv
az provider show -n Microsoft.KeyVault --query registrationState -o tsv
az provider show -n Microsoft.Network --query registrationState -o tsv
az provider show -n Microsoft.ContainerService --query registrationState -o tsv
```
+
If a resource provider is not registered, run:
+
```
az provider register --namespace Microsoft.Compute
az provider register --namespace Microsoft.ManagedIdentity
az provider register --namespace Microsoft.Storage
az provider register --namespace Microsoft.KeyVault
az provider register --namespace Microsoft.Network
az provider register --namespace Microsoft.ContainerService
```

* **Feature**: The subscription must be registered for Microsoft.Compute/EncryptionAtHost. See the https://learn.microsoft.com/en-us/azure/virtual-machines/linux/disks-enable-host-based-encryption-cli#prerequisites[Microsoft documentation^].
+
To register it, run:
+
```
az feature register --namespace Microsoft.Compute --name EncryptionAtHost

# (optional) Wait and verify it shows as Registered
az feature show --namespace Microsoft.Compute --name EncryptionAtHost --query properties.state -o tsv

# Refresh the provider after enabling a feature
az provider register --namespace Microsoft.Compute
```

* **Monitoring**: The subscription must have Azure Network Watcher enabled in the NetworkWatcherRG resource group and the region where you will use Redpanda. Network Watcher lets you monitor and diagnose conditions at a network level. See the https://learn.microsoft.com/en-us/azure/network-watcher/network-watcher-create?tabs=portaly[Microsoft documentation^]. 
+
To enable it, run:
+
``` 
# Create the NetworkWatcherRG resource group
az group create --name 'NetworkWatcherRG' --location '<region_name>'

# Enable Network Watcher in <region_name>
az network watcher configure --resource-group 'NetworkWatcherRG' --locations '<region_name>' --enabled
```

=== Check Azure quota

Confirm that the Azure subscription has enough virtual CPUs (vCPUs) per instance family and total regional vCPUs in the region where you will use Redpanda:

* Standard Ddv5-series vCPUs:  12  (3 Redpanda broker nodes + extra capacity for 3 more nodes that could be utilized temporarily during tier 1 maintenance)
* Standard Dadsv5-series vCPUs: 8  (2 Redpanda utility nodes)
* Standard Dv3-series vCPUs:    2  (1 Redpanda agent node)

See the https://learn.microsoft.com/en-us/azure/quotas/view-quotas[Microsoft documentation^].

=== Check Azure SKU restrictions

Ensure your subscription has access to the required VM sizes in the region where you will use Redpanda. For example, using the Azure CLI or in the Azure Cloud Shell, run:

[source,bash]
----
# Replace eastus2 with your target region
az vm list-skus -l eastus2 --zone --size Standard_D2d_v5 --output table
----

.Example output (no restrictions: good)
[%nowrap,bash]
----
ResourceType     Locations    Name               Zones    Restrictions
---------------  -----------  ---------------    -------  ------------
virtualMachines  eastus2      Standard_D2d_v5    1,2,3    None
----

.Example output (with restrictions: needs attention)
[%nowrap,bash]
----
ResourceType     Locations    Name               Zones    Restrictions
---------------  -----------  ---------------    -------  ------------
virtualMachines  eastus2      Standard_D2d_v5    1,2,3    NotAvailableForSubscription
----

If you see restrictions, https://learn.microsoft.com/en-us/troubleshoot/azure/general/region-access-request-process[open a Microsoft support request^] to remove them. 

=== Prerequisite checklist

[%interactive]
* [ ] Verified `rpk` version
* [ ] Verified Azure user has Owner role
* [ ] Registered all required resource providers
* [ ] Registered EncryptionAtHost feature
* [ ] Enabled Network Watcher
* [ ] Verified vCPU quota
* [ ] Verified no SKU restrictions


== Create a BYOC cluster

To create a Redpanda cluster in your Azure VNet, follow the <<prerequisites,prerequisites>> then follow the instructions in the Redpanda Cloud UI. The UI contains the parameters necessary to successfully run `rpk cloud byoc apply`.  

. Log in to https://cloud.redpanda.com[Redpanda Cloud^].
. On the Clusters page, click *Create cluster*, then click *Create BYOC cluster*.
. Enter a cluster name, then select the resource group, provider (Azure), xref:reference:tiers/byoc-tiers.adoc[region, tier], availability, and Redpanda version. 
+
[NOTE]
==== 
* If you plan to create a private network in your own VNet, select the region where your VNet is located.
* Multi-AZ is the default configuration. Three AZs provide two backups in case one availability zone goes down.
====
+ 
Optionally, click *Advanced settings* to specify up to five key-value custom tags. After the cluster is created, the tags are applied to all Azure resources associated with this cluster. For details, see the https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/tag-resources[Microsoft documentation^]. After the cluster is created, you can <<manage-custom-tags,specify more tags with the Cloud API>>. 

. Click *Next*.
. On the Network page, select the connection type: either public or private. For BYOC clusters, private using Azure Private Link is best-practice.
** Your network name is used to identify this network.
** For a xref:networking:cidr-ranges.adoc[CIDR range], choose one that does not overlap with your existing VPCs or your Redpanda network.
** For API gateway access, select either public or private. Public access exposes endpoints for Redpanda Console, the Data Plane API, and the MCP Server API, but they are still protected by authentication and authorization controls. Private access restricts endpoint access to your VNet only.
+
NOTE: If you change from public access to private access after cluster creation, users without VPN access to your VNet will lose access to these services.
. Click *Next*.
. On the Deploy page, follow the steps to log in to Redpanda Cloud and deploy the agent.
+
As part of agent deployment, Redpanda assigns the permissions required to run the agent. For details about these permissions, see xref:security:authorization/cloud-iam-policies-azure.adoc[Azure IAM policies].

== Manage custom tags

include::get-started:partial$custom-tags-azure.adoc[]
