= pg_attrdef
:description: The pg_attrdef stores information about column default values.

The `pg++_++attrdef` stores information about column default values. It mimics the https://www.postgresql.org/docs/current/catalog-pg-attrdef.html[pg++_++attrdef] PostgreSQL system catalog.

[WARNING]
====
Please note that Oxla doesn’t support the custom types
====

== Columns

[NOTE]
====
This table is designed for compatibility with tools that require PostgreSQL system tables, so it mostly has dummy data. Please note that not all columns in `pg_attrdef` are applicable to every type of relation.
====
The following columns are available for querying in `pg++_++attrdef`:

[width="100%",cols="10%,12%,78%",options="header",]
|===
|Column |Type |Description
|`oid` |`int` |This column represents the row identifier
|`adrelid` |`int` |This column represents the table to which this column belongs
|`adnum` |`int` |This column represents the number of the column within the table
|`adbin` |`text` |This column represents the default value for the column
|===
