[tabs]
=====
Free trial::
+
--
A https://www.redpanda.com/try-redpanda[free trial^] is the fastest way to get started with Serverless, and it comes with a `welcome` cluster. New trials receive $100 (USD) in free credits to spend in the first 14 days. This should be enough to run Redpanda with reasonable throughput. No credit card is required. To continue using Serverless after your trial expires, you can enter a credit card and pay as you go. Any remaining credit balance is used before you are charged. 

When either the credits expire or the days in the trial expire, the clusters move into a suspended state, and you won't be able to access your data in either the Redpanda Cloud UI or with the Kafka API. There is a seven-day grace period following the end of the trial. After that, the data is permanently deleted. 

* To ask questions about the trial, use the *#serverless* https://redpandacommunity.slack.com/[Community Slack^] channel.
* For information about billing after the trial ends, see xref:billing:billing.adoc[].

--
Redpanda Sales::
+
--
To request a private offer with possible discounts for annual committed use, contact https://www.redpanda.com/price-estimator[Redpanda Sales^]. When you subscribe to Serverless through Redpanda Sales, you get immediate access to Enterprise support. 

Redpanda creates a cloud organization for you and sends you a welcome email. 
--
AWS Marketplace::
+
--
New subscriptions to Redpanda Cloud through xref:billing:aws-pay-as-you-go.adoc[AWS Marketplace] receive $300 (USD) in free credits to spend in the first 30 days. AWS Marketplace charges for anything beyond $300, unless you cancel the subscription. After your free credits have been used, you can continue using your cluster without any commitment, only paying for what you consume and canceling anytime. 

NOTE: When you subscribe to Redpanda through AWS Marketplace, you do not have immediate access to Enterprise support, only the https://redpandacommunity.slack.com/[Community Slack^] channel. To access Enterprise support, contact https://www.redpanda.com/price-estimator[Redpanda Sales^]

Redpanda creates a cloud organization for you and sends you a welcome email. 
--
=====