[tabs]
=====
Free trial::
+
--
A https://www.redpanda.com/try-redpanda[free trial on AWS^] is the fastest way to get started with Serverless. Each free-trial customer qualifies for $100 (USD) in credits to spend in the first 14 days. This should be enough to run Redpanda with reasonable throughput. No credit card is required. To continue using Serverless after your trial expires, you can enter a credit card and pay as you go. Any remaining credit balance is used before you are charged. 

When either the credits expire or the days in the trial expire, the clusters move into a suspended state, and you won't be able to access your data in either the Redpanda Cloud UI or with the Kafka API. There is a seven-day grace period following the end of the trial. After that, the data is permanently deleted. For questions about the trial, use the *#serverless* https://redpandacommunity.slack.com/[Community Slack^] channel.

After you start a trial, Redpanda instantly prepares an account for you. Your account includes a `welcome` cluster with a `hello-world` demo topic you can explore. It includes sample data so you can see how real-time messaging works before sending your own data.

xref:get-started:cluster-types/serverless.adoc#interact-with-your-cluster[Get started] by following the wizard to create a Redpanda Connect pipeline, or by following the steps in the UI to use `rpk` to interact with your cluster from the command line:

. Log in with `rpk cloud login`.
. Consume from the `hello-world` topic with `rpk topic consume hello-world`.
. In the https://cloud.redpanda.com[Redpanda Cloud UI^], navigate to the *Topics* page and open the `hello-world` topic to see the included messages. 

--
Redpanda Sales::
+
--
To request a private offer with possible discounts for annual committed use, contact https://www.redpanda.com/price-estimator[Redpanda Sales^]. When you subscribe to Serverless through Redpanda Sales, you gain immediate access to Enterprise support. 

Redpanda creates a cloud organization for you and sends you a welcome email. 
--
AWS Marketplace::
+
--
New subscriptions to Redpanda Cloud through xref:billing:aws-pay-as-you-go.adoc[AWS Marketplace] receive $300 (USD) in free credits to spend in the first 30 days. AWS Marketplace charges for anything beyond $300, unless you cancel the subscription. After your free credits have been used, you can continue using your cluster without any commitment, only paying for what you consume and canceling anytime. 

NOTE: When you subscribe to Redpanda through AWS Marketplace, you do not have immediate access to Enterprise support, only the https://redpandacommunity.slack.com/[Community Slack^] channel. For Enterprise support, contact https://www.redpanda.com/price-estimator[Redpanda Sales^]

Redpanda creates a cloud organization for you and sends you a welcome email. 
--
=====