= Overview
:description: Set operations are operations used to manipulate and analyze sets.

Set operations are operations used to manipulate and analyze sets. It includes the following operations:

. xref:reference:sql/sql-clauses/set-operations/union.adoc[Union]: Combines two or more sets to create a new set containing all unique elements from the input sets.
. xref:reference:sql/sql-clauses/set-operations/intersect.adoc[Intersect]: Yields a new set with elements common to all input sets.
. xref:reference:sql/sql-clauses/set-operations/except.adoc[Except]: Generates a set containing elements from the first set that are not present in the second set.
+
These operations allow for comparisons, combinations, and distinctions among sets in various contexts.

[NOTE]
====
For all set operations, the data types of corresponding columns in the `SELECT` queries must be compatible. The order of columns is flexible as long as the columns in consecutive places are pairwise compatible. For example, `SELECT col1, col2 FROM table1 UNION SELECT col2, col1 FROM table2`.
====
