= Numeric Data Type Aliases
:description: Aliases for the primary numeric data types in Redpanda SQL, mapped to their primary types during processing.
:page-topic-type: reference

Redpanda SQL accepts aliases that you can use interchangeably with the primary data types. During processing, Redpanda SQL maps these aliases to their corresponding primary data types.

The following sections describe the numeric data type aliases:

== `integer` alias

The `integer` alias is an alternative name for the `int` data type. For example, the following two queries are functionally the same:

[source,sql]
----
CREATE TABLE ExampleTable (
    id INTEGER,
);

-- Functionally the same as the previous table
CREATE TABLE AnotherTable (
    id INT,
);
----

[NOTE]
====
Even though you specify the `integer` alias in DDL, Redpanda SQL stores and treats the data as `int`.
====

== `long` alias

The `long` alias is often used to represent larger integer values. For example:

[source,sql]
----
CREATE TABLE LargeValues (
    value LONG,
);

-- Functionally the same as the previous table
CREATE TABLE LargeValuesEquivalent (
    value BIGINT,
);
----

[NOTE]
====
Even though you specify the `long` alias in DDL, Redpanda SQL stores and treats the data as `bigint`.
====

== `float` alias

The `float` alias corresponds to the `real` data type. For example:

[source,sql]
----
CREATE TABLE FloatExample (
    price FLOAT,
);

-- Functionally the same as the previous table
CREATE TABLE FloatEquivalent (
    price REAL,
);
----

[NOTE]
====
Even though you specify the `float` alias in DDL, Redpanda SQL stores and treats the data as `real`.
====

== `double` alias

The `double` alias defines `double precision` floating-point numbers. For example:

[source,sql]
----
CREATE TABLE DoubleExample (
    measurement DOUBLE,
);

-- Functionally the same as the previous table
CREATE TABLE DoubleEquivalent (
    measurement DOUBLE PRECISION,
);
----

[NOTE]
====
Even though you specify the `double` alias in DDL, Redpanda SQL stores and treats the data as `double precision`.
====
