= IF Function
:description: This function returns the specified value if the condition is TRUE and another value if the condition is FALSE.

This function returns the specified value if the condition is `TRUE` and another value if the condition is `FALSE`. The syntax of the `IF()`function is shown below:

[source,sql]
----
IF(expression, true_result, else_result)
----

[WARNING]
====
The `expression` must be a Boolean expression.
====

==== Examples

==== Case ++#++1: `IF()` with a table

In this example, we have the *test++_++result* table. We want to know which participants passed and which failed from the table below:

[source,sql]
----
CREATE TABLE test_result (
  applicant_id int,
  name text,
  score int
);

INSERT INTO test_result VALUES
(78765,'Mike Aoki',677),
(78786,'Julie Grahams',650),
(78986,'Alexandra Jones',450),
(79742,'Lucas Moore',487),
(79769,'Augustine Harkness',572);
----

[source,sql]
----
SELECT * FROM test_result;
----

The above query will display the following table:

[source,sql]
----
+---------------+--------------------+--------+
| applicant_id  | name               | score  |
+---------------+--------------------+--------+
| 78765         | Mike Aoki          | 677    |
| 78786         | Julie Grahams      | 650    |
| 78986         | Alexandra Jones    | 450    |
| 79742         | Lucas Moore        | 487    |
| 79769         | Augustine Harkness | 572    |
+---------------+--------------------+--------+
----

[arabic]
. IF function in the query below states that _IF the score is equal to or greater than 500, then return “PASSED“. Otherwise, if the score is smaller than 500, return “NOT PASSED”_.

[source,sql]
----
SELECT name, IF(score>=500, 'PASSED', 'NOT PASSED') FROM test_result;
----

[arabic, start=2]
. It will return the following result:

[source,sql]
----
+--------------------+-------------+
| name               | case        |
+--------------------+-------------+
| Mike Aoki          | PASSED      |
| Julie Grahams      | PASSED      |
| Alexandra Jones    | NOT PASSED  |
| Lucas Moore        | NOT PASSED  |
| Augustine Harkness | PASSED      |
+--------------------+-------------+
----

==== Case ++#++2: IF() with expressions as return value

In the second example, we have another table named “*deptcost*. We want to know which department exceeded the budget and which one did not from the following table.

[source,sql]
----
CREATE TABLE deptcost (
  dept text,
  budget int,
  actual int,
  status text
);
INSERT INTO deptcost VALUES
('Finance', 800,677,'within budget'),
('HR', 700,930,'over budget'),
('Marketing', 500,677,'over budget'),
('Project', 720,700,'within budget'),
('Sales', 910,860,'within budget');
----

Run the following query to display the table:

[source,sql]
----
SELECT * FROM deptcost;
----

We have *deptcost* table as seen below:

[source,sql]
----
+-----------+--------+--------+---------------+
| dept      | budget | actual | status        |
+-----------+--------+--------+---------------+
| Finance   | 800    | 677    | within budget |
| HR        | 700    | 930    | over budget   |
| Marketing | 500    | 677    | over budget   |
| Project   | 720    | 700    | within budget |
| Sales     | 910    | 860    | within budget |
+-----------+--------+--------+---------------+
----

[arabic]
. The following IF function states that _IF the actual is less than the budget, then return the budget difference, otherwise return 0_.

[source,sql]
----
SELECT dept, IF(actual < budget, budget - actual, 0) FROM deptcost;
----

[arabic, start=2]
. We get the following result using the `IF()` function:

[source,sql]
----
+-----------+-----+
|   dept    |  f  |
+-----------+-----+
| Finance   | 123 |
| HR        |   0 |
| Marketing |   0 |
| Project   |  20 |
| Sales     |  50 |
+-----------+-----+
----
