= API Reference
:description: Use Redpanda API reference documentation to learn about and interact with API endpoints.

* xref:api:ROOT:cloud-controlplane-api.adoc[Redpanda Cloud Control Plane API Reference]
+
Use the Control Plane API to manage resources in your Redpanda Cloud organization such as clusters and networks.
* xref:api:ROOT:cloud-dataplane-api.adoc[Redpanda Cloud Data Plane API Reference]
+
Use the Data Plane API to manage topics, ACLs, and connectors within each cluster.
* xref:api:ROOT:pandaproxy-schema-registry.adoc[Schema Registry API Reference]
+
Manage schemas within a Redpanda cluster. See also: xref:manage:schema-reg/index.adoc[Schema Registry documentation].
* xref:api:ROOT:pandaproxy-rest.adoc[HTTP Proxy API Reference]
+
HTTP Proxy is an HTTP server that exposes operations you can perform directly on a Redpanda cluster. Use the Redpanda HTTP Proxy API to perform a subset of actions that are also available through the Kafka API, but using simpler REST operations. See also: xref:develop:http-proxy.adoc[Use Redpanda with the HTTP Proxy API].

