= Redpanda Terraform Provider
:description: Learn how to use the Redpanda Terraform provider to create and manage resources in Redpanda Cloud.
:page-cloud: true
:page-beta: true

A Terraform provider is a plugin that interacts with cloud providers, third-party tools, and other APIs. The https://registry.terraform.io/providers/redpanda-data/redpanda/latest[Redpanda Terraform provider^] interfaces with the Redpanda Cloud API, enabling you to define your Redpanda infrastructure in Terraform configuration files. 

You can use the Redpanda Terraform provider to create and manage the following resources in Redpanda Cloud:

* ACLs
* Clusters 
* Networks
* Resource groups
* Topics
* Users

== Prerequisites

* Install Terraform following the https://learn.hashicorp.com/tutorials/terraform/install-cli[Terraform documentation^].
* Log in to https://cloud.redpanda.com[Redpanda Cloud^], navigate to the *Organization IAM - Service account* page, and create a service account. The service account acts as an OAuth 2.0 client, and you will use its credentials (client ID and client secret) to authenticate to the Cloud API. 

== Limitations

The following functionality is supported in the Cloud API but not in the Redpanda Terraform provider: 

* Managed connectors
* Secrets

== Use the provider

. To install the Redpanda provider, copy and paste the following code into your Terraform configuration file:
+
```
terraform {
  required_providers {
    redpanda = {
      source  = "redpanda-data/redpanda"
      version = "~> 0.5.1"
    }
  }
}
```

. Initialize Terraform:
+
```
terraform init
```

. Add the credentials for the Redpanda Cloud service account you set in the prerequisites. Find the client ID and client secret on the *Organization IAM - Service account* page in Redpanda Cloud. Set them as environment variables, or enter them in your Terraform configuration file:
+
[tabs]
======
Environment variables::
+
--
```
REDPANDA_CLIENT_ID=<client_id>
REDPANDA_CLIENT_SECRET=<client_secret>
```
--
Static credentials::
+
--
```
provider "redpanda" {
  client_id      = "<client_id>"
  client_secret  = "<client_secret>"
}
```
--
======

. For sample configurations, see the https://registry.terraform.io/providers/redpanda-data/redpanda/latest/docs[Redpanda Terraform provider docs^]. 

=== Use the provider to create a new cluster

For an example of how to use the provider to create a new cluster, see https://github.com/redpanda-data/terraform-provider-redpanda/blob/main/examples/cluster/aws/main.tf[this example^].

=== Use the provider to manage an existing cluster

To manage resources in existing Redpanda Cloud clusters, you must reference the existing cluster using the cluster ID (Redpanda ID). The following example creates a topic in a cluster with ID `foo-bar-baz`. The `redpanda_topic` resource contains a field `cluster_api_url` that references the `data.redpanda_cluster.test.cluster_api_url` data resource. 

```
data "redpanda_cluster" "test" {
  id = "foo-bar-baz"
}

resource "redpanda_topic" "test" {
  name               = "myTopicName"
  partition_count    = 3
  replication_factor = 3
  cluster_api_url    = data.redpanda_cluster.test.cluster_api_url
}
```

=== Additional examples

To see more ways to use the provider, see the https://github.com/redpanda-data/terraform-provider-redpanda/tree/main/examples[Redpanda Terraform provider examples^].