---
# This workflow triggers a build of the production docs site
name: build
on:
  push:
    branches: [main, 'v/*', shared, api, site-search, 'v-WIP/*']
permissions:
  id-token: write
  contents: read
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.RP_AWS_CRED_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.RP_AWS_CRED_ACCOUNT_ID }}:role/${{ vars.RP_AWS_CRED_BASE_ROLE_NAME }}${{ github.event.repository.name }}
      - uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            ,sdlc/prod/github/cloud_docs_netlify_build_hook
          parse-json-secrets: true
      - name: Trigger build
        run: curl -X POST -d {} "${{ env.CLOUD_DOCS_NETLIFY_BUILD_HOOK }}"
