= Create a BYOC Cluster on GCP
:description: Use the Redpanda Cloud UI to create a BYOC cluster on GCP.
:page-aliases: get-started:cluster-types/byoc/create-byoc-cluster-gcp.adoc, cloud:create-byoc-cluster-gcp.adoc, deploy:deployment-option/cloud/create-byoc-cluster-gcp

To create a Redpanda cluster in your virtual private cloud (VPC), follow the instructions in the Redpanda Cloud UI. The UI contains the parameters necessary to successfully run `rpk cloud byoc apply`. See also: xref:get-started:byoc-arch.adoc[BYOC architecture].

NOTE: With standard BYOC clusters, Redpanda manages security policies and resources for your VPC, including subnetworks, service accounts, IAM roles, firewall rules, and storage buckets. For the highest level of security, you can manage these resources yourself with a xref:get-started:cluster-types/byoc/gcp/vpc-byo-gcp.adoc[BYOVPC cluster on GCP].

If your clients need to connect from different GCP regions than where your cluster will be deployed, you must enable global access during cluster creation using the Cloud API. To create a BYOC cluster with global access enabled, see xref:networking:byoc/gcp/enable-global-access.adoc[Enable Global Access].

== Prerequisites

Before you deploy a BYOC cluster on GCP, verify the following prerequisites:

* A minimum version of Redpanda `rpk` v24.1. See xref:manage:rpk/rpk-install.adoc[].
* Assign the `roles/editor` role (or higher, such as `roles/owner`) to the GCP user or service account that runs the bootstrap on the target GCP project. This grants the permissions needed to create VPC networks, GKE clusters, service accounts, and other infrastructure during the initial bootstrap. These bootstrap permissions are separate from the xref:security:authorization/cloud-iam-policies-gcp.adoc[agent permissions] that Redpanda assigns after bootstrap.
* The user has the https://cloud.google.com/sdk/docs/install[Google Cloud CLI^] installed and authenticated, with the target project selected. To verify, run:
+
[,bash]
----
gcloud auth list
gcloud config get-value project
----

include::partial$gpq-quotas.adoc[]

== Create a BYOC cluster

. Log in to https://cloud.redpanda.com[Redpanda Cloud^].
. On the Clusters page, click *Create cluster*, then click *Create* for BYOC.
+
Enter a cluster name, then select the resource group, provider (GCP), xref:reference:tiers/byoc-tiers.adoc[region, tier], availability, and Redpanda version.
+
[NOTE]
====
* If you plan to create a private network in your own VPC, select the region where your VPC is located.
* Three availability zones provide two backups in case one availability zone goes down.
====
+
Optionally, click *Advanced settings* to specify up to five key-value custom GCP labels. If a label key starts with `gcp.network-tag.<tag>`, then the agent interprets it as a request to apply the `<tag>` https://cloud.google.com/vpc/docs/add-remove-network-tags[network tag^] to GCE instances in the cluster. Use labels for organization/metadata; use network tags to target firewall rules and routes. After the cluster is created, labels are applied to applicable GCP resources (for example, instances and disks), and network tags are applied to instances. For more information, see the https://cloud.google.com/compute/docs/labeling-resources[GCP documentation^]. After the cluster is created, you can <<manage-custom-resource-labels-and-network-tags,specify more labels with the Cloud API>>. 
. Click *Next*.
. On the Network page, select the connection type: either public or private. For BYOC clusters, private is best-practice.
** Your network name is used to identify this network.
** For a xref:networking:cidr-ranges.adoc[CIDR range], choose one that does not overlap with your existing VPCs or your Redpanda network.
** Clusters with private networking include a setting for API Gateway network access. Public access exposes endpoints for Redpanda Console, the Data Plane API, but they remain protected by your authentication and authorization controls. Private access restricts endpoint access to your VPC only.
+
NOTE: After the cluster is created, you can change the API Gateway access on the Dataplane settings page. If you change from public to private access, users without VPN access to the Redpanda VPC will lose access to these services.
. Click *Next*.
. On the Deploy page, follow the steps to log in to Redpanda Cloud and deploy the agent.
+
As part of agent deployment, Redpanda assigns the permissions required to run the agent. For details about these permissions, see xref:security:authorization/cloud-iam-policies-gcp.adoc[GCP IAM permissions].

include::get-started:partial$no-access.adoc[]

== Manage custom resource labels and network tags

include::get-started:partial$custom-tags-gcp.adoc[]

== Next steps

xref:networking:byoc/gcp/index.adoc[Configure private networking]
