= Create a BYOC Cluster on GCP
:description: Use the Redpanda Cloud UI to create a BYOC cluster on GCP.
:page-aliases: get-started:cluster-types/byoc/create-byoc-cluster-gcp.adoc, cloud:create-byoc-cluster-gcp.adoc, deploy:deployment-option/cloud/create-byoc-cluster-gcp

To create a Redpanda cluster in your virtual private cloud (VPC), follow the instructions in the Redpanda Cloud UI. The UI contains the parameters necessary to successfully run `rpk cloud byoc apply`. See also: xref:get-started:byoc-arch.adoc[BYOC architecture].

NOTE: With standard BYOC clusters, Redpanda manages security policies and resources for your VPC, including subnetworks, service accounts, IAM roles, firewall rules, and storage buckets. For the highest level of security, you can manage these resources yourself with a xref:get-started:cluster-types/byoc/gcp/vpc-byo-gcp.adoc[BYOVPC cluster on GCP].

If your clients need to connect from different GCP regions than where your cluster will be deployed, you must enable global access during cluster creation using the Cloud API. To create a BYOC cluster with global access enabled, see xref:networking:byoc/gcp/enable-global-access.adoc[Enable Global Access].

== Create a BYOC cluster

. Log in to https://cloud.redpanda.com[Redpanda Cloud^].
. On the Clusters page, click *Create cluster*, then click *Create BYOC cluster*.
+
Enter a cluster name, then select the resource group, provider (GCP), xref:reference:tiers/byoc-tiers.adoc[region, tier], availability, and Redpanda version.
+
[NOTE]
====
* If you plan to create a private network in your own VPC, select the region where your VPC is located.
* Three availability zones provide two backups in case one availability zone goes down.
====
+
Optionally, click *Advanced settings* to specify up to five key-value custom labels. GCP labels enable you to make firewall rules and routes applicable to specific clusters. If the key of a label starts with `gcp.network-tag.`, the label is a network tag. After the cluster is created, the labels are applied to all GCP resources associated with this cluster. For more information, see the https://cloud.google.com/compute/docs/labeling-resources[GCP documentation^].

After cluster creation, you can manage custom GCP labels/tags on an existing BYOC cluster with the xref:manage:api/cloud-byoc-controlplane-api.adoc[Cloud Control Plane API].

. Click *Next*.
. On the Network page, enter the connection type: either *Public* or *Private*. For BYOC clusters, *Private* is best-practice.
** Your network name is used to identify this network.
** For a xref:networking:cidr-ranges.adoc[CIDR range], choose one that does not overlap with your existing VPCs or your Redpanda network.
. Click *Next*.
. On the Deploy page, follow the steps to log in to Redpanda Cloud and deploy the agent.
+
Note that `rpk` configures the permissions required by the agent to provision and actively maintain the cluster. For details about these permissions, see xref:security:authorization/cloud-iam-policies-gcp.adoc[GCP IAM permissions].

include::get-started:partial$no-access.adoc[]

== Manage custom tags/labels

In addition to adding custom GCP labels and GCP network tags at create time, you can manage custom GCP labels and tags on an existing BYOC cluster with the xref:manage:api/cloud-byoc-controlplane-api.adoc[Cloud Control Plane API].

Make sure you have:

* The cluster ID. You can find the cluster ID in the Redpanda Cloud UI. Look in the **Details** section of the cluster overview.
* A valid bearer token for the Cloud API. For details, see link:/api/doc/cloud-controlplane/authentication[Authenticate to the API]. 

include::shared:partial$feature-flag.adoc[]

. To refresh agent permissions so the Redpanda agent can update tags, run:
+
[,bash]
----
rpk cloud byoc gcp apply --redpanda-id=$redpanda_id --project_id=$project_id 
----
+
This is because the following IAM actions are required for tag updates:
+
* `compute.disks.get`
* `compute.disks.list`
* `compute.disks.setLabels`
* `compute.instances.setLabels`

. To set or replace tags on an existing BYOC cluster, invoke the Cloud API.
+
The `PATCH` call sets the labels and tags specified under `"cloud_provider_tags"`. It replaces the existing labels and tags with the specified labels and tags. To remove a single entry, omit it from the map you send.
+
[,bash]
----
cluster_patch_body=cat << EOF
{
  "cloud_provider_tags": {
    "custom-label-1": "true",
    "custom-label-2": "true",
    "gcp.network-tag.custom-network-tag-1": "true",
    "gcp.network-tag.custom-network-tag-2": "true"
}

curl -X PATCH "https://api.redpanda.com/v1/clusters/{cluster.id}" \
   -H "Content-Type: application/json" \
   -H "Authorization: Bearer $AUTH_TOKEN" \
----
+
Redpanda Cloud allows up to 16 custom labels and network tags in GCP. 
+
To remove all tags on an existing BYOC cluster, run:
+
[,bash]
----
cluster_patch_body='{"cloud_provider_tags": {}}'

curl -X PATCH "https://api.redpanda.com/v1/clusters/{cluster.id}" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $AUTH_TOKEN" \
  -d "$cluster_patch_body" \
----

== Next steps

xref:networking:byoc/gcp/index.adoc[Configure private networking]
